Repository nginx/nginx-gateway-fabric, pull requests merged in 2022-08, with the labels that each got.

#180 Use stable version of k8s.io/apimachinery
  go.mod
  go.sum
Labels: dependencies

#171 Add GoReleaser, create SBOMs and upload artifacts to Azure
  .github/workflows/ci.yml
  .gitignore
  .goreleaser.yml
  build/Dockerfile
Labels: chore

#182 Add check for go.mod and go.sum changes
  .github/workflows/ci.yml
Labels: chore

#181 Update kube-openapi for CVE-2022-1996
  go.mod
  go.sum
Labels: dependencies

#183 Use new sarif fomat for Trivy
  .github/workflows/ci.yml
Labels: chore

#186 Enable pushing `edge` images
  .github/workflows/ci.yml
Labels: chore

#194 Add Other Changes section to release.yml
  .github/release.yml
Labels: chore

#205 Use 0.1.0 version in release-0.1 branch
  Makefile
  deploy/manifests/nginx-gateway.yaml
  docs/building-the-image.md
  docs/installation.md
Labels: chore

#203 Update README; Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  docs/installation.md
Labels: documentation

#191 Added release process to README.md.
  docs/release-process.md
Labels: documentation

#208 Remove unnecessary HTTPRoute in cafe example
  examples/cafe-example/cafe-routes.yaml
Labels: documentation
