Repository nginx/nginx-gateway-fabric, pull requests merged in 2022-10, with the labels that each got.

#253 Deduplicate endpoints
  internal/state/resolver/resolver.go
  internal/state/resolver/resolver_test.go
  internal/state/resolver/service_resolver_test.go
Labels: bug

#254 Support ObservedGeneration in HTTPRoute status
  internal/state/change_processor_test.go
  internal/state/statuses.go
  internal/state/statuses_test.go
  internal/status/httproute.go
  internal/status/httproute_test.go
  internal/status/updater_test.go
Labels: enhancement

#263 Add release branches to CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: chore

#250 Refactor reconcilers and implementations
  go.mod
  go.sum
  internal/implementations/endpointslice/endpointslice.go
  internal/implementations/endpointslice/endpointslice_test.go
  internal/implementations/endpointslice/implementation_suite_test.go
  internal/implementations/gateway/gateway.go
  internal/implementations/gateway/gateway_test.go
  internal/implementations/gateway/implementation_suite_test.go
  internal/implementations/gatewayclass/gatewayclass.go
  internal/implementations/gatewayclass/gatewayclass_test.go
  internal/implementations/gatewayclass/implementation_suite_test.go
  internal/implementations/httproute/httproute.go
  internal/implementations/secret/implementation_suite_test.go
  internal/implementations/secret/secret.go
  internal/implementations/secret/secret_test.go
  internal/implementations/service/service.go
  internal/manager/controllers.go
  internal/manager/controllers_test.go
  internal/manager/fakes.go
  internal/manager/filter/gatewayclass.go
  internal/manager/filter/gatewayclass_test.go
  internal/manager/index/endpointslice.go
  internal/manager/index/endpointslice_test.go
  internal/manager/index/index.go
  internal/manager/manager.go
  internal/manager/managerfakes/fake_field_indexer.go
  internal/manager/managerfakes/fake_manager.go
  internal/manager/predicate/service.go
  internal/manager/predicate/service_test.go
  internal/reconciler/getter.go
  internal/reconciler/implementation.go
  internal/reconciler/implementation_test.go
  internal/reconciler/reconciler_suite_test.go
  internal/reconciler/reconcilerfakes/fake_getter.go
  internal/state/change_processor_test.go
  internal/state/relationship/capturer.go
  internal/state/relationship/capturer_test.go
  internal/state/resolver/resolver.go
  pkg/sdk/endpointslice_controller.go
  pkg/sdk/gateway_controller.go
  pkg/sdk/gatewayclass_controller.go
  pkg/sdk/httproute_controller.go
  pkg/sdk/interfaces.go
  pkg/sdk/secret_controller.go
Labels: bug, dependencies, chore

#269 Update CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#264 Create SECURITY.md
  SECURITY.md
Labels: documentation, chore

#261 HTTP Traffic Splitting
  README.md
  deploy/manifests/nginx-gateway.yaml
  docs/gateway-api-compatibility.md
  examples/traffic-splitting/README.md
  examples/traffic-splitting/cafe-route-equal-weight.yaml
  examples/traffic-splitting/cafe-route.yaml
  examples/traffic-splitting/cafe.yaml
  examples/traffic-splitting/gateway.yaml
  internal/nginx/config/execute.go
  internal/nginx/config/execute_test.go
  internal/nginx/config/generator.go
  internal/nginx/config/generator_test.go
  internal/nginx/config/http.go
  internal/nginx/config/http/config.go
  internal/nginx/config/servers.go
  internal/nginx/config/servers_template.go
  internal/nginx/config/servers_test.go
  internal/nginx/config/split_clients.go
  internal/nginx/config/split_clients_template.go
  internal/nginx/config/split_clients_test.go
  internal/nginx/config/template.go
  internal/nginx/config/template_test.go
  internal/nginx/config/upstreams.go
  internal/nginx/config/upstreams_template.go
  internal/nginx/config/upstreams_test.go
  internal/nginx/config/variable_names.go
  internal/nginx/config/variable_names_test.go
  internal/state/backend_group.go
  internal/state/backend_group_test.go
  internal/state/backend_refs.go
  internal/state/backend_refs_test.go
  internal/state/change_processor.go
  internal/state/change_processor_test.go
  internal/state/configuration.go
  internal/state/configuration_test.go
  internal/state/graph.go
  internal/state/graph_test.go
  internal/state/relationship/capturer.go
  internal/state/relationship/relationships_test.go
  internal/state/upstreams.go
Labels: documentation, enhancement

#278 Bump kind to 1.25.2
  Makefile
Labels: dependencies

#280 Update repo files for release 0.2.0
  CHANGELOG.md
  Makefile
  README.md
  deploy/manifests/nginx-gateway.yaml
  docs/building-the-image.md
  docs/installation.md
Labels: documentation, chore

#281 Update release date in changelog for 0.2.0
  CHANGELOG.md
Labels: documentation
