Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-11, with the labels that each got.

#931 Enhancement Proposal (Provisional): Data Plane Dynamic Configuration
  docs/proposals/data-plane-config.md
Labels: documentation

#1193 Helm Chart: Support extra volume mounts
  deploy/helm-chart/README.md
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/values.yaml
Labels: documentation, enhancement, helm-chart

#1217 Run CI workflows on all pull requests
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/lint.yml
  .yamllint.yaml
Labels: chore

#1215 Proposal (Implementable): data plane config
  docs/proposals/data-plane-config.md
Labels: documentation

#1220 Merge HTTPRoute conditions
  internal/framework/status/httproute.go
  internal/framework/status/httproute_test.go
  internal/framework/status/setters.go
  internal/framework/status/updater.go
Labels: bug

#1216 Add stubbed NginxProxy CRD and watcher
  apis/v1alpha1/nginxproxy_types.go
  apis/v1alpha1/register.go
  apis/v1alpha1/zz_generated.deepcopy.go
  deploy/helm-chart/README.md
  deploy/helm-chart/crds/gateway.nginx.org_nginxproxies.yaml
  deploy/helm-chart/templates/_helpers.tpl
  deploy/helm-chart/templates/gatewayclass.yaml
  deploy/helm-chart/templates/nginxproxy.yaml
  deploy/helm-chart/templates/rbac.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/crds/gateway.nginx.org_nginxproxies.yaml
  deploy/manifests/nginx-gateway.yaml
  docs/gateway-api-compatibility.md
  internal/framework/status/setters.go
  internal/framework/status/setters_test.go
  internal/framework/status/statuses.go
  internal/framework/status/updater.go
  internal/framework/status/updater_test.go
  internal/mode/static/build_statuses.go
  internal/mode/static/build_statuses_test.go
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/manager.go
  internal/mode/static/manager_test.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/graph/gatewayclass.go
  internal/mode/static/state/graph/gatewayclass_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/nginxproxy.go
  internal/mode/static/state/relationship/capturer.go
  internal/mode/static/state/relationship/capturer_test.go
  internal/mode/static/state/relationship/relationships_test.go
Labels: documentation, chore, helm-chart

#1203 Ensure failed conformance tests are caught in pipeline & fix local make command
  .github/workflows/conformance.yml
  conformance/Makefile
Labels: chore

#1212 Update documents to cover CEL validation on CRDs
  design/resource-validation.md
  docs/resource-validation.md
Labels: documentation

#1239 Correct header name validation
  internal/mode/static/nginx/config/validation/http_njs_match.go
  internal/mode/static/nginx/config/validation/http_njs_match_test.go
Labels: bug

#1242 Remove usage info from log output
  cmd/gateway/commands.go
Labels: bug

#1256 Add test utilities for installing NGF
  .github/workflows/conformance.yml
  Makefile
  conformance/Makefile
  conformance/README.md
  docs/developer/release-process.md
  go.mod
  go.sum
  internal/mode/static/manager.go
  tests/Makefile
  tests/framework/ngf.go
  tests/system_suite_test.go
Labels: documentation, dependencies, tests

#1255 Fix Helm tests on release tag
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
Labels: bug

#1276 Revert some changes to workflow files
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
Labels: chore

#1274 Add basic system test with utilities
  Makefile
  tests/Makefile
  tests/README.md
  tests/framework/portforward.go
  tests/framework/request.go
  tests/framework/resourcemanager.go
  tests/framework/timeout.go
  tests/suite/manifests/hello/gateway.yaml
  tests/suite/manifests/hello/hello.yaml
  tests/suite/manifests/hello/route.yaml
  tests/suite/sample_test.go
  tests/suite/system_suite_test.go
Labels: documentation, tests

#1287 Fix installation docs for mismatched versions
  deploy/helm-chart/README.md
  docs/developer/release-process.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/includes/installation/uninstall-gateway-api-resources.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
Labels: documentation, helm-chart

#1296 Update Control Plane Configuration documentation for Hugo formatting
  site/content/how-to/configuration/control-plane-configuration.md
Labels: documentation

#1295 docs: update architecture doc
  site/content/overview/gateway-architecture.md
Labels: documentation

#1290 Fix broken chart icon links #1289
  deploy/helm-chart/Chart.yaml
Labels: chore, helm-chart

#1302 Update linter version and fix issues
  .github/workflows/lint.yml
  conformance/README.md
  site/content/how-to/monitoring/troubleshooting.md
  site/content/how-to/traffic-management/integrating-cert-manager.md
  site/content/overview/resource-validation.md
  tests/graceful-recovery/results/1.0.0/1.0.0.md
  tests/reconfig/results/1.0.0/1.0.0.md
  tests/zero-downtime-scaling/results/1.0.0/1.0.0.md
Labels: documentation, chore
