Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-08, with the labels that each got.

#905 Add logging guidelines for developers
  docs/developer/go-style-guide.md
  docs/developer/logging-guidelines.md
Labels: documentation

#927 Enhancement Proposal (Provisional): Control Plane Dynamic Config
  docs/proposals/control-plane-config.md
Labels: documentation

#916 Add linting for yaml files
  .github/workflows/codeql-analysis.yml
  .github/workflows/conformance.yml
  .github/workflows/lint.yml
  .github/workflows/scorecards.yml
  .golangci.yml
  .pre-commit-config.yaml
  .yamllint.yaml
  examples/http-header-filter/echo-route.yaml
  examples/http-header-filter/headers.yaml
Labels: chore

#932 Fix function calls with inconsistent argument breaking
  cmd/gateway/commands.go
  docs/developer/go-style-guide.md
  internal/framework/status/updater.go
  internal/mode/provisioner/handler.go
  internal/mode/static/nginx/config/validation/common.go
  internal/mode/static/nginx/config/validation/common_test.go
  internal/mode/static/nginx/config/validation/framework_test.go
  internal/mode/static/nginx/config/validation/http_filters_test.go
  internal/mode/static/nginx/config/validation/http_njs_match_test.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/relationship/relationships_test.go
Labels: documentation, tech-debt

#930 Enhancement Proposal (Implementable): NKG config
  docs/proposals/control-plane-config.md
Labels: documentation

#948 Automatically close stale issues and PRs
  .github/workflows/stale.yml
Labels: chore

#934 Build and use custom nginx container
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  Makefile
  README.md
  build/Dockerfile
  build/Dockerfile.nginx
  conformance/Makefile
  conformance/README.md
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/README.md
  deploy/helm-chart/templates/_helpers.tpl
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/templates/nginx-conf.yaml
  deploy/helm-chart/templates/njs-modules.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway.yaml
  docs/architecture.md
  docs/building-the-image.md
  docs/building-the-images.md
  docs/developer/quickstart.md
  docs/images/nkg-pod.png
  internal/mode/static/nginx/conf/nginx.conf
  internal/mode/static/nginx/file/manager.go
  internal/mode/static/nginx/file/manager_test.go
  internal/mode/static/nginx/runtime/manager.go
Labels: documentation, enhancement

#968 Add README for docs directory
  docs/README.md
Labels: documentation

#967 Bump Go to 1.21
  go.mod
  go.sum
Labels: dependencies

#944 Add a guide about upgrading applications without downtime
  README.md
  docs/guides/upgrade-apps-without-downtime.md
Labels: documentation

#984 Remove init container from architecture doc
  docs/architecture.md
Labels: documentation

#988 Fix builder docker image
  Makefile
  build/Dockerfile
Labels: chore

#989 Fix CRD manifest installation
  .yamllint.yaml
  Makefile
  conformance/Makefile
  deploy/manifests/crds/gateway.nginx.org_nginxgateways.yaml
  deploy/manifests/nginx-gateway.yaml
  docs/developer/quickstart.md
  docs/installation.md
Labels: documentation, chore

#957 Add a cert-manager integration guide
  docs/guides/integrating-cert-manager.md
  docs/images/cert-manager-gateway-workflow.png
Labels: documentation

#990 Add an index page for guides
  docs/README.md
  docs/guides/README.md
Labels: documentation

#992 chore: Fix go lint
  internal/framework/status/httproute.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/graph/gateway_listener_test.go
  internal/mode/static/state/graph/secret.go
Labels: chore

#991 Add Routing Traffic to Your Application Guide
  .gitignore
  docs/guides/README.md
  docs/guides/routing-traffic-to-your-app.md
  docs/images/route-all-traffic-app.png
  docs/images/route-all-traffic-config.png
  docs/images/route-all-traffic-flow.png
  docs/images/src/README.md
  docs/images/src/route-all-traffic-app.mermaid
  docs/images/src/route-all-traffic-config.mermaid
  docs/images/src/route-all-traffic-flow.mermaid
Labels: documentation

#993 Add advanced routing guide
  docs/guides/README.md
  docs/guides/advanced-routing.md
  docs/images/advanced-routing.png
  docs/images/src/advanced-routing.mermaid
  docs/installation.md
  docs/release-process.md
  examples/advanced-routing/README.md
  examples/advanced-routing/cafe-routes.yaml
  examples/advanced-routing/coffee.yaml
  examples/advanced-routing/gateway.yaml
  examples/advanced-routing/tea.yaml
Labels: documentation

#1005 Fix nginx version in README
  README.md
Labels: documentation, chore

#1004 Ensure NKG has least privileges
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/templates/rbac.yaml
  deploy/manifests/nginx-gateway.yaml
Labels: bug

#1006 Refactor codebase using generic GetPointer function
  internal/framework/helpers/helpers.go
  internal/framework/status/updater_test.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/graph/gateway_listener_test.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/relationship/capturer_test.go
  internal/mode/static/state/relationship/relationships_test.go
  internal/mode/static/state/resolver/resolver_test.go
  internal/mode/static/state/resolver/service_resolver_test.go
Labels: tech-debt

#1008 Update Gateway API SDK to 0.8.0
  .github/workflows/ci.yml
  README.md
  cmd/gateway/validation.go
  conformance/Makefile
  conformance/README.md
  deploy/helm-chart/README.md
  docs/developer/quickstart.md
  docs/installation.md
  go.mod
  go.sum
  internal/framework/controller/controllerfakes/fake_manager.go
  internal/framework/status/gateway.go
  internal/framework/status/gateway_test.go
  internal/framework/status/updater_test.go
  internal/mode/static/manager.go
  internal/mode/static/state/change_processor.go
Labels: documentation, dependencies, chore

#999 Integrate NGINX prometheus exporter and enable metrics server
  Makefile
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/validating_types.go
  cmd/gateway/validation.go
  cmd/gateway/validation_test.go
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/README.md
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway.yaml
  docs/architecture.md
  docs/cli-help.md
  docs/images/nkg-pod.png
  docs/monitoring.md
  go.mod
  go.sum
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  internal/mode/static/manager_test.go
  internal/mode/static/metrics/nginx.go
  internal/mode/static/nginx/conf/nginx.conf
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/graph/gateway.go
  internal/mode/static/state/graph/gateway_listener.go
  internal/mode/static/state/graph/gateway_listener_test.go
  internal/mode/static/state/graph/gateway_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/graph_test.go
Labels: documentation, enhancement, dependencies

#1017 Generate conformance report and upload to release
  .github/workflows/conformance.yml
  .gitignore
  conformance/Makefile
  conformance/tests/conformance_test.go
  go.mod
Labels: dependencies, chore

#1018 Fix typo in resource-validation doc
  docs/resource-validation.md
Labels: documentation, chore

#1022 Remove dots in helm release name
  .github/workflows/ci.yml
Labels: chore

#1021 Release 0.6.0
  CHANGELOG.md
  Makefile
  README.md
  conformance/Makefile
  conformance/provisioner/provisioner.yaml
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/Chart.yaml
  deploy/helm-chart/README.md
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway.yaml
  deploy/manifests/service/loadbalancer-aws-nlb.yaml
  deploy/manifests/service/loadbalancer.yaml
  deploy/manifests/service/nodeport.yaml
  docs/building-the-images.md
  docs/guides/advanced-routing.md
  docs/installation.md
Labels: documentation, chore

#1023 Update CHANGELOG and README for release
  CHANGELOG.md
  README.md
  docs/release-process.md
Labels: documentation, chore

#1024 Wait for release to exist for conformance tests
  .github/workflows/conformance.yml
Labels: bug

#1025 Fix docs links and helm version
  CHANGELOG.md
  deploy/helm-chart/README.md
Labels: documentation, chore
