Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-06, with the labels that each got.

#658 Set Gateway Programmed condition
  docs/gateway-api-compatibility.md
  internal/events/handler.go
  internal/events/handler_test.go
  internal/manager/manager.go
  internal/nginx/runtime/manager.go
  internal/state/change_processor.go
  internal/state/change_processor_test.go
  internal/state/conditions/conditions.go
  internal/state/graph/gateway.go
  internal/state/graph/gateway_test.go
  internal/state/statefakes/fake_change_processor.go
  internal/status/gateway.go
  internal/status/gateway_test.go
  internal/status/gatewayclass.go
  internal/status/gatewayclass_test.go
  internal/status/httproute.go
  internal/status/httproute_test.go
  internal/status/statuses.go
  internal/status/statuses_test.go
  internal/status/statusfakes/fake_updater.go
  internal/status/updater.go
  internal/status/updater_test.go
Labels: documentation, enhancement

#716 Ensure uniqueness and validity of generated names and labels
  internal/provisioner/handler.go
  internal/provisioner/handler_test.go
Labels: bug

#718 Add in required capabilities for writing TLS secrets
  deploy/manifests/deployment.yaml
Labels: bug

#722 Update GoReleaser config
  .github/workflows/ci.yml
  .goreleaser.yml
Labels: chore

#680 Add enhancement proposal document and template
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  ISSUE_LIFECYCLE.md
  README.md
  docs/proposals/README.md
  docs/proposals/template.md
Labels: documentation

#730 Fix binding to multiple listeners with empty section name
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
Labels: bug

#733 Improve dev quickstart guide
  docs/developer/quickstart.md
Labels: documentation

#721 AllowedRoutes support for Listeners
  deploy/manifests/rbac.yaml
  docs/gateway-api-compatibility.md
  internal/events/handler.go
  internal/manager/manager.go
  internal/manager/manager_test.go
  internal/state/change_processor.go
  internal/state/change_processor_test.go
  internal/state/conditions/conditions.go
  internal/state/graph/gateway_listener.go
  internal/state/graph/gateway_listener_test.go
  internal/state/graph/gateway_test.go
  internal/state/graph/graph.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
  internal/state/relationship/capturer.go
  internal/state/relationship/capturer_test.go
  internal/state/relationship/relationshipfakes/fake_capturer.go
  internal/state/store.go
Labels: documentation, enhancement

#731 Add SBOM for Docker image
  .github/workflows/ci.yml
  README.md
Labels: documentation, chore

#738 Add enhancement proposal to list of possible issue types
  ISSUE_LIFECYCLE.md
Labels: documentation

#713 Tests/run conformance tests
  conformance/Makefile
  conformance/README.md
  conformance/tests/Dockerfile
  conformance/tests/conformance_test.go
  docs/developer/testing.md
  go.mod
  go.sum
Labels: documentation, dependencies

#739 Update runners to ubuntu-22.04
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fossa.yml
  .github/workflows/labeler.yml
  .github/workflows/lint.yml
  .github/workflows/scorecards.yml
Labels: chore

#676 Add timeout and retry logic for finding NGINX PID file
  internal/nginx/runtime/manager.go
  internal/nginx/runtime/manager_test.go
Labels: bug

#737 Add dependency review workflow and config
  .github/dependency-review-config.yml
  .github/workflows/dependency-review.yml
Labels: chore

#741 Improve provisioner docs
  conformance/provisioner/provisioner.md
Labels: documentation

#753 Add summary of dependency review as comment in the PR
  .github/dependency-review-config.yml
  .github/workflows/dependency-review.yml
Labels: chore

#762 Add actionlint to lint workflow
  .github/workflows/lint.yml
Labels: chore

#756 Add requirements for Docker image in examples
  docs/developer/implementing-a-feature.md
Labels: documentation

#745 Support custom listener ports
  conformance/README.md
  deploy/manifests/service/loadbalancer-aws-nlb.yaml
  deploy/manifests/service/loadbalancer.yaml
  deploy/manifests/service/nodeport.yaml
  docs/gateway-api-compatibility.md
  docs/installation.md
  internal/manager/manager.go
  internal/nginx/config/generator_test.go
  internal/nginx/config/http/config.go
  internal/nginx/config/servers.go
  internal/nginx/config/servers_template.go
  internal/nginx/config/servers_test.go
  internal/nginx/config/upstreams_template.go
  internal/state/change_processor_test.go
  internal/state/conditions/conditions.go
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/graph/gateway_listener.go
  internal/state/graph/gateway_listener_test.go
  internal/state/graph/gateway_test.go
  internal/state/graph/httproute_test.go
  internal/status/statuses_test.go
Labels: documentation, enhancement

#764 Fix spacing in the go style code blocks
  docs/developer/go-style-guide.md
Labels: documentation

#717 Add support for RequestHeaderModifier for HTTPRouteRule objects
  deploy/manifests/nginx-conf.yaml
  docs/gateway-api-compatibility.md
  examples/http-header-filter/README.md
  examples/http-header-filter/echo-route.yaml
  examples/http-header-filter/gateway.yaml
  examples/http-header-filter/headers.yaml
  internal/nginx/config/generator.go
  internal/nginx/config/http/config.go
  internal/nginx/config/maps.go
  internal/nginx/config/maps_template.go
  internal/nginx/config/maps_test.go
  internal/nginx/config/servers.go
  internal/nginx/config/servers_template.go
  internal/nginx/config/servers_test.go
  internal/nginx/config/validation/common.go
  internal/nginx/config/validation/common_test.go
  internal/nginx/config/validation/http_filters.go
  internal/nginx/config/validation/http_filters_test.go
  internal/nginx/config/validation/http_validator.go
  internal/nginx/config/variable_names.go
  internal/nginx/config/variable_names_test.go
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
  internal/state/validation/validationfakes/fake_httpfields_validator.go
  internal/state/validation/validator.go
Labels: documentation, enhancement

#777 Fix/increase nginx timeout
  conformance/Makefile
  conformance/tests/conformance_test.go
  internal/nginx/runtime/manager.go
Labels: bug

#746 Add mend workflow for security scanning
  .github/workflows/fossa.yml
  .github/workflows/lint.yml
  .github/workflows/mend.yml
Labels: chore

#769 Add wildcard hostname support
  docs/gateway-api-compatibility.md
  examples/cafe-example/README.md
  examples/cafe-example/gateway.yaml
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/graph/gateway_listener_test.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
  internal/state/graph/validation.go
  internal/state/graph/validation_test.go
Labels: documentation, enhancement

#784 Regenerate FakeCapturer
  internal/state/relationship/relationshipfakes/fake_capturer.go
Labels: chore

#786 Add Programmed status for listener
  docs/gateway-api-compatibility.md
  internal/state/conditions/conditions.go
  internal/state/graph/gateway_listener.go
  internal/state/graph/gateway_listener_test.go
  internal/state/graph/gateway_test.go
  internal/status/statuses.go
  internal/status/statuses_test.go
Labels: documentation, enhancement

#790 Pin logex dependency to licensed version
  go.mod
  go.sum
Labels: dependencies, chore

#789 Prioritize method matching
  internal/state/dataplane/sort.go
  internal/state/dataplane/sort_test.go
Labels: bug

#787 Run conformance tests in pod on cluster
  conformance/Makefile
  conformance/README.md
  conformance/tests/conformance-rbac.yaml
  docs/developer/quickstart.md
  docs/developer/testing.md
Labels: bug, documentation

#799 Add NewListenerInvalidRouteKinds condition
  docs/gateway-api-compatibility.md
  internal/state/conditions/conditions.go
  internal/state/graph/gateway_listener.go
Labels: bug, documentation

#800 Update validateBackendRef invalid group error conditions
  internal/state/graph/backend_refs.go
  internal/state/graph/backend_refs_test.go
Labels: bug

#792 Run conformance tests in the CI pipeline
  .github/workflows/ci.yml
  Makefile
  conformance/Makefile
  conformance/README.md
  conformance/tests/Dockerfile
Labels: documentation, enhancement

#804 Set GatewayClass status for ignored GatewayClasses
  cmd/gateway/commands.go
  conformance/Makefile
  docs/gateway-api-compatibility.md
  internal/manager/manager.go
  internal/manager/predicate/gatewayclass.go
  internal/manager/predicate/gatewayclass_test.go
  internal/manager/predicate/service_test.go
  internal/provisioner/handler.go
  internal/provisioner/handler_test.go
  internal/provisioner/manager.go
  internal/state/conditions/conditions.go
  internal/state/graph/gatewayclass.go
  internal/state/graph/gatewayclass_test.go
  internal/state/graph/graph.go
  internal/status/statuses.go
  internal/status/statuses_test.go
  internal/status/updater.go
  internal/status/updater_test.go
Labels: bug, documentation
