Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-07, with the labels that each got.

#778 Bump CodeQL actions to v2.20.1
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/scorecards.yml
Labels: dependencies

#813 Update release branch dependencies
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/scorecards.yml
  internal/nginx/modules/package-lock.json
  internal/nginx/modules/package.json
Labels: chore

#801 Add logic for defining port in redirect based on scheme
  internal/nginx/config/servers.go
  internal/nginx/config/servers_test.go
Labels: bug

#810 Release 0.4.0
  CHANGELOG.md
  Makefile
  README.md
  conformance/Makefile
  conformance/provisioner/provisioner.yaml
  deploy/manifests/deployment.yaml
  docs/building-the-image.md
  docs/installation.md
Labels: documentation, chore

#806 Support cross-namespace BackendRefs in HTTPRoutes
  docs/gateway-api-compatibility.md
  examples/cross-namespace-routing/README.md
  examples/cross-namespace-routing/cafe-ns-and-app.yaml
  examples/cross-namespace-routing/cafe-routes.yaml
  examples/cross-namespace-routing/gateway.yaml
  examples/cross-namespace-routing/reference-grant.yaml
  examples/https-termination/README.md
  examples/https-termination/reference-grant.yaml
  internal/state/change_processor_test.go
  internal/state/graph/backend_refs.go
  internal/state/graph/backend_refs_test.go
  internal/state/graph/gateway.go
  internal/state/graph/gateway_listener.go
  internal/state/graph/gateway_test.go
  internal/state/graph/graph.go
  internal/state/graph/graph_test.go
  internal/state/graph/reference_grant.go
  internal/state/graph/reference_grant_test.go
Labels: documentation, enhancement

#819 Skip conformance tests on tags
  .github/workflows/ci.yml
Labels: bug

#820 Update README and CHANGELOG for the latest release
  CHANGELOG.md
  README.md
Labels: documentation, chore

#807 Watch for Secrets
  internal/events/handler.go
  internal/events/handler_test.go
  internal/manager/manager.go
  internal/nginx/config/configfakes/fake_generator.go
  internal/nginx/config/generator.go
  internal/nginx/config/generator_test.go
  internal/nginx/config/servers.go
  internal/nginx/config/servers_test.go
  internal/nginx/file/file_suite_test.go
  internal/nginx/file/filefakes/fake_clear_folders_osfile_manager.go
  internal/nginx/file/filefakes/fake_dir_entry.go
  internal/nginx/file/filefakes/fake_manager.go
  internal/nginx/file/filefakes/fake_osfile_manager.go
  internal/nginx/file/folders.go
  internal/nginx/file/folders_test.go
  internal/nginx/file/manager.go
  internal/nginx/file/manager_test.go
  internal/nginx/file/os_filemanager.go
  internal/state/change_processor.go
  internal/state/change_processor_test.go
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/graph/gateway.go
  internal/state/graph/gateway_listener.go
  internal/state/graph/gateway_test.go
  internal/state/graph/graph.go
  internal/state/graph/graph_test.go
  internal/state/graph/secret.go
  internal/state/graph/secret_test.go
  internal/state/secrets/file_manager.go
  internal/state/secrets/secrets.go
  internal/state/secrets/secrets_test.go
  internal/state/secrets/secretsfakes/fake_secret_disk_memory_manager.go
  internal/state/secrets/secretsfakes/fake_secret_store.go
  internal/state/store.go
Labels: enhancement

#827 Set proxy host header to the exact value of the request host header
  internal/nginx/config/maps_template.go
  internal/nginx/config/maps_test.go
  internal/nginx/config/servers_template.go
Labels: bug

#829 Update gateway listener compatibility doc
  docs/gateway-api-compatibility.md
Labels: documentation

#844 Check for changes in generated files in GitHub workflow
  .github/workflows/ci.yml
Labels: chore

#817 Ensure Prefix matching requires trailing slash
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
Labels: bug

#851 Update developer docs
  docs/developer/go-style-guide.md
  docs/developer/pull-request.md
Labels: documentation

#852 Update the release process doc for conformance tests
  docs/release-process.md
Labels: documentation, chore

#857 Update dependabot after refactor
  .github/dependabot.yml
Labels: chore

#860 Set support level to Core in the Gateway API Compatibility doc
  docs/gateway-api-compatibility.md
Labels: documentation

#740 Add variables to makefile help and build-goreleaser target
  .gitignore
  Makefile
Labels: chore

#864 Fix example output
  examples/http-header-filter/README.md
  examples/https-termination/README.md
Labels: documentation

#861 Add dependabot config for conformance tests Dockerfile
  .github/dependabot.yml
Labels: chore

#859 Fix docs to make copying commands easier
  README.md
  conformance/README.md
  conformance/provisioner/README.md
  design/control-data-plane-separation/design.md
  docs/building-the-image.md
  docs/developer/quickstart.md
  docs/developer/testing.md
  docs/installation.md
  docs/resource-validation.md
  docs/running-on-kind.md
  examples/advanced-routing/README.md
  examples/cafe-example/README.md
  examples/cross-namespace-routing/README.md
  examples/http-header-filter/README.md
  examples/https-termination/README.md
  examples/traffic-splitting/README.md
  internal/mode/static/nginx/modules/README.md
Labels: documentation

#866 Release 0.5.0
  CHANGELOG.md
  Makefile
  README.md
  conformance/Makefile
  conformance/provisioner/provisioner.yaml
  deploy/manifests/deployment.yaml
  docs/building-the-image.md
  docs/installation.md
Labels: documentation, chore

#871 Update incorrect link - release 0.4
  README.md
Labels: documentation, chore

#870 Update README and CHANGELOG for 0.5.0 release
  CHANGELOG.md
  README.md
Labels: documentation, chore

#873 Update incorrect link - release 0.2
  README.md
Labels: documentation, chore

#872 Update incorrect link - release 0.3
  README.md
Labels: documentation, chore

#869 Update formatting for names and output in docs
  conformance/provisioner/README.md
  docs/architecture.md
  docs/developer/design-principles.md
  docs/installation.md
  docs/resource-validation.md
  examples/advanced-routing/README.md
  examples/cafe-example/README.md
  examples/cross-namespace-routing/README.md
  examples/http-header-filter/README.md
  examples/https-termination/README.md
  examples/traffic-splitting/README.md
Labels: documentation

#888 Fix Makefile variables
  Makefile
Labels: bug

#889 Fix local build
  build/Dockerfile
Labels: bug

#883 Add linting for markdown files
  .github/workflows/lint.yml
  .markdownlint-cli2.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_LIFECYCLE.md
  README.md
  SECURITY.md
  conformance/README.md
  conformance/provisioner/README.md
  design/archive/gateway-evaluation.md
  design/control-data-plane-separation/design.md
  design/resource-validation.md
  docs/architecture.md
  docs/building-the-image.md
  docs/cli-help.md
  docs/developer/branching-and-workflow.md
  docs/developer/go-style-guide.md
  docs/developer/implementing-a-feature.md
  docs/developer/pull-request.md
  docs/developer/quickstart.md
  docs/developer/testing.md
  docs/gateway-api-compatibility.md
  docs/installation.md
  docs/proposals/README.md
  docs/proposals/template.md
  docs/release-process.md
  docs/resource-validation.md
  docs/running-on-kind.md
  examples/advanced-routing/README.md
  examples/cafe-example/README.md
  examples/cross-namespace-routing/README.md
  examples/http-header-filter/README.md
  examples/https-termination/README.md
  examples/traffic-splitting/README.md
  internal/mode/static/nginx/modules/README.md
Labels: documentation, chore

#884 Run conformance tests nightly on main branch
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  conformance/Makefile
  conformance/README.md
  conformance/scripts/install-gateway.sh
  conformance/scripts/uninstall-gateway.sh
Labels: documentation

#865 Add token-permissions to CI workflow
  .github/workflows/ci.yml
Labels: chore

#894 Bump semver for CVE
  internal/mode/static/nginx/modules/package-lock.json
Labels: dependencies

#897 Sign checksum with cosign
  .github/workflows/ci.yml
  .goreleaser.yml
Labels: chore

#840 Add Helm Chart to install NKG
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  Makefile
  conformance/Makefile
  deploy/helm-chart/.helmignore
  deploy/helm-chart/Chart.yaml
  deploy/helm-chart/README.md
  deploy/helm-chart/chart-icon.png
  deploy/helm-chart/templates/_helpers.tpl
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/templates/gatewayclass.yaml
  deploy/helm-chart/templates/nginx-conf.yaml
  deploy/helm-chart/templates/njs-modules.yaml
  deploy/helm-chart/templates/rbac.yaml
  deploy/helm-chart/templates/service.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/njs-modules.yaml
  docs/developer/implementing-a-feature.md
  docs/developer/quickstart.md
  docs/installation.md
  docs/release-process.md
  internal/mode/static/nginx/modules/README.md
Labels: documentation, enhancement

#906 Fix permissions in Helm job
  .github/workflows/ci.yml
Labels: chore

#907 Read dependency config from central repo
  .github/dependency-review-config.yml
  .github/workflows/dependency-review.yml
Labels: chore

#910 Specify where to find draft changelog in release process doc
  docs/release-process.md
Labels: documentation, chore
