Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-02, with the labels that each got.

#399 Add Dockerfile for agent
  Makefile
  build/nginx-with-agent/Dockerfile
  build/nginx-with-agent/entrypoint.sh
  build/nginx-with-agent/nginx-agent.conf
  build/nginx-with-agent/nginx-with-agent.yaml
  build/nginx-with-agent/nginx.conf
Labels: enhancement

#407 Implement NKG-specific field validation for Gateway resource
  internal/state/change_processor_test.go
  internal/state/conditions/conditions.go
  internal/state/conditions/conditions_test.go
  internal/state/conditions/httproute.go
  internal/state/conditions/httproute_test.go
  internal/state/configuration_test.go
  internal/state/graph.go
  internal/state/graph_test.go
  internal/state/listener.go
  internal/state/listener_test.go
  internal/state/statuses.go
  internal/state/statuses_test.go
  internal/status/conditions.go
  internal/status/conditions_test.go
  internal/status/gateway.go
  internal/status/gateway_test.go
  internal/status/httproute.go
  internal/status/httproute_test.go
  internal/status/updater_test.go
Labels: enhancement

#420 Use strict versions in package.json and align CI
  .github/workflows/lint.yml
  internal/nginx/modules/package-lock.json
  internal/nginx/modules/package.json
Labels: chore

#423 Use read-only npm command
  .github/workflows/ci.yml
Labels: chore

#419 Remove pinned dependencies
  go.mod
  go.sum
Labels: dependencies, chore

#431 Add Issue Lifecycle and update Contributing
  CONTRIBUTING.md
  ISSUE_LIFECYCLE.md
Labels: documentation

#432 Refactor graph and configuration into separate packages
  internal/events/handler.go
  internal/events/handler_test.go
  internal/manager/manager.go
  internal/nginx/config/configfakes/fake_generator.go
  internal/nginx/config/generator.go
  internal/nginx/config/generator_test.go
  internal/nginx/config/servers.go
  internal/nginx/config/servers_test.go
  internal/nginx/config/split_clients.go
  internal/nginx/config/split_clients_test.go
  internal/nginx/config/upstreams.go
  internal/nginx/config/upstreams_test.go
  internal/sort/doc.go
  internal/sort/sort.go
  internal/sort/sort_test.go
  internal/state/change_processor.go
  internal/state/change_processor_test.go
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/dataplane/doc.go
  internal/state/dataplane/sort.go
  internal/state/dataplane/sort_test.go
  internal/state/dataplane/warnings.go
  internal/state/dataplane/warnings_test.go
  internal/state/graph/backend_group.go
  internal/state/graph/backend_group_test.go
  internal/state/graph/backend_refs.go
  internal/state/graph/backend_refs_test.go
  internal/state/graph/doc.go
  internal/state/graph/gateway.go
  internal/state/graph/gateway_test.go
  internal/state/graph/gatewayclass.go
  internal/state/graph/gatewayclass_test.go
  internal/state/graph/graph.go
  internal/state/graph/graph_test.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
  internal/state/graph_test.go
  internal/state/listener_test.go
  internal/state/secrets/file_manager.go
  internal/state/secrets/secrets.go
  internal/state/secrets/secrets_test.go
  internal/state/secrets/secretsfakes/fake_dir_entry.go
  internal/state/secrets/secretsfakes/fake_file_manager.go
  internal/state/secrets/secretsfakes/fake_secret_disk_memory_manager.go
  internal/state/secrets/secretsfakes/fake_secret_store.go
  internal/state/statefakes/fake_change_processor.go
  internal/state/statuses.go
  internal/state/statuses_test.go
Labels: chore
