Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-05, with the labels that each got.

#609 Set upstream zone size to 512k
  internal/nginx/config/upstreams_template.go
Labels: bug

#626 Allow empty sectionName in HTTPRoute parentRef
  docs/gateway-api-compatibility.md
  examples/advanced-routing/cafe-routes.yaml
  internal/nginx/config/servers.go
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
Labels: documentation, enhancement

#601 Move BackendGroup to dataplane package
  internal/nginx/config/generator_test.go
  internal/nginx/config/servers_test.go
  internal/nginx/config/split_clients.go
  internal/nginx/config/split_clients_test.go
  internal/state/change_processor_test.go
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/graph/backend_group.go
  internal/state/graph/backend_group_test.go
  internal/state/graph/backend_refs.go
  internal/state/graph/backend_refs_test.go
  internal/state/graph/graph.go
  internal/state/graph/graph_test.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
Labels: tech-debt

#645 Set ResolvedRefs condition to true on HTTPRoutes
  docs/gateway-api-compatibility.md
  internal/state/change_processor_test.go
  internal/state/conditions/conditions.go
Labels: documentation, enhancement

#638 Set gateway Pod IP as GatewayStatus address
  cmd/gateway/gateway_suite_test.go
  cmd/gateway/main.go
  cmd/gateway/main_test.go
  cmd/gateway/setup_test.go
  deploy/manifests/nginx-gateway.yaml
  docs/gateway-api-compatibility.md
  go.mod
  go.sum
  internal/config/config.go
  internal/manager/manager.go
  internal/status/gateway.go
  internal/status/gateway_test.go
  internal/status/updater.go
  internal/status/updater_test.go
Labels: documentation, enhancement, dependencies

#646 Refactor controllers registration
  internal/controller/controller_suite_test.go
  internal/controller/controllerfakes/fake_field_indexer.go
  internal/controller/controllerfakes/fake_getter.go
  internal/controller/controllerfakes/fake_manager.go
  internal/controller/doc.go
  internal/controller/fakes.go
  internal/controller/getter.go
  internal/controller/reconciler.go
  internal/controller/reconciler_test.go
  internal/controller/register.go
  internal/controller/register_test.go
  internal/manager/filter/gatewayclass.go
  internal/manager/manager.go
Labels: tech-debt

#633 Set Accepted condition type on Gateway status
  docs/gateway-api-compatibility.md
  internal/state/change_processor_test.go
  internal/state/conditions/conditions.go
  internal/state/graph/gateway.go
  internal/state/graph/gateway_listener.go
  internal/state/graph/gateway_test.go
  internal/state/graph/graph_test.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
  internal/state/statuses.go
  internal/state/statuses_test.go
  internal/status/conditions_test.go
  internal/status/gateway.go
  internal/status/gateway_test.go
  internal/status/gatewayclass_test.go
  internal/status/httproute_test.go
  internal/status/updater.go
  internal/status/updater_test.go
Labels: documentation, enhancement

#650 Allow empty HTTPRoute hostnames
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/graph/gateway_listener.go
  internal/state/graph/gateway_test.go
  internal/state/graph/graph_test.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
Labels: bug

#651 Allow long server names
  deploy/manifests/nginx-gateway.yaml
Labels: bug

#656 Support multiple commands in gateway binary
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/main.go
  cmd/gateway/main_test.go
  cmd/gateway/setup.go
  cmd/gateway/setup_test.go
  cmd/gateway/validation.go
  cmd/gateway/validation_test.go
  deploy/manifests/nginx-gateway.yaml
  docs/cli-args.md
  docs/cli-help.md
  docs/gateway-api-compatibility.md
  go.mod
  go.sum
Labels: documentation, enhancement, dependencies

#657 Make static mode compatible with provisioner
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/validation.go
  cmd/gateway/validation_test.go
  docs/cli-help.md
  docs/gateway-api-compatibility.md
  internal/config/config.go
  internal/controller/reconciler.go
  internal/controller/register_test.go
  internal/manager/filter/filter.go
  internal/manager/filter/filter_test.go
  internal/manager/filter/gatewayclass.go
  internal/manager/filter/gatewayclass_test.go
  internal/manager/manager.go
  internal/manager/manager_test.go
  internal/status/status_suit_test.go
  internal/status/updater.go
  internal/status/updater_test.go
Labels: documentation, enhancement

#674 Fix supported gateway conditions in compatibility doc
  docs/gateway-api-compatibility.md
Labels: documentation

#675 Update route condition where listener is not found
  docs/gateway-api-compatibility.md
  internal/state/conditions/conditions.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
Labels: documentation, enhancement

#682 Update k8s and controller-runtime dependencies
  go.mod
  go.sum
  internal/controller/controllerfakes/fake_manager.go
  internal/status/updater_test.go
Labels: dependencies, chore

#669 Add developer guide to CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/developer/branching-and-workflow.md
  docs/developer/code-review-pyramid.jpeg
  docs/developer/implementing-a-feature.md
  docs/developer/pull-request.md
  docs/developer/quickstart.md
  docs/developer/testing.md
Labels: documentation, chore

#684 Bump nginx from 1.23 to 1.25
  CHANGELOG.md
  README.md
  deploy/manifests/nginx-gateway.yaml
Labels: documentation, dependencies

#678 Move nginx.conf to ConfigMap
  deploy/manifests/nginx-gateway.yaml
Labels: chore

#697 Update labeler config with new format
  .github/labeler.yml
  .github/workflows/labeler.yml
Labels: chore

#699 Update release step to use GitHub Action
  .github/workflows/ci.yml
  .github/workflows/release.yaml
Labels: chore
