Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-01, with the labels that each got.

#350 Fix status for parentRef with invalid listener
  internal/state/conditions/httproute.go
  internal/state/graph.go
  internal/state/graph_test.go
Labels: bug

#351 Fix Observed Generation for Gateway Status
  internal/state/change_processor_test.go
  internal/state/statuses.go
  internal/state/statuses_test.go
  internal/status/gateway.go
  internal/status/gateway_test.go
  internal/status/updater_test.go
Labels: bug

#356 Always generate a root "/" location block
  internal/nginx/config/servers.go
  internal/nginx/config/servers_test.go
Labels: enhancement

#343 Add a design doc for resource validation
  design/resource-validation.md
Labels: documentation

#360 Calculate max capacity for locations slice
  internal/nginx/config/servers.go
Labels: bug

#328 Bump kind to 1.26.0
  Makefile
Labels: chore

#344 Add design doc for Control Plane and Data Plane Separation
  design/control-data-plane-separation/connect-response.png
  design/control-data-plane-separation/connect.png
  design/control-data-plane-separation/deployment-architecture.png
  design/control-data-plane-separation/design.md
  design/control-data-plane-separation/download-config.png
Labels: documentation

#388 Run webhook validation
  deploy/manifests/nginx-gateway.yaml
  internal/manager/controllers.go
  internal/manager/controllers_test.go
  internal/manager/manager.go
  internal/manager/validators.go
  internal/manager/validators_test.go
  internal/reconciler/implementation.go
  internal/reconciler/implementation_test.go
  internal/reconciler/reconcilerfakes/fake_event_recorder.go
  internal/reconciler/recorder.go
  internal/state/change_processor.go
  internal/state/change_processor_test.go
Labels: enhancement
