Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-03, with the labels that each got.

#449 Add agent registration
  .github/workflows/ci.yml
  build/nginx-with-agent/clusterip.yaml
  build/nginx-with-agent/nginx-agent.conf
  build/nginx-with-agent/nginx-with-agent.yaml
  deploy/manifests/nginx-gateway.yaml
  go.mod
  go.sum
  internal/agent/agent_suite_test.go
  internal/agent/doc.go
  internal/agent/pool.go
  internal/agent/pool_test.go
  internal/events/handler_test.go
  internal/grpc/commander/agent.go
  internal/grpc/commander/channel.go
  internal/grpc/commander/channel_test.go
  internal/grpc/commander/commander.go
  internal/grpc/commander/commander_suite_test.go
  internal/grpc/commander/commander_test.go
  internal/grpc/commander/commanderfakes/fake_agent.go
  internal/grpc/commander/commanderfakes/fake_agent_manager.go
  internal/grpc/commander/commanderfakes/fake_commander_command_channel_server.go
  internal/grpc/commander/commanderfakes/fake_commander_upload_server.go
  internal/grpc/commander/connection.go
  internal/grpc/commander/connection_test.go
  internal/grpc/commander/doc.go
  internal/grpc/commander/exchanger/doc.go
  internal/grpc/commander/exchanger/exchanger.go
  internal/grpc/commander/exchanger/exchangerfakes/fake_command_exchanger.go
  internal/grpc/commander/test_helpers.go
  internal/grpc/doc.go
  internal/grpc/server.go
  internal/grpc/server_test.go
  internal/grpc/service/commander.go
  internal/manager/manager.go
  internal/state/change_processor_test.go
  internal/state/dataplane/configuration_test.go
  internal/state/resolver/service_resolver_test.go
Labels: enhancement, dependencies

#495 Implement NKG-specific validation for GatewayClass
  internal/state/change_processor_test.go
  internal/state/conditions/conditions.go
  internal/state/dataplane/configuration_test.go
  internal/state/graph/gatewayclass.go
  internal/state/graph/gatewayclass_test.go
  internal/state/graph/graph.go
  internal/state/graph/graph_test.go
  internal/state/statuses.go
  internal/state/statuses_test.go
  internal/status/gatewayclass.go
  internal/status/gatewayclass_test.go
  internal/status/updater_test.go
Labels: enhancement

#497 Remove redundant comment about query param validation
  internal/nginx/modules/src/httpmatches.js
Labels: chore

#502 Remove redundant warnings
  internal/state/change_processor.go
  internal/state/dataplane/configuration.go
  internal/state/dataplane/configuration_test.go
  internal/state/dataplane/warnings.go
  internal/state/dataplane/warnings_test.go
Labels: enhancement

#503 Improve Gateway validation error messages
  internal/state/graph/gateway.go
  internal/state/graph/gateway_test.go
Labels: enhancement

#504 Simplify hostname validation for HTTPRoute
  internal/nginx/config/validation/http_validator.go
  internal/nginx/config/validation/http_validator_test.go
  internal/state/graph/httproute.go
  internal/state/graph/httproute_test.go
  internal/state/validation/validationfakes/fake_httpfields_validator.go
  internal/state/validation/validator.go
Labels: chore, area/httproute/core

#505 Add webhook installation to docs
  docs/installation.md
Labels: documentation

#429 Bump Go to 1.20
  go.mod
Labels: dependencies
