Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-09, with the labels that each got.

#1020 Run conformance tests on minimum k8s version
  .github/workflows/conformance.yml
  conformance/Makefile
  conformance/README.md
Labels: documentation, chore

#1027 Run helm tests on tag event
  .github/workflows/ci.yml
Labels: chore

#1026 Refactor codebase to use inline error checking
  internal/framework/controller/reconciler.go
  internal/framework/controller/register.go
  internal/framework/events/first_eventbatch_preparer.go
  internal/framework/helpers/helpers.go
  internal/framework/status/updater.go
  internal/mode/provisioner/deployment.go
  internal/mode/provisioner/handler.go
  internal/mode/provisioner/manager.go
  internal/mode/static/handler.go
  internal/mode/static/manager.go
  internal/mode/static/nginx/config/execute.go
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/state/graph/gateway_listener.go
  internal/mode/static/state/graph/httproute.go
  internal/mode/static/state/resolver/service_resolver_test.go
Labels: tech-debt

#1040 Optimize default nginx config
  internal/mode/static/nginx/conf/nginx.conf
  internal/mode/static/nginx/config/servers_template.go
Labels: bug

#1038 Move release process doc and update READMEs
  README.md
  docs/README.md
  docs/developer/logging-guidelines.md
  docs/developer/release-process.md
Labels: documentation

#1033 Ensure NGINX reload occurs
  docs/architecture.md
  docs/images/nkg-pod.png
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/version.go
  internal/mode/static/nginx/config/version_template.go
  internal/mode/static/nginx/config/version_test.go
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/nginx/runtime/manager_test.go
  internal/mode/static/nginx/runtime/runtimefakes/fake_manager.go
  internal/mode/static/nginx/runtime/verify.go
  internal/mode/static/nginx/runtime/verify_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
Labels: bug, documentation

#1046 Replace unit test assertions with Gomega matchers
  cmd/gateway/commands_test.go
  cmd/gateway/validation_test.go
  conformance/tests/conformance_test.go
  internal/framework/controller/filter/filter_test.go
  internal/framework/controller/index/endpointslice_test.go
  internal/framework/controller/predicate/gatewayclass_test.go
  internal/framework/controller/predicate/service_test.go
  internal/framework/controller/register_test.go
  internal/framework/events/events_test.go
  internal/framework/status/conditions_test.go
  internal/framework/status/gateway_test.go
  internal/framework/status/gatewayclass_test.go
  internal/framework/status/httproute_test.go
  internal/mode/static/build_statuses_test.go
  internal/mode/static/manager_test.go
  internal/mode/static/nginx/config/execute_test.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/maps_test.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/split_clients_test.go
  internal/mode/static/nginx/config/upstreams_test.go
  internal/mode/static/nginx/config/validation/framework_test.go
  internal/mode/static/nginx/config/variable_names_test.go
  internal/mode/static/nginx/file/folders_test.go
  internal/mode/static/sort/sort_test.go
  internal/mode/static/state/conditions/conditions_test.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/convert_test.go
  internal/mode/static/state/dataplane/sort_test.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/gateway_listener_test.go
  internal/mode/static/state/graph/gateway_test.go
  internal/mode/static/state/graph/gatewayclass_test.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/reference_grant_test.go
  internal/mode/static/state/graph/secret_test.go
  internal/mode/static/state/graph/validation_test.go
  internal/mode/static/state/relationship/relationships_test.go
  internal/mode/static/state/resolver/resolver_test.go
Labels: tech-debt

#1047 Add readiness probe
  Makefile
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/validation.go
  cmd/gateway/validation_test.go
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/README.md
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway.yaml
  docs/architecture.md
  docs/cli-help.md
  internal/mode/static/config/config.go
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/health.go
  internal/mode/static/health_test.go
  internal/mode/static/manager.go
  internal/mode/static/state/graph/graph_test.go
Labels: documentation, enhancement

#1019 Add workflow for updating nginx base image
  .github/workflows/update-docker-images.yml
Labels: chore

#1072 Update workflows
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/conformance.yml
  .github/workflows/fossa.yml
  .github/workflows/lint.yml
  .github/workflows/scorecards.yml
Labels: chore

#1048 Support Horizontal Scaling
  Makefile
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/README.md
  deploy/helm-chart/templates/_helpers.tpl
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/templates/rbac.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway.yaml
  docs/architecture.md
  docs/cli-help.md
  internal/framework/status/statuses.go
  internal/framework/status/statusfakes/fake_updater.go
  internal/framework/status/updater.go
  internal/framework/status/updater_test.go
  internal/mode/provisioner/deployment.go
  internal/mode/provisioner/handler.go
  internal/mode/provisioner/handler_test.go
  internal/mode/static/build_statuses.go
  internal/mode/static/build_statuses_test.go
  internal/mode/static/config/config.go
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/leader.go
  internal/mode/static/manager.go
Labels: documentation, enhancement

#1069 Update go version in go.mod
  go.mod
  go.sum
Labels: dependencies, chore

#1049 Add NGINX reload counters
  docs/monitoring.md
  internal/mode/static/manager.go
  internal/mode/static/metrics/collector.go
  internal/mode/static/metrics/metrics.go
  internal/mode/static/metrics/nginx.go
  internal/mode/static/nginx/runtime/manager.go
Labels: documentation, enhancement

#1092 Add deployment manifests as release artifacts
  .goreleaser.yml
  Makefile
  scripts/combine-crds.sh
Labels: chore

#1089 Add upgrade instructions
  docs/installation.md
Labels: documentation

#1093 Update GW API to 0.8.1
  .github/workflows/ci.yml
  README.md
  cmd/gateway/validation.go
  conformance/Makefile
  conformance/README.md
  deploy/helm-chart/README.md
  docs/developer/quickstart.md
  docs/installation.md
  go.mod
  go.sum
  internal/mode/static/state/change_processor.go
Labels: documentation, dependencies, chore

#1062 Implement Status Updater Retrying on Failures
  internal/framework/status/k8s_updater.go
  internal/framework/status/statusfakes/fake_k8s_updater.go
  internal/framework/status/updater.go
  internal/framework/status/updater_retry_test.go
  internal/framework/status/updater_test.go
Labels: enhancement
