Repository nginx/nginx-gateway-fabric, pull requests merged in 2023-10, with the labels that each got.

#1115 Scale test
  tests/scale/generate_manifests.go
  tests/scale/manifests/prom-clusterrole.yaml
  tests/scale/manifests/scale-matches.yaml
  tests/scale/manifests/scale-upstreams.yaml
  tests/scale/results/1.0.0/1.0.0.md
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/CPU.png
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/Memory.png
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/TTR.png
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/results-10s-delay.csv
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/results-no-delay.csv
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/results.csv
  tests/scale/results/1.0.0/TestScale_HTTPSListeners/CPU.png
  tests/scale/results/1.0.0/TestScale_HTTPSListeners/Memory.png
  tests/scale/results/1.0.0/TestScale_HTTPSListeners/TTR.png
  tests/scale/results/1.0.0/TestScale_HTTPSListeners/results.csv
  tests/scale/results/1.0.0/TestScale_Listeners/CPU.png
  tests/scale/results/1.0.0/TestScale_Listeners/Memory.png
  tests/scale/results/1.0.0/TestScale_Listeners/TTR.png
  tests/scale/results/1.0.0/TestScale_Listeners/results.csv
  tests/scale/results/1.0.0/TestScale_UpstreamServers/CPU.png
  tests/scale/results/1.0.0/TestScale_UpstreamServers/Memory.png
  tests/scale/scale.md
  tests/scale/scale_test.go
Labels: documentation, tests

#1116 Add reconfig tests setup and results
  tests/reconfig/results/v1.0.0.md
  tests/reconfig/scripts/cafe-routes.yaml
  tests/reconfig/scripts/cafe.yaml
  tests/reconfig/scripts/certificate-ns-and-cafe-secret.yaml
  tests/reconfig/scripts/create-resources-gw-last.sh
  tests/reconfig/scripts/create-resources-routes-last.sh
  tests/reconfig/scripts/delete-multiple.sh
  tests/reconfig/scripts/gateway.yaml
  tests/reconfig/scripts/reference-grant.yaml
  tests/reconfig/setup.md
Labels: documentation

#1113 Add longevity test plan and results
  .yamllint.yaml
  tests/longevity/longevity.md
  tests/longevity/manifests/cafe-routes.yaml
  tests/longevity/manifests/cafe-secret.yaml
  tests/longevity/manifests/cafe.yaml
  tests/longevity/manifests/cronjob.yaml
  tests/longevity/manifests/gateway.yaml
  tests/longevity/manifests/prom.yaml
  tests/longevity/results/1.0.0/1.0.0.md
  tests/longevity/results/1.0.0/cpu.png
  tests/longevity/results/1.0.0/memory.png
  tests/longevity/results/1.0.0/reload-time.png
  tests/longevity/results/1.0.0/reloads.png
  tests/longevity/results/1.0.0/stub-status.png
Labels: documentation

#1111 Add Graceful Recovery Baseline Test
  tests/graceful-recovery/graceful-recovery.md
  tests/graceful-recovery/results/1.0.0/1.0.0.md
Labels: documentation

#1128 Use single timeout for reload retries
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/nginx/runtime/manager_test.go
  internal/mode/static/nginx/runtime/verify.go
  internal/mode/static/nginx/runtime/verify_test.go
Labels: bug

#1130 Return error when leader lease is lost
  internal/mode/static/leader.go
Labels: bug

#1137 Fix fieldalignment error
  internal/mode/static/handler.go
Labels: bug

#1132 Fix NGF fails to recover if conf files are unexpectedly removed
  internal/mode/static/nginx/file/manager.go
  internal/mode/static/nginx/file/manager_test.go
Labels: bug

#1120 Add zero downtime upgrade test plan and results
  tests/zero-downtime-upgrades/manifests/cafe-routes.yaml
  tests/zero-downtime-upgrades/manifests/cafe-secret.yaml
  tests/zero-downtime-upgrades/manifests/cafe.yaml
  tests/zero-downtime-upgrades/manifests/gateway-updated.yaml
  tests/zero-downtime-upgrades/manifests/gateway.yaml
  tests/zero-downtime-upgrades/requests-plot.gp
  tests/zero-downtime-upgrades/results/1.0.0/1.0.0.md
  tests/zero-downtime-upgrades/results/1.0.0/http.csv
  tests/zero-downtime-upgrades/results/1.0.0/http.png
  tests/zero-downtime-upgrades/results/1.0.0/https.csv
  tests/zero-downtime-upgrades/results/1.0.0/https.png
  tests/zero-downtime-upgrades/zero-downtime-upgrades.md
Labels: documentation

#1140 Add dataplane performance test
  tests/dataplane-performance/manifests/cafe-routes.yaml
  tests/dataplane-performance/manifests/coffee.yaml
  tests/dataplane-performance/manifests/gateway.yaml
  tests/dataplane-performance/results/1.0.0/1.0.0.md
  tests/dataplane-performance/scripts/post.lua
  tests/dataplane-performance/scripts/wrk-latency.sh
  tests/dataplane-performance/setup.md
Labels: documentation, tests

#1146 Add tests section to labeler config
  .github/labeler.yml
Labels: chore

#1141 Set Service address in Gateway Status
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  conformance/Makefile
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/templates/deployment.yaml
  deploy/manifests/nginx-gateway.yaml
  docs/cli-help.md
  docs/gateway-api-compatibility.md
  docs/installation.md
  internal/framework/controller/predicate/service.go
  internal/framework/controller/predicate/service_test.go
  internal/framework/status/gateway.go
  internal/framework/status/gateway_test.go
  internal/framework/status/statuses.go
  internal/framework/status/statusfakes/fake_updater.go
  internal/framework/status/updater.go
  internal/framework/status/updater_test.go
  internal/mode/provisioner/handler_test.go
  internal/mode/static/build_statuses.go
  internal/mode/static/build_statuses_test.go
  internal/mode/static/config/config.go
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/manager.go
Labels: documentation, enhancement

#1153 Improve installation doc
  docs/installation.md
Labels: documentation

#1167 Upgrade apk packages when building nginx image
  build/Dockerfile.nginx
Labels: chore

#1160 Add PartiallyInvalid HTTPRoute Condition
  docs/gateway-api-compatibility.md
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/graph/httproute.go
  internal/mode/static/state/graph/httproute_test.go
Labels: documentation, enhancement

#1151 Only update a resource's status if it has changed
  internal/framework/status/setters.go
  internal/framework/status/setters_test.go
  internal/framework/status/updater.go
  internal/framework/status/updater_retry_test.go
  internal/framework/status/updater_test.go
  internal/mode/static/manager.go
  tests/scale/results/1.0.0/1.0.0.md
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/CPU-no-delay.png
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/CPU.png
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/Memory-no-delay.png
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/Memory.png
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/TTR.png
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/results-10s-delay.csv
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/results-no-delay.csv
  tests/scale/results/1.0.0/TestScale_HTTPRoutes/results.csv
  tests/scale/results/1.0.0/TestScale_HTTPSListeners/CPU.png
  tests/scale/results/1.0.0/TestScale_HTTPSListeners/Memory.png
  tests/scale/results/1.0.0/TestScale_HTTPSListeners/TTR.png
  tests/scale/results/1.0.0/TestScale_HTTPSListeners/results.csv
  tests/scale/results/1.0.0/TestScale_Listeners/CPU.png
  tests/scale/results/1.0.0/TestScale_Listeners/Memory.png
  tests/scale/results/1.0.0/TestScale_Listeners/TTR.png
  tests/scale/results/1.0.0/TestScale_Listeners/results.csv
  tests/scale/results/1.0.0/TestScale_UpstreamServers/CPU.png
  tests/scale/results/1.0.0/TestScale_UpstreamServers/Memory.png
  tests/scale/scale.md
  tests/scale/scale_test.go
Labels: bug, documentation

#1170 Update Go to latest version
  go.mod
Labels: dependencies, chore

#1172 Fix pre-commit and action linter
  .github/workflows/lint.yml
  .golangci.yml
  .pre-commit-config.yaml
Labels: chore

#1159 Implement delayed termination to achieve zero downtime upgrades
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/main.go
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/README.md
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway.yaml
  docs/cli-help.md
  tests/zero-downtime-upgrades/results/1.0.0-special/1.0.0-special.md
  tests/zero-downtime-upgrades/results/1.0.0-special/http.csv
  tests/zero-downtime-upgrades/results/1.0.0-special/http.png
  tests/zero-downtime-upgrades/results/1.0.0-special/https.csv
  tests/zero-downtime-upgrades/results/1.0.0-special/https.png
  tests/zero-downtime-upgrades/values.yaml
  tests/zero-downtime-upgrades/zero-downtime-upgrades.md
Labels: documentation, enhancement

#1177 Fail run conformance test make target on test failure
  conformance/Makefile
Labels: bug

#1179 Update helm chart to 1.0; fix links
  deploy/helm-chart/Chart.yaml
  docs/developer/release-process.md
Labels: documentation, chore

#1184 Update docs and versions for 1.0
  CHANGELOG.md
  Makefile
  README.md
  conformance/Makefile
  conformance/provisioner/provisioner.yaml
  conformance/provisioner/static-deployment.yaml
  deploy/helm-chart/Chart.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway.yaml
  deploy/manifests/service/loadbalancer-aws-nlb.yaml
  deploy/manifests/service/loadbalancer.yaml
  deploy/manifests/service/nodeport.yaml
  docs/building-the-images.md
  docs/guides/advanced-routing.md
  docs/installation.md
  examples/http-header-filter/README.md
Labels: documentation, chore

#1186 Add event batch processing results and rerun reconfig test
  tests/reconfig/results/1.0.0/1.0.0.md
  tests/reconfig/results/v1.0.0.md
  tests/reconfig/setup.md
Labels: documentation, tests

#1188 Add event batch processing results and rerun reconfig test (#1186)
  tests/reconfig/results/1.0.0/1.0.0.md
  tests/reconfig/results/v1.0.0.md
  tests/reconfig/setup.md
Labels: documentation, chore

#1191 Update installation docs for release branch
  docs/installation.md
Labels: documentation, chore

#1189 Update docs for release
  CHANGELOG.md
  README.md
  docs/developer/release-process.md
  docs/installation.md
Labels: documentation, chore

#1204 Fix release process phrasing
  docs/developer/release-process.md
Labels: documentation, chore

#1206 Add helm-chart label to changes affecting the Helm chart
  .github/labeler.yml
  .github/release.yml
Labels: chore

#1192 Helm Chart: Add support for tolerations
  deploy/helm-chart/README.md
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/values.yaml
Labels: documentation, enhancement, helm-chart
