Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-10, with the labels that each got.

#2608 Add hugo version check and theme update to Makefile
  site/Makefile
  site/go.mod
  site/go.sum
  site/hugo-entrypoint.sh
Labels: community

#2649 Add init container for setting up base config
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/include-configmap.yaml
  charts/nginx-gateway-fabric/templates/scc.yaml
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/main.go
  config/tests/static-deployment.yaml
  deploy/aws-nlb/deploy.yaml
  deploy/azure/deploy.yaml
  deploy/default/deploy.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  deploy/nginx-plus/deploy.yaml
  deploy/nodeport/deploy.yaml
  deploy/openshift/deploy.yaml
  internal/mode/static/handler_test.go
  internal/mode/static/manager.go
  internal/mode/static/state/dataplane/configuration.go
Labels: enhancement, helm-chart

#2666 Fix main includes
  charts/nginx-gateway-fabric/values.schema.json
  deploy/snippets-filters-nginx-plus/deploy.yaml
  deploy/snippets-filters/deploy.yaml
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/main_config.go
  internal/mode/static/nginx/config/main_config_template.go
  internal/mode/static/nginx/config/main_config_test.go
  internal/mode/static/nginx/config/main_includes.go
  internal/mode/static/nginx/config/main_includes_template.go
  internal/mode/static/nginx/config/main_includes_test.go
Labels: bug, helm-chart

#2664 Functional Tests for SnippetsFilter
  tests/framework/ngf.go
  tests/suite/manifests/snippets-filter/cafe.yaml
  tests/suite/manifests/snippets-filter/gateway.yaml
  tests/suite/manifests/snippets-filter/grpc-backend.yaml
  tests/suite/manifests/snippets-filter/invalid-context-sf.yaml
  tests/suite/manifests/snippets-filter/invalid-duplicate-sf.yaml
  tests/suite/manifests/snippets-filter/valid-sf.yaml
  tests/suite/snippets_filter_test.go
Labels: tests

#2668 Complete enhancement proposal
  docs/proposals/rewrite-client-ip.md
Labels: chore

#2679 Update Docker updater workflow
  .github/workflows/build.yml
  .github/workflows/update-docker-images.yml
Labels: chore

#2684 Only set stream status zone if hostname exists
  internal/mode/static/nginx/config/stream_servers_template.go
Labels: bug, release-notes

#2685 Fix failing unit test
  internal/mode/static/config_updater_test.go
Labels: tests

#2677 Collect SnippetsFilter information
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/data.avdl
  internal/mode/static/telemetry/data_attributes_generated.go
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/ngfresourcecounts_attributes_generated.go
  site/content/overview/product-telemetry.md
  tests/suite/telemetry_test.go
Labels: documentation, enhancement, tests

#2695 Lower upstream count for scale nfr test with nginx plus
  tests/README.md
  tests/suite/scale_test.go
Labels: documentation, tests

#2694 Update gateway api version to 1.2.0
  README.md
  cmd/gateway/validation.go
  config/crd/gateway-api/experimental/kustomization.yaml
  config/crd/gateway-api/standard/kustomization.yaml
  go.mod
  go.sum
  internal/framework/gatewayclass/validate.go
  internal/mode/static/state/graph/grpcroute.go
  internal/mode/static/state/graph/grpcroute_test.go
  internal/mode/static/state/graph/route_common.go
  tests/go.mod
  tests/go.sum
Labels: documentation, dependencies, chore

#2698 Add workaround for renovate
  .github/workflows/ci.yml
Labels: chore

#2705 Fix permissions for git-auto-commit-action
  .github/workflows/ci.yml
Labels: chore

#2701 Add docs for rewrite client IP settings
  site/content/how-to/data-plane-configuration.md
Labels: documentation

#2710 Use NGINX_PAT to checkout renovate's PRs
  .github/workflows/ci.yml
Labels: chore

#2700 Add new "Get started" document
  site/content/get-started.md
  site/content/how-to/_index.md
  site/content/installation/_index.md
  site/content/installation/running-on-kind.md
  site/content/reference/_index.md
  site/content/releases.md
  site/content/support.md
  site/go.mod
  site/go.sum
Labels: documentation

#2717 (cherry-pick) Add new "Get started" document (#2700)
  site/content/get-started.md
  site/content/how-to/_index.md
  site/content/installation/_index.md
  site/content/installation/running-on-kind.md
  site/content/reference/_index.md
  site/content/releases.md
  site/content/support.md
  site/go.mod
  site/go.sum
Labels: documentation

#2712 Move renovate build to separate workflow
  .github/.cache/buster-for-generate
  .github/workflows/ci.yml
  .github/workflows/renovate-build.yml
Labels: chore

#2720 Limit PRs from renovate to once a day
  renovate.json
Labels: chore

#2703 Feature/topology spread constraints
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
Labels: documentation, helm-chart

#2693 Update support.md
  site/content/support.md
Labels: documentation

#2715 Add request header tutorial to how-to guides
  examples/http-request-header-filter/README.md
  examples/http-response-header-filter/README.md
  site/content/how-to/data-plane-configuration.md
  site/content/how-to/traffic-management/request-response-headers.md
  site/content/how-to/traffic-management/response-headers.md
Labels: documentation
