Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-04, with the labels that each got.

#1696 Add delete predicate for gateway class
  internal/framework/controller/predicate/gatewayclass.go
  internal/framework/controller/predicate/gatewayclass_test.go
Labels: community

#1797 Fix permissions for Release PR workflow
  .github/workflows/release-pr.yml
Labels: chore

#1798 Move CRDs to config directory
  .yamllint.yaml
  Makefile
  config/crd/bases/gateway.nginx.org_nginxgateways.yaml
  deploy/helm-chart/crds
  deploy/manifests/crds
  deploy/manifests/crds/gateway.nginx.org_nginxgateways.yaml
Labels: chore, helm-chart

#1793 Add ClientSettingsPolicy CRD
  apis/v1alpha1/clientsettingspolicy_types.go
  apis/v1alpha1/nginxgateway_types.go
  apis/v1alpha1/register.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.nginx.org_clientsettingspolicies.yaml
  config/crd/bases/gateway.nginx.org_nginxgateways.yaml
  docs/proposals/client-settings.md
Labels: documentation, enhancement

#1776 Gateway Settings Enhancement Proposal
  docs/proposals/gateway-settings.md
Labels: documentation, enhancement-proposal

#1814 Refactor Status Updater to be resource agnostic
  internal/framework/conditions/conditions.go
  internal/framework/conditions/conditions_test.go
  internal/framework/helpers/helpers.go
  internal/framework/helpers/helpers_test.go
  internal/framework/status/backend_tls.go
  internal/framework/status/backend_tls_test.go
  internal/framework/status/clock.go
  internal/framework/status/conditions.go
  internal/framework/status/conditions_test.go
  internal/framework/status/gateway.go
  internal/framework/status/gateway_test.go
  internal/framework/status/gatewayclass.go
  internal/framework/status/gatewayclass_test.go
  internal/framework/status/httproute.go
  internal/framework/status/httproute_test.go
  internal/framework/status/k8s_updater.go
  internal/framework/status/leader_aware_group_updater.go
  internal/framework/status/leader_aware_group_updater_test.go
  internal/framework/status/statuses.go
  internal/framework/status/statusfakes/fake_clock.go
  internal/framework/status/statusfakes/fake_group_updater.go
  internal/framework/status/statusfakes/fake_updater.go
  internal/framework/status/updater.go
  internal/framework/status/updater_test.go
  internal/mode/provisioner/handler.go
  internal/mode/provisioner/handler_test.go
  internal/mode/provisioner/manager.go
  internal/mode/static/build_statuses.go
  internal/mode/static/build_statuses_test.go
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/manager.go
  internal/mode/static/status/prepare_requests.go
  internal/mode/static/status/prepare_requests_test.go
  internal/mode/static/status/status_setters.go
  internal/mode/static/status/status_setters_test.go
Labels: tech-debt

#1795 ObservabilityPolicy Enhancement Proposal
  docs/proposals/observability.md
Labels: documentation, enhancement-proposal

#1815 Add NginxProxy CRD
  apis/v1alpha1/clientsettingspolicy_types.go
  apis/v1alpha1/nginxproxy_types.go
  apis/v1alpha1/register.go
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
Labels: enhancement

#1849 Add EditorConfig
  .editorconfig
  internal/mode/static/nginx/modules/src/httpmatches.js
  internal/mode/static/nginx/modules/test/httpmatches.test.js
Labels: chore

#1848 Add ObservabilityPolicy CRD
  apis/v1alpha1/nginxproxy_types.go
  apis/v1alpha1/observabilitypolicy_types.go
  apis/v1alpha1/register.go
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  config/crd/bases/gateway.nginx.org_observabilitypolicies.yaml
  docs/proposals/observability.md
Labels: documentation, enhancement

#1862 Move the helm chart to charts
  .github/labeler.yml
  .github/workflows/ci.yml
  .github/workflows/release-pr.yml
  .pre-commit-config.yaml
  .yamllint.yaml
  Makefile
  charts/nginx-gateway-fabric/.helmignore
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/chart-icon.png
  charts/nginx-gateway-fabric/crds
  charts/nginx-gateway-fabric/templates/_helpers.tpl
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/gatewayclass.yaml
  charts/nginx-gateway-fabric/templates/nginxgateway.yaml
  charts/nginx-gateway-fabric/templates/rbac.yaml
  charts/nginx-gateway-fabric/templates/service.yaml
  charts/nginx-gateway-fabric/values.yaml
  docs/developer/implementing-a-feature.md
  docs/developer/quickstart.md
  site/content/how-to/monitoring/prometheus.md
  site/content/installation/installing-ngf/helm.md
  site/content/overview/gateway-architecture.md
  tests/suite/system_suite_test.go
Labels: documentation, chore

#1885 Update minimum k8s version to 1.25
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  Makefile
  README.md
  charts/nginx-gateway-fabric/README.md
  conformance/Makefile
  conformance/README.md
  conformance/scripts/install-gateway.sh
  conformance/scripts/uninstall-gateway.sh
  design/resource-validation.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/includes/installation/uninstall-gateway-api-resources.md
  site/content/installation/installing-ngf/manifests.md
  site/content/overview/resource-validation.md
  tests/framework/ngf.go
Labels: documentation, chore, helm-chart, release-notes

#1879 Remove 390x and ppc64le platforms
  .github/workflows/ci.yml
  .goreleaser.yml
Labels: chore

#1829 fix: Fix reload errors due long matching conditions
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/maps.go
  internal/mode/static/nginx/config/maps_test.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/split_clients.go
  internal/mode/static/nginx/config/split_clients_test.go
  internal/mode/static/nginx/config/upstreams.go
  internal/mode/static/nginx/config/upstreams_test.go
  internal/mode/static/nginx/modules/src/httpmatches.js
  internal/mode/static/nginx/modules/test/httpmatches.test.js
Labels: bug

#1900 Remove replace no longer needed
  go.mod
Labels: dependencies, chore

#1890 Fix crdPath in automated tests when applying the crd directory
  tests/framework/ngf.go
Labels: bug

#1870 Support NginxProxy CRD and global tracing settings
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/_helpers.tpl
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/gatewayclass.yaml
  charts/nginx-gateway-fabric/templates/nginxproxy.yaml
  charts/nginx-gateway-fabric/templates/rbac.yaml
  charts/nginx-gateway-fabric/values.yaml
  conformance/provisioner/static-deployment.yaml
  deploy/manifests/nginx-gateway-experimental.yaml
  deploy/manifests/nginx-gateway.yaml
  deploy/manifests/nginx-plus-gateway-experimental.yaml
  deploy/manifests/nginx-plus-gateway.yaml
  docs/proposals/gateway-settings.md
  internal/mode/static/manager.go
  internal/mode/static/manager_test.go
  internal/mode/static/nginx/conf/nginx-plus.conf
  internal/mode/static/nginx/conf/nginx.conf
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/maps_template.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/split_clients_template.go
  internal/mode/static/nginx/config/telemetry.go
  internal/mode/static/nginx/config/telemetry_template.go
  internal/mode/static/nginx/config/telemetry_test.go
  internal/mode/static/nginx/config/upstreams_template.go
  internal/mode/static/nginx/config/validation/generic.go
  internal/mode/static/nginx/config/validation/generic_test.go
  internal/mode/static/nginx/config/version_template.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/gatewayclass.go
  internal/mode/static/state/graph/gatewayclass_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/nginxproxy.go
  internal/mode/static/state/graph/nginxproxy_test.go
  internal/mode/static/state/validation/validationfakes/fake_generic_validator.go
  internal/mode/static/state/validation/validator.go
  site/content/installation/installing-ngf/helm.md
  site/content/overview/gateway-api-compatibility.md
Labels: documentation, enhancement, helm-chart, release-notes

#1835 GRPCRoute Support
  Makefile
  README.md
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  charts/nginx-gateway-fabric/templates/rbac.yaml
  conformance/Makefile
  deploy/manifests/nginx-gateway-experimental.yaml
  deploy/manifests/nginx-plus-gateway-experimental.yaml
  go.mod
  go.sum
  internal/framework/gatewayclass/validate.go
  internal/mode/static/handler.go
  internal/mode/static/manager.go
  internal/mode/static/manager_test.go
  internal/mode/static/nginx/conf/grpc-error-locations.conf
  internal/mode/static/nginx/conf/grpc-error-pages.conf
  internal/mode/static/nginx/conf/nginx-plus.conf
  internal/mode/static/nginx/conf/nginx.conf
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/sort.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/gateway_listener.go
  internal/mode/static/state/graph/gateway_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/grpcroute.go
  internal/mode/static/state/graph/grpcroute_test.go
  internal/mode/static/state/graph/httproute.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/route_common_test.go
  internal/mode/static/state/graph/service.go
  internal/mode/static/state/graph/service_test.go
  internal/mode/static/status/prepare_requests.go
  internal/mode/static/status/prepare_requests_test.go
  internal/mode/static/status/status_setters.go
  internal/mode/static/status/status_setters_test.go
  internal/mode/static/telemetry/collector_test.go
  site/content/overview/gateway-api-compatibility.md
Labels: documentation, enhancement, dependencies, helm-chart
