Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-08, with the labels that each got.

#2324 Remove steps no longer needed
  tests/README.md
Labels: documentation

#2319 Read Go build info from the binary
  .goreleaser.yml
  Makefile
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/main.go
Labels: chore

#2323 Add seccompProfile to Helm chart
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/scc.yaml
  config/tests/static-deployment.yaml
  deploy/manifests/nginx-gateway-experimental.yaml
  deploy/manifests/nginx-gateway.yaml
  deploy/manifests/nginx-plus-gateway-experimental.yaml
  deploy/manifests/nginx-plus-gateway.yaml
  deploy/manifests/scc.yaml
Labels: enhancement, helm-chart

#2292 Add Helm Chart examples
  .gitignore
  .goreleaser.yml
  .yamllint.yaml
  Makefile
  charts/nginx-gateway-fabric/templates/_helpers.tpl
  charts/nginx-gateway-fabric/templates/clusterrole.yaml
  charts/nginx-gateway-fabric/templates/clusterrolebinding.yaml
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/serviceaccount.yaml
  config/base/kustomization.yaml
  config/base/namespace.yaml
  deploy/README.md
  deploy/aws-nlb/deploy.yaml
  deploy/azure/deploy.yaml
  deploy/default/deploy.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  deploy/kustomization.yaml
  deploy/manifests/scc.yaml
  deploy/manifests/service/loadbalancer-aws-nlb.yaml
  deploy/manifests/service/loadbalancer.yaml
  deploy/manifests/service/nodeport.yaml
  deploy/nginx-plus/deploy.yaml
  deploy/nodeport/deploy.yaml
  deploy/openshift/deploy.yaml
  docs/developer/quickstart.md
  examples/helm/README.md
  examples/helm/aws-nlb/values.yaml
  examples/helm/azure/values.yaml
  examples/helm/default/values.yaml
  examples/helm/experimental-nginx-plus/values.yaml
  examples/helm/experimental/values.yaml
  examples/helm/nginx-plus/values.yaml
  examples/helm/nodeport/values.yaml
  scripts/generate-manifests.sh
  site/content/how-to/monitoring/prometheus.md
  site/content/how-to/monitoring/tracing.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/how-to/traffic-management/https-termination.md
  site/content/how-to/traffic-management/redirects-and-rewrites.md
  site/content/how-to/traffic-management/response-headers.md
  site/content/how-to/traffic-management/routing-traffic-to-your-app.md
  site/content/how-to/traffic-management/securing-backend-traffic.md
  site/content/includes/installation/expose-nginx-gateway-fabric.md
  site/content/includes/installation/next-step-expose-fabric.md
  site/content/installation/expose-nginx-gateway-fabric.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  tests/Makefile
Labels: documentation, chore, helm-chart

#2314 Disallow route to attach to listener if not present in allowed routes.
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/graph/gateway_listener.go
  internal/mode/static/state/graph/gateway_listener_test.go
  internal/mode/static/state/graph/gateway_test.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/route_common_test.go
Labels: bug

#2330 Add missing variables and format scripts
  .github/workflows/nfr.yml
  .pre-commit-config.yaml
  scripts/generate-manifests.sh
  tests/reconfig/scripts/create-resources-gw-last.sh
  tests/reconfig/scripts/create-resources-routes-last.sh
  tests/reconfig/scripts/delete-multiple.sh
  tests/scripts/add-local-ip-auth-networks.sh
  tests/scripts/check-pod-exit-code.sh
  tests/scripts/cleanup-router.sh
  tests/scripts/cleanup-vm.sh
  tests/scripts/create-and-setup-gcp-vm.sh
  tests/scripts/create-gke-cluster.sh
  tests/scripts/create-gke-router.sh
  tests/scripts/delete-gke-cluster.sh
  tests/scripts/remote-scripts/run-nfr-tests.sh
  tests/scripts/remote-scripts/run-tests.sh
  tests/scripts/run-tests-gcp-vm.sh
  tests/scripts/sync-files-to-vm.sh
  tests/suite/scripts/longevity-wrk.sh
Labels: chore

#2329 Rewrite Client IP Enhancement Proposal
  docs/proposals/rewrite-client-ip.md
Labels: documentation, enhancement

#2337 Check for ReferenceGrants from GRPCRoutes to Services
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/reference_grant.go
  internal/mode/static/state/graph/reference_grant_test.go
Labels: bug, release-notes

#2332 Add options for chart version and add command output
  .golangci.yml
  tests/Makefile
  tests/framework/ngf.go
  tests/scripts/sync-files-to-vm.sh
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: chore

#2318 Restrict policies to non-duplicate routes
  internal/mode/static/handler.go
  internal/mode/static/manager.go
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/maps_template.go
  internal/mode/static/nginx/config/maps_test.go
  internal/mode/static/nginx/config/policies/clientsettings/generator.go
  internal/mode/static/nginx/config/policies/clientsettings/generator_test.go
  internal/mode/static/nginx/config/policies/clientsettings/validator.go
  internal/mode/static/nginx/config/policies/clientsettings/validator_test.go
  internal/mode/static/nginx/config/policies/generator.go
  internal/mode/static/nginx/config/policies/generator_test.go
  internal/mode/static/nginx/config/policies/observability/generator.go
  internal/mode/static/nginx/config/policies/observability/generator_test.go
  internal/mode/static/nginx/config/policies/observability/validator.go
  internal/mode/static/nginx/config/policies/observability/validator_test.go
  internal/mode/static/nginx/config/policies/policies_suite_test.go
  internal/mode/static/nginx/config/policies/policiesfakes/fake_generator.go
  internal/mode/static/nginx/config/policies/policiesfakes/fake_object_kind.go
  internal/mode/static/nginx/config/policies/policiesfakes/fake_policy.go
  internal/mode/static/nginx/config/policies/policiesfakes/fake_validator.go
  internal/mode/static/nginx/config/policies/policy.go
  internal/mode/static/nginx/config/policies/validator.go
  internal/mode/static/nginx/config/policies/validator_test.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/validation/http_njs_match_test.go
  internal/mode/static/nginx/modules/src/httpmatches.js
  internal/mode/static/nginx/modules/test/httpmatches.test.js
  internal/mode/static/policies/clientsettings/generator.go
  internal/mode/static/policies/observability/generator.go
  internal/mode/static/policies/observability/generator_test.go
  internal/mode/static/policies/policiesfakes/fake_config_generator.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/httproute.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/policies.go
  internal/mode/static/state/graph/policies_test.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/store.go
  internal/mode/static/state/validation/validationfakes/fake_policy_validator.go
  internal/mode/static/state/validation/validator.go
  internal/mode/static/status/status_setters.go
  internal/mode/static/status/status_setters_test.go
  site/content/how-to/monitoring/tracing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/overview/custom-policies.md
  tests/Makefile
  tests/suite/manifests/clientsettings/cafe-routes.yaml
  tests/suite/manifests/hello-world/routes.yaml
Labels: bug, documentation, release-notes

#2347 Print logs and events on test failure
  tests/Makefile
  tests/framework/info.go
  tests/framework/resourcemanager.go
  tests/scripts/cleanup-router.sh
  tests/scripts/cleanup-vm.sh
  tests/suite/system_suite_test.go
Labels: tests

#2353 Add NGF build information to test results
  .github/workflows/functional.yml
  Makefile
  tests/Makefile
  tests/framework/info.go
  tests/framework/results.go
  tests/scripts/remote-scripts/run-nfr-tests.sh
  tests/scripts/remote-scripts/run-tests.sh
  tests/scripts/run-tests-gcp-vm.sh
  tests/suite/client_settings_test.go
  tests/suite/dataplane_perf_test.go
  tests/suite/graceful_recovery_test.go
  tests/suite/longevity_test.go
  tests/suite/sample_test.go
  tests/suite/scale_test.go
  tests/suite/system_suite_test.go
  tests/suite/telemetry_test.go
  tests/suite/tracing_test.go
  tests/suite/upgrade_test.go
Labels: tests

#2211 add support for TLS route
  .github/workflows/conformance.yml
  charts/nginx-gateway-fabric/templates/clusterrole.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  internal/framework/gatewayclass/validate.go
  internal/framework/kinds/kinds.go
  internal/mode/static/handler.go
  internal/mode/static/manager.go
  internal/mode/static/manager_test.go
  internal/mode/static/nginx/config/base_http_config_template.go
  internal/mode/static/nginx/config/base_http_config_test.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/maps.go
  internal/mode/static/nginx/config/maps_template.go
  internal/mode/static/nginx/config/maps_test.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/shared/config.go
  internal/mode/static/nginx/config/stream/config.go
  internal/mode/static/nginx/config/stream_servers.go
  internal/mode/static/nginx/config/stream_servers_template.go
  internal/mode/static/nginx/config/stream_servers_test.go
  internal/mode/static/nginx/config/upstreams.go
  internal/mode/static/nginx/config/upstreams_test.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/gateway_listener.go
  internal/mode/static/state/graph/gateway_listener_test.go
  internal/mode/static/state/graph/gateway_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/route_common_test.go
  internal/mode/static/state/graph/service.go
  internal/mode/static/state/graph/service_test.go
  internal/mode/static/state/graph/tlsroute.go
  internal/mode/static/state/graph/tlsroute_test.go
  internal/mode/static/status/prepare_requests.go
  internal/mode/static/status/prepare_requests_test.go
  internal/mode/static/status/status_setters.go
  internal/mode/static/status/status_setters_test.go
  tests/Makefile
  tests/conformance/conformance-rbac.yaml
  tests/conformance/conformance_test.go
Labels: enhancement, helm-chart

#2358 Remove var buildInfo
  Makefile
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
Labels: chore

#2361 Run tests in cmd/ in parallel
  .golangci.yml
  cmd/gateway/commands_test.go
  cmd/gateway/validation_test.go
Labels: tests

#2360 Add server zone metrics
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/stream/config.go
  internal/mode/static/nginx/config/stream_servers.go
  internal/mode/static/nginx/config/stream_servers_template.go
  internal/mode/static/nginx/config/stream_servers_test.go
Labels: enhancement, release-notes

#2364 Fix flaky unit tests
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/graph/policies_test.go
Labels: chore

#2313 Automate Reconfiguration Performance Test
  tests/framework/prometheus.go
  tests/framework/resourcemanager.go
  tests/reconfig/scripts/create-resources-gw-last.sh
  tests/reconfig/scripts/create-resources-routes-last.sh
  tests/reconfig/scripts/delete-multiple.sh
  tests/reconfig/setup.md
  tests/results/reconfig/1.0.0/1.0.0.md
  tests/results/reconfig/1.1.0/1.1.0.md
  tests/results/reconfig/1.2.0/1.2.0.md
  tests/results/reconfig/1.3.0/1.3.0.md
  tests/suite/manifests/reconfig/cafe-routes.yaml
  tests/suite/manifests/reconfig/cafe-secret.yaml
  tests/suite/manifests/reconfig/cafe.yaml
  tests/suite/manifests/reconfig/gateway.yaml
  tests/suite/manifests/reconfig/reference-grant.yaml
  tests/suite/reconfig_test.go
  tests/suite/scale_test.go
  tests/suite/system_suite_test.go
Labels: documentation, tests

#2380 Increase timeout for NFR tests to 5h
  tests/Makefile
Labels: chore

#2381 Add teardown of NGF to start of reconfiguration performance test
  tests/suite/reconfig_test.go
Labels: tests

#2391 Add NFR flag to NGF configuration on reconfiguration performance test
  tests/suite/reconfig_test.go
Labels: tests

#2392 Run mend workflow on releases
  .github/workflows/mend.yml
Labels: chore

#2379 Support cross-namespace routing with TLSRoutes
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/reference_grant.go
  internal/mode/static/state/graph/reference_grant_test.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/route_common_test.go
  internal/mode/static/state/graph/tlsroute.go
  internal/mode/static/state/graph/tlsroute_test.go
  tests/Makefile
Labels: enhancement, release-notes

#2367 Run tests in internal/framework in parallel (2)
  internal/framework/controller/controller_suite_test.go
  internal/framework/controller/filter/filter_test.go
  internal/framework/controller/index/endpointslice_test.go
  internal/framework/controller/predicate/annotation_test.go
  internal/framework/controller/predicate/gatewayclass_test.go
  internal/framework/controller/predicate/service_test.go
  internal/framework/controller/register_test.go
  internal/framework/status/conditions_test.go
  internal/framework/status/status_suite_test.go
  internal/framework/status/updater_retry_test.go
Labels: tests

#2378 Add high level doc for data plane config
  .github/workflows/docs-build-push.yml
  site/content/how-to/control-plane-configuration.md
  site/content/how-to/data-plane-configuration.md
  site/content/how-to/upgrade-apps-without-downtime.md
Labels: documentation

#2387 Add NGF telemetry data for TLSRoute
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/data.avdl
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/ngfresourcecounts_attributes_generated.go
  site/content/overview/product-telemetry.md
  tests/suite/telemetry_test.go
Labels: documentation, chore

#2409 Update NGINX to 1.27.1
  README.md
  build/Dockerfile.nginx
Labels: dependencies

#2363 Add guide for TLS Route in site
  site/content/how-to/traffic-management/tls-passthrough.md
  site/content/overview/gateway-api-compatibility.md
  site/go.mod
  site/go.sum
Labels: documentation, chore, release-notes

#2412 Add guide for TLS Route in site (#2363)
  site/content/how-to/traffic-management/tls-passthrough.md
  site/content/overview/gateway-api-compatibility.md
  site/go.mod
  site/go.sum
Labels: documentation

#2420 Update troubleshooting doc for policy restriction
  site/content/how-to/monitoring/troubleshooting.md
Labels: documentation

#2422 Update troubleshooting doc for policy restriction (#2420)
  site/content/how-to/monitoring/troubleshooting.md
Labels: documentation, chore

#2427 Add longevity results for 1.4.0
  tests/README.md
  tests/results/longevity/1.4.0/oss-cpu.png
  tests/results/longevity/1.4.0/oss-memory.png
  tests/results/longevity/1.4.0/oss-ngf-memory.png
  tests/results/longevity/1.4.0/oss-reload-time.png
  tests/results/longevity/1.4.0/oss-reloads.png
  tests/results/longevity/1.4.0/oss-stub-status.png
  tests/results/longevity/1.4.0/oss.md
  tests/results/longevity/1.4.0/plus-cpu.png
  tests/results/longevity/1.4.0/plus-memory.png
  tests/results/longevity/1.4.0/plus-ngf-memory.png
  tests/results/longevity/1.4.0/plus-reloads.png
  tests/results/longevity/1.4.0/plus-status.png
  tests/results/longevity/1.4.0/plus.md
Labels: documentation, chore

#2428 (Cherry-pick) Add longevity results for 1.4.0 (#2427)
  tests/README.md
  tests/results/longevity/1.4.0/oss-cpu.png
  tests/results/longevity/1.4.0/oss-memory.png
  tests/results/longevity/1.4.0/oss-ngf-memory.png
  tests/results/longevity/1.4.0/oss-reload-time.png
  tests/results/longevity/1.4.0/oss-reloads.png
  tests/results/longevity/1.4.0/oss-stub-status.png
  tests/results/longevity/1.4.0/oss.md
  tests/results/longevity/1.4.0/plus-cpu.png
  tests/results/longevity/1.4.0/plus-memory.png
  tests/results/longevity/1.4.0/plus-ngf-memory.png
  tests/results/longevity/1.4.0/plus-reloads.png
  tests/results/longevity/1.4.0/plus-status.png
  tests/results/longevity/1.4.0/plus.md
Labels: documentation

#2432 Update release version and process doc
  .github/CHANGELOG_TEMPLATE.md
  .github/workflows/conformance.yml
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
  docs/developer/release-process.md
  site/content/how-to/monitoring/prometheus.md
  site/content/how-to/monitoring/troubleshooting.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/how-to/traffic-management/response-headers.md
  site/content/how-to/upgrade-apps-without-downtime.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/includes/installation/uninstall-gateway-api-resources.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  site/content/installation/ngf-images/building-the-images.md
  site/content/installation/ngf-images/pulling-ngf-image.md
  site/content/installation/running-on-kind.md
  site/content/overview/gateway-architecture.md
Labels: documentation, chore, helm-chart

#2433 Remove deprecated linter and fix issues
  .golangci.yml
  .pre-commit-config.yaml
  cmd/gateway/commands_test.go
  cmd/gateway/validation_test.go
  internal/framework/controller/filter/filter_test.go
  internal/framework/controller/index/endpointslice_test.go
  internal/framework/controller/predicate/annotation_test.go
  internal/framework/controller/predicate/service_test.go
  internal/framework/controller/register_test.go
  internal/framework/gatewayclass/validate_test.go
  internal/framework/helpers/helpers_test.go
  internal/framework/status/conditions_test.go
  internal/framework/status/updater_retry_test.go
  internal/mode/static/manager.go
  internal/mode/static/state/graph/gateway_test.go
  internal/mode/static/state/graph/reference_grant_test.go
  internal/mode/static/state/graph/tlsroute_test.go
  internal/mode/static/status/prepare_requests.go
  tests/suite/scale_test.go
  tests/suite/upgrade_test.go
Labels: chore

#2404 Add CRD versioning developer doc
  docs/developer/crd-versioning.md
Labels: documentation

#2440 Fix graceful recovery tests
  tests/framework/timeout.go
  tests/suite/graceful_recovery_test.go
Labels: bug

#2423 Update README.md
  README.md
Labels: documentation

#2448 Remove dependabot, add more tools to renovate
  .github/dependabot.yml
  .github/labeler.yml
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
  .github/workflows/helm.yml
  .github/workflows/labeler.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  Makefile
  go.mod
  go.sum
  tests/Dockerfile
  tests/framework/collector.go
  tools.go
Labels: dependencies, chore

#2456 Fix wrong package name
  .github/workflows/functional.yml
  .github/workflows/helm.yml
  Makefile
Labels: chore

#2455 Reduce log verbosity
  internal/framework/events/loop.go
  internal/mode/static/manager.go
  internal/mode/static/nginx/file/manager.go
  tests/framework/ngf.go
Labels: chore, tests

#2458 Fix dependency name for OTEL collector
  tests/framework/collector.go
Labels: chore, tests

#2439 Fix scale test errors caused by upstream server count
  tests/suite/scale_test.go
Labels: tests

#2464 Replace prettier mirror in pre-commit
  .pre-commit-config.yaml
Labels: chore

#2469 Fix failing image build workflow
  .github/workflows/update-docker-images.yml
Labels: chore

#2389 Add fail-fast flag to ginkgo tests
  Makefile
  tests/Makefile
Labels: tests

#2471 Update SnippetFilter validation rules in enhancement proposal
  docs/proposals/advanced-nginx-extensions.md
Labels: documentation, chore

#2478 Add login step to updater
  .github/workflows/update-docker-images.yml
Labels: chore

#2479 Cherry Pick URL fixes into Release 1.4
  site/content/how-to/monitoring/troubleshooting.md
  site/content/overview/resource-validation.md
Labels: documentation

#2484 Only use prettier for javascript
  .pre-commit-config.yaml
Labels: chore

#2175 Test/add runtime manager tests
  internal/mode/static/manager.go
  internal/mode/static/metrics/collectors/nginx.go
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/nginx/runtime/manager_test.go
  internal/mode/static/nginx/runtime/runtimefakes/fake_metrics_collector.go
  internal/mode/static/nginx/runtime/runtimefakes/fake_nginx_config_verifier.go
  internal/mode/static/nginx/runtime/runtimefakes/fake_nginx_plus_client.go
  internal/mode/static/nginx/runtime/runtimefakes/fake_process_handler.go
  internal/mode/static/nginx/runtime/runtimefakes/fake_verify_client.go
  internal/mode/static/nginx/runtime/verify.go
  internal/mode/static/nginx/runtime/verify_test.go
Labels: tests, community
