Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-02, with the labels that each got.

#1529 Make telemetry job a generic runnable
  internal/framework/runnables/cronjob.go
  internal/framework/runnables/cronjob_test.go
  internal/mode/static/manager.go
  internal/mode/static/telemetry/job.go
  internal/mode/static/telemetry/job_test.go
Labels: chore

#1517 Run unit tests with ginkgo
  .gitignore
  Makefile
  cmd/gateway/commands_test.go
  cmd/gateway/gateway_suite_test.go
  conformance/Makefile
Labels: tech-debt

#1525 Update stale workflow
  .github/workflows/stale.yml
  ISSUE_LIFECYCLE.md
Labels: documentation, chore

#1497 Add Telemetry collector structure with some collected resources
  cmd/gateway/commands.go
  deploy/helm-chart/templates/rbac.yaml
  deploy/manifests/nginx-gateway.yaml
  internal/framework/runnables/cronjob.go
  internal/framework/runnables/cronjob_test.go
  internal/mode/static/config/config.go
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/health.go
  internal/mode/static/health_test.go
  internal/mode/static/manager.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/graph/service_test.go
  internal/mode/static/state/statefakes/fake_change_processor.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/exporter.go
  internal/mode/static/telemetry/job_worker.go
  internal/mode/static/telemetry/job_worker_test.go
  internal/mode/static/telemetry/telemetryfakes/fake_configuration_getter.go
  internal/mode/static/telemetry/telemetryfakes/fake_data_collector.go
  internal/mode/static/telemetry/telemetryfakes/fake_graph_getter.go
Labels: enhancement, helm-chart

#1542 Use the right parameter for milestones
  .github/workflows/stale.yml
Labels: chore

#1536 Add plus to test suites
  .github/workflows/conformance.yml
  conformance/Makefile
  conformance/README.md
  tests/Makefile
  tests/README.md
  tests/framework/ngf.go
  tests/framework/results.go
  tests/scripts/remote-scripts/run-tests.sh
  tests/scripts/vars.env-example
  tests/suite/dataplane_perf_test.go
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: documentation, tests

#1558 Fix lint issues
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  internal/framework/controller/reconciler_test.go
  internal/framework/controller/register_test.go
  internal/framework/events/first_eventbatch_preparer_test.go
  internal/framework/events/loop_test.go
  internal/framework/runnables/cronjob_test.go
  internal/mode/static/config_updater_test.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/file/folders_test.go
  internal/mode/static/nginx/file/manager_test.go
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/nginx/runtime/verify.go
  internal/mode/static/state/changed_predicate_test.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/telemetry/collector_test.go
  tests/framework/load.go
  tests/suite/upgrade_test.go
Labels: chore

#1554 Add annotations for Artifact Hub
  .github/workflows/build.yml
Labels: chore

#1569 Update package for CVE-2023-52425
  .github/workflows/build.yml
  .github/workflows/ci.yml
  build/Dockerfile.nginx
Labels: chore

#1553 Bump Go to 1.22
  go.mod
Labels: dependencies

#1551 Add telemetry collection of deployment replica count
  cmd/gateway/commands.go
  deploy/helm-chart/templates/rbac.yaml
  deploy/manifests/nginx-gateway.yaml
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
Labels: enhancement, helm-chart

#1524 feat: Add docs to install Nginx Gateway Fabric with N+
  Makefile
  README.md
  deploy/helm-chart/templates/rbac.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-plus-gateway.yaml
  site/content/installation/installing-ngf/_index.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  site/content/installation/ngf-images/_index.md
  site/content/installation/ngf-images/building-the-images.md
  site/content/installation/ngf-images/jwt-token-docker-secret.md
  site/content/installation/ngf-images/pulling-ngf-image.md
  site/content/installation/running-on-kind.md
  site/go.mod
  site/go.sum
Labels: documentation, helm-chart

#1579 Update package for CVE-2024-25062 and remove fail
  .github/workflows/build.yml
  build/Dockerfile.nginx
Labels: chore

#1574 Add release-note section in PR template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/developer/pull-request.md
Labels: documentation

#1487 feat: Add BackendTLS Policy support
  .github/workflows/conformance.yml
  .gitleaksignore
  Makefile
  cmd/gateway/commands.go
  conformance/Makefile
  conformance/README.md
  conformance/scripts/install-gateway.sh
  conformance/scripts/uninstall-gateway.sh
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/templates/rbac.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway-experimental.yaml
  deploy/manifests/nginx-plus-gateway-experimental.yaml
  docs/developer/quickstart.md
  internal/framework/gatewayclass/validate.go
  internal/framework/status/backend_tls.go
  internal/framework/status/backend_tls_test.go
  internal/framework/status/setters.go
  internal/framework/status/setters_test.go
  internal/framework/status/statuses.go
  internal/framework/status/updater.go
  internal/framework/status/updater_test.go
  internal/mode/static/build_statuses.go
  internal/mode/static/build_statuses_test.go
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  internal/mode/static/manager_test.go
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/backend_tls_policy.go
  internal/mode/static/state/graph/backend_tls_policy_test.go
  internal/mode/static/state/graph/configmaps.go
  internal/mode/static/state/graph/configmaps_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/httproute.go
  site/content/how-to/traffic-management/securing-backend-traffic.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/includes/installation/uninstall-gateway-api-resources.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  site/content/overview/gateway-api-compatibility.md
  site/content/reference/cli-help.md
Labels: documentation, enhancement, helm-chart

#1575 Remove "build images" link from README
  README.md
Labels: documentation, chore

#1587 Add more badges
  README.md
Labels: documentation, chore

#1592 Update NGINX version in README
  README.md
Labels: documentation, chore

#1565 Collects ClusterId for Telemetry Object Collector
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
Labels: enhancement

#1590 Remove webhook validation code
  design/resource-validation.md
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/gateway_listener.go
  internal/mode/static/state/graph/gateway_listener_test.go
  internal/mode/static/state/graph/httproute.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/validation.go
  internal/mode/static/state/store.go
  site/content/overview/resource-validation.md
Labels: bug, documentation

#1604 Add installed architecture to telemetry data
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
Labels: enhancement

#1605 Add flag to opt out of product telemetry
  cmd/gateway/commands.go
  deploy/helm-chart/README.md
  deploy/helm-chart/templates/deployment.yaml
  deploy/helm-chart/templates/rbac.yaml
  deploy/helm-chart/values.yaml
  deploy/manifests/nginx-gateway-experimental.yaml
  deploy/manifests/nginx-gateway.yaml
  deploy/manifests/nginx-plus-gateway-experimental.yaml
  deploy/manifests/nginx-plus-gateway.yaml
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  site/content/reference/cli-help.md
Labels: documentation, chore, helm-chart

#1606 Fix typo in Gateway API compatibility doc
  site/content/overview/gateway-api-compatibility.md
Labels: documentation, chore

#1607 Add NGINX bot
  .github/workflows/nginx-bot.yml
  docs/developer/pull-request.md
Labels: documentation, chore

#1622 Move version in event handler
  internal/mode/static/handler.go
Labels: bug

#1578 Collect Deployment Flag Options
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  go.mod
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
Labels: enhancement, dependencies

#1618 Move NGINX Bot to GitHub App
  .github/nginx-bot.yml
  .github/workflows/nginx-bot.yml
  .yamllint.yaml
Labels: chore

#1626 Add Codecov
  .codecov.yml
  .github/workflows/ci.yml
  Makefile
  README.md
Labels: documentation, chore

#1624 Fix experimental feature flag name in docs and conformance makefile
  conformance/Makefile
  site/content/installation/installing-ngf/helm.md
Labels: documentation

#1567 Add NGINX extensions enhancement proposal
  docs/images/hierarchy.png
  docs/images/nginx-functionality-groups.png
  docs/proposals/nginx-extensions.md
Labels: documentation

#1627 Bump Node to v20 and add .nvmrc
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .nvmrc
  Makefile
  internal/mode/static/nginx/modules/README.md
  internal/mode/static/nginx/modules/package-lock.json
  internal/mode/static/nginx/modules/package.json
  internal/mode/static/nginx/modules/test/httpmatches.test.js
  internal/mode/static/nginx/modules/test/vitest.config.ts
Labels: documentation, chore
