Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-09, with the labels that each got.

#2493 Run tests in internal/mode/static/nginx/config in parallel (1)
  internal/mode/static/nginx/config/policies/clientsettings/generator_test.go
  internal/mode/static/nginx/config/policies/clientsettings/validator_test.go
  internal/mode/static/nginx/config/policies/observability/generator_test.go
  internal/mode/static/nginx/config/policies/observability/validator_test.go
  internal/mode/static/nginx/config/policies/policies_suite_test.go
  internal/mode/static/nginx/config/validation/common_test.go
  internal/mode/static/nginx/config/validation/framework_test.go
  internal/mode/static/nginx/config/validation/generic_test.go
  internal/mode/static/nginx/config/validation/http_filters_test.go
  internal/mode/static/nginx/config/validation/http_njs_match_test.go
Labels: tests

#2505 Clean up NFR test result formatting
  .github/workflows/nfr.yml
  tests/suite/reconfig_test.go
  tests/suite/scale_test.go
Labels: tests

#2507 Update documentation Makefile and README
  site/Makefile
  site/README.md
Labels: documentation

#2489 Enhancement Proposal for UpstreamSettingsPolicy
  docs/proposals/upstream-settings.md
Labels: documentation

#2486 Add NginxGateway functional test
  tests/framework/ngf.go
  tests/suite/manifests/nginxgateway/nginx-gateway.yaml
  tests/suite/nginxgateway_test.go
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: tests

#2510 Use CLA GitHub Action
  .github/workflows/f5-cla.yml
  CONTRIBUTING.md
  F5ContributorLicenseAgreement.pdf
Labels: documentation, chore

#2521 Don't cancel in progress runs of CLA bot
  .github/workflows/f5-cla.yml
Labels: chore

#2284 Adds configuration to retain client IP information
  apis/v1alpha1/nginxproxy_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  charts/nginx-gateway-fabric/values.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/shared/config.go
  internal/mode/static/nginx/config/stream/config.go
  internal/mode/static/nginx/config/stream_servers.go
  internal/mode/static/nginx/config/stream_servers_template.go
  internal/mode/static/nginx/config/stream_servers_test.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/nginxproxy.go
  internal/mode/static/state/graph/nginxproxy_test.go
  site/content/how-to/monitoring/troubleshooting.md
  site/content/reference/api.md
Labels: documentation, enhancement, helm-chart, release-notes

#2519 Watch SnippetsFilters when feature is enabled and add to graph
  apis/v1alpha1/snippetsfilter_types.go
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/clusterrole.yaml
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/values.yaml
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  config/crd/bases/gateway.nginx.org_snippetsfilters.yaml
  deploy/snippets-filters-nginx-plus/deploy.yaml
  deploy/snippets-filters/deploy.yaml
  examples/helm/README.md
  examples/helm/snippets-filters-nginx-plus/values.yaml
  examples/helm/snippets-filters/values.yaml
  examples/snippets-filter/README.md
  examples/snippets-filter/snippets-filter.yaml
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  internal/mode/static/manager_test.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/snippets_filter.go
  internal/mode/static/state/graph/snippets_filter_test.go
  site/content/reference/api.md
  site/content/reference/cli-help.md
Labels: documentation, enhancement, helm-chart

#2515 Add UpstreamSettingsPolicy CRD
  apis/v1alpha1/register.go
  apis/v1alpha1/upstreamsettingspolicy_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.nginx.org_upstreamsettingspolicies.yaml
  docs/proposals/upstream-settings.md
  examples/upstream-settings-policy/README.md
  examples/upstream-settings-policy/upstream-settings-policy.yaml
  site/content/reference/api.md
Labels: documentation, enhancement

#2525 Change validation in Duration type in CRDs and NGF
  apis/v1alpha1/shared_types.go
  config/crd/bases/gateway.nginx.org_clientsettingspolicies.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/mode/static/nginx/config/policies/clientsettings/validator_test.go
  internal/mode/static/nginx/config/validation/generic.go
  internal/mode/static/nginx/config/validation/generic_test.go
  site/content/reference/api.md
Labels: documentation, chore, release-notes

#2534 Run tests in internal/mode/static/state in parallel (1)
  internal/mode/static/state/changed_predicate_test.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/convert_test.go
  internal/mode/static/state/dataplane/sort_test.go
  internal/mode/static/state/graph/gateway_listener_test.go
  internal/mode/static/state/graph/gatewayclass_test.go
  internal/mode/static/state/graph/grpcroute_test.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/namespace_test.go
  internal/mode/static/state/graph/nginxproxy_test.go
  internal/mode/static/state/graph/policies_test.go
  internal/mode/static/state/graph/policy_ancestor_test.go
  internal/mode/static/state/graph/secret_test.go
  internal/mode/static/state/graph/service_test.go
  internal/mode/static/state/graph/validation_test.go
  internal/mode/static/state/resolver/resolver_test.go
  internal/mode/static/state/resolver/service_resolver_suite_test.go
  internal/mode/static/state/state_suite_test.go
  internal/mode/static/state/store_test.go
Labels: tests

#2537 Run tests in parallel
  internal/mode/provisioner/provisioner_suite_test.go
  internal/mode/static/config_updater_test.go
  internal/mode/static/health_test.go
  internal/mode/static/log_level_setters_test.go
  internal/mode/static/manager_test.go
  internal/mode/static/nginx/file/file_suite_test.go
  internal/mode/static/nginx/file/folders_test.go
  internal/mode/static/nginx/runtime/manager_test.go
  internal/mode/static/nginx/runtime/runtime_suite_test.go
  internal/mode/static/nginx/runtime/verify_test.go
  internal/mode/static/sort/sort_test.go
  internal/mode/static/static_suite_test.go
  internal/mode/static/status/prepare_requests_test.go
  internal/mode/static/status/status_setters_test.go
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/exporter_test.go
  internal/mode/static/telemetry/job_worker_test.go
  internal/mode/static/telemetry/platform_test.go
  internal/mode/static/telemetry/telemetry_suite_test.go
  internal/mode/static/usage/job_worker_test.go
  internal/mode/static/usage/reporter_test.go
  internal/mode/static/usage/secret_test.go
Labels: tests

#2543 Remove extra endifs in docs Makefile
  site/Makefile
Labels: documentation

#2536 Add status to snippetsFilter
  internal/mode/static/handler.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/status/prepare_requests.go
  internal/mode/static/status/prepare_requests_test.go
  internal/mode/static/status/status_setters.go
  internal/mode/static/status/status_setters_test.go
Labels: enhancement

#2545 Enable more linters
  .golangci.yml
  internal/mode/provisioner/manager.go
  internal/mode/static/handler.go
  internal/mode/static/manager.go
  internal/mode/static/nginx/config/validation/common_test.go
  internal/mode/static/nginx/file/folders.go
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_tls_policy.go
  internal/mode/static/state/graph/backend_tls_policy_test.go
  internal/mode/static/state/graph/gateway_listener.go
  internal/mode/static/state/graph/secret.go
  internal/mode/static/state/resolver/resolver.go
  internal/mode/static/status/prepare_requests.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/usage/job_worker_test.go
  tests/framework/ngf.go
  tests/suite/system_suite_test.go
  tests/suite/tracing_test.go
Labels: chore, tests

#2575 [cherry-pick] Update nginxinc/docs-actions action to v1.0.5 (#2565)
  .github/workflows/docs-build-push.yml
Labels: community

#2572 Enable more parallel tests
  internal/mode/static/config_updater_test.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/backend_tls_policy_test.go
  internal/mode/static/state/graph/configmaps_test.go
  internal/mode/static/state/graph/gateway_test.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/reference_grant_test.go
  internal/mode/static/state/graph/route_common_test.go
  tests/suite/system_suite_test.go
Labels: chore, tests

#2574 Fix import shadowing and unchecked type assertions in test
  .golangci.yml
  internal/framework/controller/reconciler_test.go
  internal/framework/events/first_eventbatch_preparer_test.go
  internal/framework/helpers/helpers.go
  internal/framework/status/leader_aware_group_updater_test.go
  internal/framework/status/updater.go
  internal/framework/status/updater_test.go
  internal/mode/static/handler.go
  internal/mode/static/manager.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/graph/gateway_listener.go
  internal/mode/static/state/graph/policies.go
  internal/mode/static/state/resolver/resolver.go
  internal/mode/static/state/store.go
  internal/mode/static/telemetry/collector_test.go
  tests/framework/generate_manifests.go
  tests/framework/prometheus.go
  tests/framework/resourcemanager.go
Labels: chore, tests

#2546 Add description for enabling experimental features
  site/content/how-to/traffic-management/securing-backend-traffic.md
  site/content/how-to/traffic-management/tls-passthrough.md
  site/content/includes/installation/install-gateway-api-experimental-features.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/overview/gateway-api-compatibility.md
Labels: documentation

#2570 add controller to snippetsFilter status
  apis/v1alpha1/snippetsfilter_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.nginx.org_snippetsfilters.yaml
  internal/mode/static/handler.go
  internal/mode/static/status/prepare_requests.go
  internal/mode/static/status/prepare_requests_test.go
  internal/mode/static/status/status_setters.go
  internal/mode/static/status/status_setters_test.go
  site/content/reference/api.md
Labels: documentation, enhancement

#2585 docs-fix-broken-url
  site/content/includes/installation/expose-nginx-gateway-fabric.md
Labels: documentation, community

#2592 (Cherry pick) docs-fix-broken-url (#2585)
  site/content/includes/installation/expose-nginx-gateway-fabric.md
Labels: documentation

#2597 Enable auto-deployment of docs in release 1.4 branch
  .github/workflows/docs-build-push.yml
Labels: chore

#2588 Use correct indentation in lifecyce examples
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/README.md.gotmpl
Labels: bug, documentation, helm-chart, community

#2580 Fix unchecked type assertions
  .golangci.yml
  internal/framework/status/updater.go
  internal/mode/static/manager.go
  internal/mode/static/status/status_setters.go
  tests/framework/request.go
Labels: chore, tests

#2599 Reorder release notes labels
  .github/release.yml
Labels: chore

#2522 Add crossplane framework for testing
  .github/workflows/functional.yml
  internal/mode/static/nginx/config/generator.go
  tests/Makefile
  tests/README.md
  tests/framework/crossplane.go
  tests/framework/crossplane/Dockerfile
  tests/framework/crossplane/cmd/crossplane/main.go
  tests/framework/crossplane/go.mod
  tests/framework/crossplane/go.sum
  tests/framework/resourcemanager.go
  tests/scripts/remote-scripts/run-tests.sh
  tests/scripts/run-tests-gcp-vm.sh
  tests/suite/client_settings_test.go
  tests/suite/system_suite_test.go
Labels: documentation

#2602 Fix unit tests to avoid data race in pipelines
  docs/developer/testing.md
  internal/mode/static/state/graph/policies_test.go
  internal/mode/static/state/graph/reference_grant_test.go
Labels: bug, documentation

#2613 Use go test as unit test runner
  .codecov.yml
  .github/workflows/ci.yml
  Makefile
  cmd/gateway/commands_test.go
  tests/Makefile
Labels: tests

#2616 Docs: Fix broken redirect in usage-reporting.md
  site/content/installation/usage-reporting.md
Labels: documentation

#2618 Use NGF logger in client-go library
  cmd/gateway/commands.go
  docs/developer/logging-guidelines.md
  go.mod
Labels: documentation, dependencies, chore

#2622 Docs: Fix invalid URL
  site/content/how-to/monitoring/troubleshooting.md
Labels: documentation

#2492 Add Helm schema
  .pre-commit-config.yaml
  .yamllint.yaml
  Makefile
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
  tests/Makefile
Labels: documentation, tests, helm-chart, release-notes

#2619 Support IP and Hostname trusted addresses
  apis/v1alpha1/nginxproxy_types.go
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/graph/nginxproxy.go
  internal/mode/static/state/graph/nginxproxy_test.go
  site/content/reference/api.md
Labels: documentation, enhancement, helm-chart
