Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-11, with the labels that each got.

#2730 Update backend group name with a prefix
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/split_clients_test.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  site/content/how-to/monitoring/troubleshooting.md
Labels: bug, documentation

#2749 Add more queries to CodeQL
  .github/workflows/codeql-analysis.yml
Labels: chore

#2766 Add loadbalancerIP as a helm parameter
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/service.yaml
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
Labels: documentation, helm-chart

#2721 Add SnippetsFilter guide
  examples/snippets-filter/README.md
  examples/snippets-filter/app.yaml
  examples/snippets-filter/example.yaml
  examples/snippets-filter/gateway.yaml
  examples/snippets-filter/httproutes.yaml
  examples/snippets-filter/no-delay-rate-limiting-sf.yaml
  examples/snippets-filter/rate-limiting-sf.yaml
  site/content/how-to/traffic-management/snippets.md
Labels: documentation

#2773 Add loadBalancerSourceRanges to helm parameters
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/service.yaml
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
Labels: documentation, enhancement, helm-chart, release-notes

#2784 Skip plus tests on a fork
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
  .github/workflows/helm.yml
Labels: chore

#2787 Update release version in docs
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
  site/content/get-started.md
  site/content/how-to/monitoring/prometheus.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/how-to/traffic-management/request-response-headers.md
  site/content/how-to/traffic-management/snippets.md
  site/content/how-to/upgrade-apps-without-downtime.md
  site/content/includes/installation/install-gateway-api-experimental-features.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/includes/installation/uninstall-gateway-api-resources.md
  site/content/installation/building-the-images.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  site/content/installation/nginx-plus-jwt.md
  site/content/overview/gateway-architecture.md
  tests/Makefile
Labels: documentation, chore, tests, helm-chart

#2800 Deploy docs for release 1.5.0
  .github/workflows/docs-build-push.yml
Labels: documentation

#2803 Docs: remove () typo from troubleshooting doc
  site/content/how-to/monitoring/troubleshooting.md
Labels: documentation

#2808 Clear up installation language
  site/content/installation/installing-ngf/helm.md
  site/content/installation/nginx-plus-jwt.md
Labels: documentation

#2789 Docs: Update support referencing support package tool
  site/content/support.md
Labels: documentation

#2753 Update ObservabilityPolicy API to have minimum one target ref
  apis/v1alpha1/observabilitypolicy_types.go
  config/crd/bases/gateway.nginx.org_observabilitypolicies.yaml
  deploy/crds.yaml
Labels: bug, release-notes

#2815 Cherry pick recent documentation changes
  site/content/how-to/monitoring/troubleshooting.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/nginx-plus-jwt.md
  site/content/support.md
Labels: documentation

#2820 feat: Update documentation action, bump version for local testing
  .github/workflows/docs-build-push.yml
  site/go.mod
  site/go.sum
Labels: documentation

#2822 Cherry-pick CRD fix to release-1.5 branch
  config/crd/kustomization.yaml
  deploy/crds.yaml
Labels: chore

#2823 Remove the email support section from the NGF README file
  README.md
Labels: documentation

#2729 Update data/control plane split design
  design/control-data-plane-separation/design.md
  docs/proposals/control-data-plane-split/README.md
  docs/proposals/control-data-plane-split/connect.png
  docs/proposals/control-data-plane-split/deployment-architecture.png
  docs/proposals/control-data-plane-split/graph-conns.png
Labels: documentation

#2834 (cherry-pick) Update documentation action, bump version for local testing
  .github/workflows/docs-build-push.yml
  site/go.mod
  site/go.sum
Labels: documentation

#2836 Update split design with some clearer details
  docs/proposals/control-data-plane-split/README.md
Labels: documentation
