Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-01, with the labels that each got.

#1202 Add ephemeral debugging guide
  Makefile
  conformance/Makefile
  debug/Dockerfile
  docs/developer/debugging.md
  docs/developer/quickstart.md
Labels: documentation, chore

#1438 Test automation: zero-downtime upgrades
  .gitignore
  .markdownlint-cli2.yaml
  .pre-commit-config.yaml
  tests/Makefile
  tests/README.md
  tests/framework/common.go
  tests/framework/load.go
  tests/framework/ngf.go
  tests/framework/portforward.go
  tests/framework/resourcemanager.go
  tests/framework/results.go
  tests/results/ngf-upgrade/1.0.0-special/1.0.0-special.md
  tests/results/ngf-upgrade/1.0.0-special/http.csv
  tests/results/ngf-upgrade/1.0.0-special/http.png
  tests/results/ngf-upgrade/1.0.0-special/https.csv
  tests/results/ngf-upgrade/1.0.0-special/https.png
  tests/results/ngf-upgrade/1.0.0/1.0.0.md
  tests/results/ngf-upgrade/1.0.0/http.csv
  tests/results/ngf-upgrade/1.0.0/http.png
  tests/results/ngf-upgrade/1.0.0/https.csv
  tests/results/ngf-upgrade/1.0.0/https.png
  tests/results/ngf-upgrade/1.1.0/1.1.0.md
  tests/results/ngf-upgrade/1.1.0/http.csv
  tests/results/ngf-upgrade/1.1.0/http.png
  tests/results/ngf-upgrade/1.1.0/https.csv
  tests/results/ngf-upgrade/1.1.0/https.png
  tests/scripts/cleanup-router.sh
  tests/scripts/cleanup-vm.sh
  tests/scripts/create-and-setup-gcp-vm.sh
  tests/scripts/create-gke-router.sh
  tests/scripts/remote-scripts/install-deps.sh
  tests/scripts/requests-plot.gp
  tests/scripts/run-tests-gcp-vm.sh
  tests/scripts/vars.env-example
  tests/suite/dataplane_perf_test.go
  tests/suite/manifests/ngf-upgrade/cafe-routes.yaml
  tests/suite/manifests/ngf-upgrade/cafe-secret.yaml
  tests/suite/manifests/ngf-upgrade/cafe.yaml
  tests/suite/manifests/ngf-upgrade/gateway-updated.yaml
  tests/suite/manifests/ngf-upgrade/gateway.yaml
  tests/suite/manifests/ngf-upgrade/values.yaml
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
  tests/zero-downtime-upgrades/requests-plot.gp
  tests/zero-downtime-upgrades/zero-downtime-upgrades.md
Labels: documentation, tests

#1452 Add Helm Chart configuration table reference to installation guide
  docs/developer/release-process.md
  site/content/installation/installing-ngf/helm.md
Labels: documentation

#1388 doc: Support document
  site/content/support.md
Labels: documentation

#1431 Update guidance and tooling for documentation
  CONTRIBUTING.md
  docs/developer/documentation.md
  site/Makefile
  site/README.md
Labels: documentation

#1432 EndpointSlice resources tracked by Graph
  internal/mode/static/manager.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/changed_predicate.go
  internal/mode/static/state/changed_predicate_test.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/service.go
  internal/mode/static/state/graph/service_test.go
  internal/mode/static/state/relationship/capturer.go
  internal/mode/static/state/relationship/capturer_suite_test.go
  internal/mode/static/state/relationship/capturer_test.go
  internal/mode/static/state/relationship/relationshipfakes/fake_capturer.go
  internal/mode/static/state/relationship/relationships_test.go
  internal/mode/static/state/resolver/resolver.go
  internal/mode/static/state/resolver/resolver_test.go
  internal/mode/static/state/resolver/resolverfakes/fake_service_resolver.go
  internal/mode/static/state/resolver/service_resolver_test.go
  internal/mode/static/state/store.go
Labels: tech-debt

#1469 NGINX Plus: dynamic upstream reloads support
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/manager.go
  internal/mode/static/metrics/collectors/nginx.go
  internal/mode/static/nginx/conf/nginx-plus.conf
  internal/mode/static/nginx/config/convert.go
  internal/mode/static/nginx/config/convert_test.go
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/upstreams.go
  internal/mode/static/nginx/config/upstreams_template.go
  internal/mode/static/nginx/config/upstreams_test.go
  internal/mode/static/nginx/runtime/clients.go
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/nginx/runtime/manager_test.go
  internal/mode/static/nginx/runtime/runtime_suite_test.go
  internal/mode/static/nginx/runtime/runtimefakes/fake_manager.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/statefakes/fake_change_processor.go
  internal/mode/static/state/store.go
  internal/mode/static/state/store_test.go
  site/content/overview/gateway-api-compatibility.md
  site/content/overview/gateway-architecture.md
  site/content/overview/nginx-plus.md
  site/content/overview/resource-validation.md
Labels: documentation, enhancement

#1499 Fix markdownlint in `site`
  .pre-commit-config.yaml
  site/.markdownlint.json
  site/Makefile
  site/README.md
  site/content/how-to/traffic-management/integrating-cert-manager.md
  site/content/reference/technical-specifications.md
  site/content/releases.md
Labels: documentation, chore

#1501 Update N+ to R31
  README.md
  build/Dockerfile.nginxplus
  internal/mode/static/nginx/conf/nginx-plus.conf
Labels: documentation, chore

#1503 Update README.md
  README.md
Labels: documentation

#1516 Reduce contextual use of "NGF" three letter acronym
  site/content/overview/gateway-api-compatibility.md
  site/content/overview/gateway-architecture.md
Labels: documentation

#1518 Fix comment grammar in loop.go
  internal/framework/events/loop.go
Labels: chore

#1477 Build NGINX Plus images
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/update-docker-images.yml
  Makefile
  build/Dockerfile
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  conformance/tests/Dockerfile
  debug/Dockerfile
  docs/developer/branching-and-workflow.md
  docs/developer/quickstart.md
  docs/developer/release-process.md
  site/content/installation/building-the-images.md
Labels: documentation, chore
