Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-05, with the labels that each got.

#1886 Use kustomize to generate a single CRDs file
  .goreleaser.yml
  .yamllint.yaml
  Makefile
  charts/nginx-gateway-fabric/README.md
  config/crd/kustomization.yaml
  conformance/Makefile
  deploy/crds.yaml
  deploy/manifests/crds
  docs/developer/quickstart.md
  scripts/combine-crds.sh
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
Labels: documentation, chore, helm-chart

#1914 Fix conformance tests using cached binary
  .github/workflows/conformance.yml
Labels: chore

#1919 Use new directories directive in dependabot
  .github/dependabot.yml
Labels: chore

#1916 Bump Dockerfile version to 1.7
  build/Dockerfile
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  conformance/tests/Dockerfile
  debug/Dockerfile
Labels: chore

#1915 Bump js dependencies
  internal/mode/static/nginx/modules/package-lock.json
  internal/mode/static/nginx/modules/package.json
Labels: dependencies

#1922 Fix httproute counts
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
Labels: bug

#1928 Update docs process in release-guide
  docs/developer/release-process.md
Labels: documentation, chore

#1832 Automate Graceful Recovery NFR
  tests/Makefile
  tests/framework/request.go
  tests/framework/resourcemanager.go
  tests/framework/timeout.go
  tests/suite/graceful_recovery_test.go
  tests/suite/manifests/graceful-recovery/cafe-routes.yaml
  tests/suite/manifests/graceful-recovery/cafe-secret.yaml
  tests/suite/manifests/graceful-recovery/cafe.yaml
  tests/suite/manifests/graceful-recovery/gateway.yaml
  tests/suite/manifests/graceful-recovery/node-debugger-job.yaml
  tests/suite/system_suite_test.go
Labels: tests

#1931 Remove zone size for invalid backend ref
  internal/mode/static/nginx/config/upstreams.go
  internal/mode/static/nginx/config/upstreams_template.go
  internal/mode/static/nginx/config/upstreams_test.go
Labels: bug, release-notes

#1934 Add directive for SSL Server block
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
Labels: bug, release-notes

#1944 Fixing the 'pre-commit install' command in the quick start guide of the NGF
  docs/developer/quickstart.md
Labels: documentation

#1953 Fix rbac ServiceAccount imagePullSecrets template
  charts/nginx-gateway-fabric/templates/rbac.yaml
Labels: bug, helm-chart, release-notes

#1909 Add request header filter support for gRPC
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/state/graph/grpcroute.go
  internal/mode/static/state/graph/grpcroute_test.go
  internal/mode/static/state/graph/httproute.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/route_common_test.go
  site/content/overview/gateway-api-compatibility.md
Labels: documentation, enhancement, release-notes

#1925 Add field to NginxProxy to allow disabling HTTP2
  apis/v1alpha1/nginxproxy_types.go
  charts/nginx-gateway-fabric/values.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/mode/static/nginx/conf/nginx-plus.conf
  internal/mode/static/nginx/conf/nginx.conf
  internal/mode/static/nginx/config/base_http_config.go
  internal/mode/static/nginx/config/base_http_config_template.go
  internal/mode/static/nginx/config/base_http_config_test.go
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/grpcroute.go
  internal/mode/static/state/graph/grpcroute_test.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/route_common.go
Labels: enhancement, helm-chart, release-notes

#1983 Support response header filter for GRPCRoute
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/state/graph/grpcroute.go
  internal/mode/static/state/graph/grpcroute_test.go
  site/content/overview/gateway-api-compatibility.md
Labels: documentation, enhancement, release-notes

#1954 Collect backendTLSPolicy and GRPCRoute Count
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/data.avdl
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/ngfresourcecounts_attributes_generated.go
  site/content/overview/product-telemetry.md
  tests/suite/telemetry_test.go
Labels: documentation, enhancement, release-notes

#1990 Speed up generation
  internal/framework/controller/fakes.go
  internal/framework/controller/getter.go
  internal/framework/events/first_eventbatch_preparer.go
  internal/framework/events/handler.go
  internal/framework/status/k8s_updater.go
  internal/framework/status/leader_aware_group_updater.go
  internal/mode/static/handler.go
  internal/mode/static/log_level_setters.go
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/file/folders.go
  internal/mode/static/nginx/file/manager.go
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/resolver/resolver.go
  internal/mode/static/state/validation/validator.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/exporter.go
  internal/mode/static/telemetry/job_worker.go
  internal/mode/static/usage/reporter.go
Labels: chore

#1969 Move conformance tests to tests directory
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
  .github/workflows/release-pr.yml
  .gitignore
  Makefile
  config/tests/static-deployment.yaml
  conformance/Makefile
  conformance/README.md
  conformance/tests/Dockerfile
  docs/developer/quickstart.md
  docs/developer/release-process.md
  docs/developer/testing.md
  embedded.go
  go.mod
  go.sum
  tests/Dockerfile
  tests/Makefile
  tests/README.md
  tests/conformance/Dockerfile
  tests/conformance/conformance-rbac.yaml
  tests/conformance/conformance_test.go
  tests/conformance/provisioner/README.md
  tests/conformance/provisioner/provisioner.yaml
  tests/go.mod
  tests/go.sum
  tests/scripts/check-pod-exit-code.sh
  tests/scripts/install-gateway.sh
  tests/scripts/uninstall-gateway.sh
Labels: documentation, dependencies, chore

#2003 Add missing upstream remote command to quickstart guide
  docs/developer/quickstart.md
Labels: documentation, chore

#1994 Get correct leader election holder ID in upgrade test
  tests/suite/upgrade_test.go
Labels: tests

#2016 Bump kindest/node from v1.29.2 to v1.30.0 in /tests
  tests/Dockerfile
Labels: dependencies

#2018 Enable yamllint for Helm Chart and GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/nfr.yml
  .yamllint.yaml
  charts/nginx-gateway-fabric/values.yaml
Labels: chore, helm-chart

#2024 Add NFR scale test to GitHub actions pipeline
  .github/workflows/nfr.yml
Labels: tests

#2025 Add minimum k8s version in Helm
  charts/nginx-gateway-fabric/Chart.yaml
Labels: chore, helm-chart

#1976 Allow NGF to run on Openshift
  Makefile
  charts/nginx-gateway-fabric/templates/_helpers.tpl
  charts/nginx-gateway-fabric/templates/rbac.yaml
  charts/nginx-gateway-fabric/templates/scc.yaml
  charts/nginx-gateway-fabric/values.yaml
  deploy/manifests/scc.yaml
  site/content/installation/installing-ngf/manifests.md
Labels: bug, documentation, helm-chart, release-notes

#2011 Add Gateway API CRDs to the repo with kustomize
  .github/workflows/ci.yml
  Makefile
  charts/nginx-gateway-fabric/README.md
  config/crd/gateway-api/experimental/kustomization.yaml
  config/crd/gateway-api/standard/kustomization.yaml
  config/crd/kustomization.yaml
  docs/developer/quickstart.md
  docs/developer/release-process.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/includes/installation/uninstall-gateway-api-resources.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  tests/Makefile
  tests/reconfig/setup.md
  tests/scripts/install-gateway.sh
  tests/scripts/uninstall-gateway.sh
Labels: documentation, chore, helm-chart

#2013 Add functional tests for ClientSettingsPolicies
  .github/workflows/functional.yml
  tests/README.md
  tests/conformance/Dockerfile
  tests/framework/ngf.go
  tests/framework/request.go
  tests/framework/resourcemanager.go
  tests/framework/timeout.go
  tests/go.mod
  tests/go.sum
  tests/suite/client_settings_test.go
  tests/suite/manifests/clientsettings/cafe-routes.yaml
  tests/suite/manifests/clientsettings/cafe.yaml
  tests/suite/manifests/clientsettings/gateway.yaml
  tests/suite/manifests/clientsettings/grpc-backend.yaml
  tests/suite/manifests/clientsettings/grpc-route.yaml
  tests/suite/manifests/clientsettings/ignored-gateway.yaml
  tests/suite/manifests/clientsettings/invalid-csp.yaml
  tests/suite/manifests/clientsettings/merging-csps.yaml
  tests/suite/manifests/clientsettings/valid-csps.yaml
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: documentation, tests

#2057 Bump NGINX Plus to R32
  README.md
  build/Dockerfile.nginxplus
Labels: documentation, dependencies, release-notes

#2047 Update secrets on resource version change only
  internal/mode/static/manager.go
Labels: bug

#2027 Use chart-testing to lint the Helm Chart
  .ct.yaml
  .github/workflows/lint.yml
  .yamllint.yaml
  Makefile
  charts/nginx-gateway-fabric/Chart.yaml
Labels: chore, helm-chart

#2026 Add tracing how-to guide
  .yamllint.yaml
  site/content/how-to/maintenance/_index.md
  site/content/how-to/monitoring/_index.md
  site/content/how-to/monitoring/dashboard.md
  site/content/how-to/monitoring/prometheus.md
  site/content/how-to/monitoring/tracing.md
  site/content/how-to/monitoring/troubleshooting.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/static/img/jaeger-trace-attributes.png
  site/static/img/jaeger-trace-overview.png
  site/static/jaeger.yaml
  site/static/otel-collector.yaml
Labels: documentation

#2067 Add PRs with release-notes labels to the CHANGELOG
  .github/release-notes.yml
  .github/workflows/release-pr.yml
Labels: chore

#2068 Increase timeout for tracing test
  tests/suite/tracing_test.go
Labels: tests

#2060 Test Chart installation for Plus and remote images
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
  .github/workflows/helm.yml
  Makefile
  tests/Makefile
Labels: chore
