Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-06, with the labels that each got.

#1993 Add custom annotations into GatewayClass and NginxGateway manifests
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/gatewayclass.yaml
  charts/nginx-gateway-fabric/templates/nginxgateway.yaml
  charts/nginx-gateway-fabric/values.yaml
Labels: documentation, helm-chart, community

#2072 Extend troubleshooting doc
  site/content/how-to/monitoring/troubleshooting.md
Labels: documentation

#2082 Update release doc
  docs/developer/release-process.md
Labels: documentation

#2045 Run graceful recovery tests in pipeline
  tests/framework/resourcemanager.go
  tests/suite/graceful_recovery_test.go
  tests/suite/system_suite_test.go
Labels: enhancement

#2100 Fix GRPCRoute check in tests
  tests/framework/resourcemanager.go
Labels: tests

#2101 Add retries to tracing tests
  tests/suite/tracing_test.go
Labels: tests

#2096 Add 1.3.0 zero-downtime-scaling test results
  tests/zero-downtime-scaling/results/1.3.0/1.3.0.md
  tests/zero-downtime-scaling/results/1.3.0/10-node/abrupt-down-http.png
  tests/zero-downtime-scaling/results/1.3.0/10-node/abrupt-down-https.png
  tests/zero-downtime-scaling/results/1.3.0/10-node/abrupt-up-http.png
  tests/zero-downtime-scaling/results/1.3.0/10-node/abrupt-up-https.png
  tests/zero-downtime-scaling/results/1.3.0/10-node/gradual-down-http.png
  tests/zero-downtime-scaling/results/1.3.0/10-node/gradual-down-https.png
  tests/zero-downtime-scaling/results/1.3.0/10-node/gradual-up-http.png
  tests/zero-downtime-scaling/results/1.3.0/10-node/gradual-up-https.png
  tests/zero-downtime-scaling/results/1.3.0/25-node/abrupt-down-http.png
  tests/zero-downtime-scaling/results/1.3.0/25-node/abrupt-down-https.png
  tests/zero-downtime-scaling/results/1.3.0/25-node/abrupt-up-http.png
  tests/zero-downtime-scaling/results/1.3.0/25-node/abrupt-up-https.png
  tests/zero-downtime-scaling/results/1.3.0/25-node/gradual-down-http.png
  tests/zero-downtime-scaling/results/1.3.0/25-node/gradual-down-https.png
  tests/zero-downtime-scaling/results/1.3.0/25-node/gradual-up-http.png
  tests/zero-downtime-scaling/results/1.3.0/25-node/gradual-up-https.png
Labels: documentation, tests

#2102 Add manual Graceful recovery results for 1.3.0
  tests/graceful-recovery/graceful-recovery.md
  tests/graceful-recovery/results/1.3.0/1.3.0.md
Labels: documentation, tests

#2104 Add specific instruction for upgrading NGF from OSS to Plus
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
Labels: documentation

#2071 Add how-to for ClientSettingsPolicy
  examples/client-settings-policy/README.md
  examples/client-settings-policy/app.yaml
  examples/client-settings-policy/csp-grpcroute.yaml
  examples/client-settings-policy/csp-httproutes.yaml
  examples/client-settings-policy/gateway-client-settings.yaml
  examples/client-settings-policy/gateway.yaml
  examples/client-settings-policy/grpc-client-settings.yaml
  examples/client-settings-policy/httproutes.yaml
  examples/client-settings-policy/tea-client-settings.yaml
  site/content/how-to/monitoring/tracing.md
  site/content/how-to/monitoring/troubleshooting.md
  site/content/how-to/traffic-management/client-settings.md
Labels: documentation

#2093 Add 1.3.0 longevity test results
  tests/results/longevity/1.3.0/oss-cpu.png
  tests/results/longevity/1.3.0/oss-final-reloads.png
  tests/results/longevity/1.3.0/oss-memory.png
  tests/results/longevity/1.3.0/oss-ngf-memory.png
  tests/results/longevity/1.3.0/oss-reload-time.png
  tests/results/longevity/1.3.0/oss-reloads.png
  tests/results/longevity/1.3.0/oss-stub-status.png
  tests/results/longevity/1.3.0/oss.md
  tests/results/longevity/1.3.0/plus-cpu.png
  tests/results/longevity/1.3.0/plus-final-reloads.png
  tests/results/longevity/1.3.0/plus-memory.png
  tests/results/longevity/1.3.0/plus-ngf-memory.png
  tests/results/longevity/1.3.0/plus-reload-time.png
  tests/results/longevity/1.3.0/plus-reloads.png
  tests/results/longevity/1.3.0/plus-status.png
  tests/results/longevity/1.3.0/plus.md
Labels: documentation, tests

#2114 Add 1.3 reconfig test results
  tests/reconfig/results/1.3.0/1.3.0.md
  tests/reconfig/setup.md
Labels: documentation, tests

#2075 Run functional tests with LoadBalancer
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
Labels: chore

#1884 Generate API docs
  .github/workflows/ci.yml
  Makefile
  apis/v1alpha1/clientsettingspolicy_types.go
  apis/v1alpha1/nginxgateway_types.go
  apis/v1alpha1/nginxproxy_types.go
  apis/v1alpha1/observabilitypolicy_types.go
  go.mod
  go.sum
  site/config/api/config.json
  site/config/api/members.tpl
  site/config/api/pkg.tpl
  site/config/api/type.tpl
  site/content/how-to/monitoring/tracing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/reference/api.md
  tools.go
Labels: documentation, dependencies

#2123 Update release doc for conformance
  docs/developer/release-process.md
Labels: documentation, chore

#2039 Add provisional Enhancement Proposal-2035: Advanced NGINX Extensions
  docs/proposals/advanced-nginx-extensions.md
Labels: documentation, enhancement

#2125 Update docs for 1.3 release
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
  docs/developer/release-process.md
  site/content/how-to/maintenance/upgrade-apps-without-downtime.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/includes/installation/uninstall-gateway-api-resources.md
  site/content/installation/expose-nginx-gateway-fabric.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  site/content/installation/ngf-images/building-the-images.md
  site/content/installation/ngf-images/pulling-ngf-image.md
  site/content/installation/running-on-kind.md
  site/content/overview/gateway-architecture.md
  tests/Makefile
Labels: documentation, chore, helm-chart

#2127 Fix error in uninstall gateway api resources doc
  site/content/includes/installation/uninstall-gateway-api-resources.md
Labels: documentation

#2142 Update GRPCRoute Core Support Level
  site/content/overview/gateway-api-compatibility.md
Labels: documentation

#2122 Add generate-all make target
  .github/workflows/ci.yml
  .github/workflows/release-pr.yml
  Makefile
  docs/developer/quickstart.md
Labels: documentation, chore

#2155 Update stale.yml
  .github/workflows/stale.yml
Labels: chore

#2157 Fix tracing doc namespace
  site/content/how-to/monitoring/tracing.md
Labels: documentation

#2158 Fix tracing doc namespace (#2157)
  site/content/how-to/monitoring/tracing.md
Labels: documentation

#2131 Remove sock files on nginx startup
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  charts/nginx-gateway-fabric/templates/deployment.yaml
  config/tests/static-deployment.yaml
  deploy/manifests/nginx-gateway-experimental.yaml
  deploy/manifests/nginx-gateway.yaml
  deploy/manifests/nginx-plus-gateway-experimental.yaml
  deploy/manifests/nginx-plus-gateway.yaml
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/upstreams.go
  internal/mode/static/nginx/config/upstreams_test.go
  site/content/overview/gateway-architecture.md
  tests/suite/graceful_recovery_test.go
Labels: bug, documentation, helm-chart

#2140 Automate remaining graceful recovery tests
  .github/workflows/functional.yml
  tests/Makefile
  tests/graceful-recovery/graceful-recovery.md
  tests/results/graceful-recovery/1.0.0/1.0.0.md
  tests/results/graceful-recovery/1.1.0/1.1.0.md
  tests/results/graceful-recovery/1.2.0/1.2.0.md
  tests/results/graceful-recovery/1.3.0/1.3.0.md
  tests/suite/graceful_recovery_test.go
  tests/suite/system_suite_test.go
Labels: documentation, tests

#2092 Add more linters
  .github/.cache/buster-for-binary
  .github/.cache/buster-for-unit-tests
  .github/.cache/buster-for-vars
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  apis/v1alpha1/clientsettingspolicy_types.go
  apis/v1alpha1/register.go
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/main.go
  cmd/gateway/validation.go
  internal/framework/controller/predicate/service.go
  internal/framework/controller/reconciler.go
  internal/framework/kinds/kinds.go
  internal/framework/runnables/cronjob.go
  internal/framework/status/updater.go
  internal/mode/static/handler.go
  internal/mode/static/manager.go
  internal/mode/static/metrics/collectors/controller.go
  internal/mode/static/metrics/collectors/nginx.go
  internal/mode/static/metrics/collectors/nginx_runtime.go
  internal/mode/static/metrics/metrics.go
  internal/mode/static/nginx/config/base_http_config_test.go
  internal/mode/static/nginx/config/maps.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/split_clients.go
  internal/mode/static/nginx/config/validation/framework_test.go
  internal/mode/static/nginx/config/validation/http_validator.go
  internal/mode/static/nginx/file/manager_test.go
  internal/mode/static/nginx/file/os_filemanager.go
  internal/mode/static/nginx/runtime/verify.go
  internal/mode/static/nginx/runtime/verify_test.go
  internal/mode/static/policies/clientsettings/validator.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/gateway.go
  internal/mode/static/state/graph/gateway_test.go
  internal/mode/static/state/graph/graph_test.go
  internal/mode/static/state/graph/grpcroute.go
  internal/mode/static/state/graph/policies_test.go
  internal/mode/static/state/graph/reference_grant.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/resolver/resolver.go
  internal/mode/static/state/resolver/resolver_test.go
  internal/mode/static/state/store.go
  internal/mode/static/status/prepare_requests.go
  internal/mode/static/status/status_setters.go
  internal/mode/static/usage/reporter.go
  internal/mode/static/usage/reporter_test.go
  site/content/reference/api.md
  tests/framework/generate_manifests.go
  tests/framework/load.go
  tests/framework/prometheus.go
  tests/framework/resourcemanager.go
  tests/suite/scale_test.go
  tests/suite/tracing_test.go
Labels: documentation, chore

#2180 Run CI and Lint workflows on PRs to any branch
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: chore

#2181 Update CodeQL workflow
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
Labels: chore
