Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-07, with the labels that each got.

#2182 Update Docker frontend and remove noisy summaries for tests
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
  build/Dockerfile
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  debug/Dockerfile
  tests/Dockerfile
  tests/conformance/Dockerfile
Labels: chore

#2186 Use yamllint action from reviewdog
  .github/workflows/lint.yml
Labels: chore

#2202 Fix ObservabilityPolicy TargetRefs documentation
  apis/v1alpha1/observabilitypolicy_types.go
  config/crd/bases/gateway.nginx.org_observabilitypolicies.yaml
  deploy/crds.yaml
  site/content/reference/api.md
Labels: documentation

#2200 Group otel and k8s.io updates
  .github/dependabot.yml
Labels: chore

#2192 Upload Plus Docker images to GAR
  .github/workflows/build.yml
  .github/workflows/nfr.yml
Labels: chore

#2179 Collect ClientSettingsPolicy, ObservabilityPolicy, and NginxProxy count
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/data.avdl
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/ngfresourcecounts_attributes_generated.go
  site/content/overview/product-telemetry.md
  tests/suite/telemetry_test.go
Labels: documentation, enhancement

#2141 Update Troubleshooting guide
  docs/developer/implementing-a-feature.md
  site/content/how-to/monitoring/troubleshooting.md
Labels: documentation, release-notes

#2218 fix: update kubectl exec syntax to remove deprecation warning
  site/content/how-to/monitoring/troubleshooting.md
Labels: documentation

#2213 Use doctoc to automatically generate TOCs
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/developer/go-style-guide.md
  docs/developer/logging-guidelines.md
  docs/developer/quickstart.md
  docs/developer/release-process.md
  docs/proposals/nginx-extensions.md
  tests/README.md
Labels: documentation, chore

#2230 Add helm-docs to pre-commit
  .pre-commit-config.yaml
Labels: chore

#2228 Replace TODO route condition with an Accepted/False condition
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/route_common_test.go
  site/content/overview/gateway-api-compatibility.md
Labels: bug, documentation

#2210 Fix HTTP Response Headers document link
  examples/http-response-header-filter/README.md
Labels: documentation

#2227 Fix: include security note for JWT and password in history
  site/content/includes/installation/jwt-password-note.md
  site/content/installation/ngf-images/jwt-token-docker-secret.md
Labels: documentation

#2216 Feature/allow resource allocation
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/values.yaml
Labels: helm-chart, release-notes

#2236 Update Community Meeting Schedule in README
  README.md
Labels: documentation, chore

#2239 Update Community Meeting Schedule to every Tuesday in README
  README.md
Labels: documentation, chore

#2245 Bump cloud-provider-kind to v0.3.0
  .github/workflows/functional.yml
  .github/workflows/helm.yml
Labels: dependencies

#2250 Add possibility to provide custom pod annotations
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/values.yaml
Labels: documentation, enhancement, helm-chart, community, release-notes

#2249 Run NFR tests on 1st and 15th of every month
  .github/workflows/nfr.yml
  .github/workflows/release-pr.yml
Labels: chore

#2253 Use separate clusters for Plus and OSS
  .github/workflows/nfr.yml
Labels: chore

#2190 Add support for IPv6
  Makefile
  apis/v1alpha1/nginxproxy_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  charts/nginx-gateway-fabric/values.yaml
  config/cluster/kind-cluster.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  docs/developer/quickstart.md
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/upstreams.go
  internal/mode/static/nginx/config/upstreams_test.go
  internal/mode/static/state/conditions/conditions.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/graph.go
  internal/mode/static/state/graph/nginxproxy.go
  internal/mode/static/state/graph/nginxproxy_test.go
  internal/mode/static/state/resolver/resolver.go
  internal/mode/static/state/resolver/resolver_test.go
  internal/mode/static/state/resolver/resolverfakes/fake_service_resolver.go
  internal/mode/static/state/resolver/service_resolver_test.go
  site/content/how-to/monitoring/troubleshooting.md
  site/content/overview/gateway-api-compatibility.md
  site/content/reference/api.md
Labels: documentation, enhancement, helm-chart, release-notes

#2201 Move Advanced NGINX Extensions proposal to Implementable
  docs/proposals/advanced-nginx-extensions.md
Labels: documentation, enhancement

#2255 Truncate test result files
  .github/workflows/nfr.yml
  tests/framework/results.go
Labels: chore

#2261 Add oss suffix to OSS tests results
  .github/workflows/nfr.yml
  tests/framework/results.go
  tests/results/dp-perf/edge/edge-oss.md
  tests/results/ngf-upgrade/edge/edge-oss.md
  tests/results/ngf-upgrade/edge/http-oss.png
  tests/results/ngf-upgrade/edge/https-oss.png
  tests/results/scale/edge/TestScale_HTTPRoutes/cpu-oss.png
  tests/results/scale/edge/TestScale_HTTPRoutes/memory-oss.png
  tests/results/scale/edge/TestScale_HTTPRoutes/ttr-oss.png
  tests/results/scale/edge/TestScale_HTTPSListeners/cpu-oss.png
  tests/results/scale/edge/TestScale_HTTPSListeners/memory-oss.png
  tests/results/scale/edge/TestScale_HTTPSListeners/ttr-oss.png
  tests/results/scale/edge/TestScale_Listeners/cpu-oss.png
  tests/results/scale/edge/TestScale_Listeners/memory-oss.png
  tests/results/scale/edge/TestScale_Listeners/ttr-oss.png
  tests/results/scale/edge/TestScale_UpstreamServers/cpu-oss.png
  tests/results/scale/edge/TestScale_UpstreamServers/memory-oss.png
  tests/results/scale/edge/edge-oss.md
Labels: documentation, chore

#2260 Use custom NGF Debian image for tests
  .github/workflows/nfr.yml
  tests/scripts/create-and-setup-gcp-vm.sh
  tests/scripts/remote-scripts/install-deps.sh
  tests/scripts/remote-scripts/run-nfr-tests.sh
  tests/scripts/remote-scripts/run-tests.sh
  tests/scripts/run-tests-gcp-vm.sh
  tests/scripts/vars.env-example
Labels: chore

#2280 Avoid cloning the repo/downloading dependencies
  .github/workflows/nfr.yml
  tests/scripts/create-and-setup-gcp-vm.sh
  tests/scripts/create-gke-cluster.sh
  tests/scripts/vars.env-example
  tests/suite/upgrade_test.go
Labels: chore

#2263 docs: adds info on setting up host network access
  site/content/installation/running-on-kind.md
Labels: documentation, community

#2256 Update documentation for style consistency
  site/config/api/pkg.tpl
  site/content/how-to/_index.md
  site/content/how-to/configuration/_index.md
  site/content/how-to/control-plane-configuration.md
  site/content/how-to/maintenance/_index.md
  site/content/how-to/monitoring/_index.md
  site/content/how-to/monitoring/dashboard.md
  site/content/how-to/monitoring/prometheus.md
  site/content/how-to/monitoring/tracing.md
  site/content/how-to/monitoring/troubleshooting.md
  site/content/how-to/traffic-management/_index.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/how-to/traffic-management/https-termination.md
  site/content/how-to/traffic-management/integrating-cert-manager.md
  site/content/how-to/traffic-management/redirects-and-rewrites.md
  site/content/how-to/traffic-management/response-headers.md
  site/content/how-to/traffic-management/routing-traffic-to-your-app.md
  site/content/how-to/traffic-management/securing-backend-traffic.md
  site/content/how-to/upgrade-apps-without-downtime.md
  site/content/includes/installation/jwt-password-note.md
  site/content/installation/expose-nginx-gateway-fabric.md
  site/content/installation/installing-ngf/_index.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  site/content/installation/ngf-images/building-the-images.md
  site/content/installation/ngf-images/jwt-token-docker-secret.md
  site/content/installation/ngf-images/pulling-ngf-image.md
  site/content/installation/running-on-kind.md
  site/content/installation/usage-reporting.md
  site/content/overview/gateway-api-compatibility.md
  site/content/overview/gateway-architecture.md
  site/content/overview/nginx-plus.md
  site/content/overview/product-telemetry.md
  site/content/overview/resource-validation.md
  site/content/reference/api.md
  site/content/reference/cli-help.md
  site/content/reference/technical-specifications.md
Labels: documentation

#2289 Fix: update support link to KB K000140156
  .hugo_build.lock
  site/content/overview/nginx-plus.md
  site/content/support.md
Labels: documentation

#2305 Hide NGINX version
  internal/mode/static/nginx/conf/nginx-plus.conf
  internal/mode/static/nginx/conf/nginx.conf
Labels: chore

#2307 Properly disable leader election
  internal/mode/static/manager.go
Labels: bug

#2291 Update release process doc
  docs/developer/release-process.md
Labels: documentation, chore

#2315 Use /usr/bin/env for scripts
  .pre-commit-config.yaml
  tests/Makefile
  tests/reconfig/scripts/create-resources-gw-last.sh
  tests/reconfig/scripts/create-resources-routes-last.sh
  tests/reconfig/scripts/delete-multiple.sh
  tests/results/dp-perf/1.2.0/1.2.0-plus.md
  tests/results/dp-perf/1.2.0/1.2.0.md
  tests/results/dp-perf/1.3.0/1.3.0-plus.md
  tests/results/dp-perf/1.3.0/1.3.0.md
  tests/results/dp-perf/edge/edge-oss.md
  tests/results/dp-perf/edge/edge-plus.md
  tests/results/ngf-upgrade/1.2.0/1.2.0-plus.md
  tests/results/ngf-upgrade/1.2.0/1.2.0.md
  tests/results/ngf-upgrade/1.3.0/1.3.0-plus.md
  tests/results/ngf-upgrade/1.3.0/1.3.0.md
  tests/results/ngf-upgrade/edge/edge-oss.md
  tests/results/ngf-upgrade/edge/edge-plus.md
  tests/results/scale/1.3.0/1.3.0-plus.md
  tests/results/scale/1.3.0/1.3.0.md
  tests/results/scale/edge/edge-oss.md
  tests/results/scale/edge/edge-plus.md
  tests/scripts/add-local-ip-auth-networks.sh
  tests/scripts/check-pod-exit-code.sh
  tests/scripts/cleanup-router.sh
  tests/scripts/cleanup-vm.sh
  tests/scripts/create-and-setup-gcp-vm.sh
  tests/scripts/create-gke-cluster.sh
  tests/scripts/create-gke-router.sh
  tests/scripts/delete-gke-cluster.sh
  tests/scripts/remote-scripts/run-nfr-tests.sh
  tests/scripts/remote-scripts/run-tests.sh
  tests/scripts/run-tests-gcp-vm.sh
  tests/scripts/sync-files-to-vm.sh
  tests/suite/scripts/longevity-wrk.sh
Labels: documentation, chore

#2320 Fix problems in tests scripts
  tests/scripts/create-and-setup-gcp-vm.sh
  tests/scripts/create-gke-cluster.sh
  tests/scripts/sync-files-to-vm.sh
Labels: chore
