Repository nginx/nginx-gateway-fabric, pull requests merged in 2024-03, with the labels that each got.

#1639 NFR: Add convenience script and update workflow token
  .github/workflows/nfr.yml
  tests/Makefile
  tests/README.md
  tests/scripts/add-local-ip-auth-networks.sh
  tests/scripts/create-gke-cluster.sh
Labels: documentation, chore

#1650 Update community meeting schedule to every other Monday
  README.md
Labels: documentation, chore

#1656 Integrate telemetry exporter
  .goreleaser.yml
  .pre-commit-config.yaml
  Makefile
  build/Dockerfile
  cmd/gateway/commands.go
  cmd/gateway/main.go
  cmd/gateway/validation.go
  cmd/gateway/validation_test.go
  docs/developer/implementing-a-feature.md
  docs/developer/quickstart.md
  go.mod
  go.sum
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/data.avdl
  internal/mode/static/telemetry/data_attributes_generated.go
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/exporter.go
  internal/mode/static/telemetry/exporter_test.go
  internal/mode/static/telemetry/job_worker.go
  internal/mode/static/telemetry/job_worker_test.go
  internal/mode/static/telemetry/ngfresourcecounts_attributes_generated.go
  internal/mode/static/telemetry/telemetryfakes/fake_exporter.go
Labels: documentation, enhancement, dependencies

#1620 Add Grafana dashboard and installation steps
  site/content/how-to/monitoring/prometheus.md
  site/go.mod
  site/go.sum
  site/static/grafana-dashboard.json
Labels: documentation, release-notes

#1657 Automate longevity test
  .github/workflows/nfr.yml
  .gitignore
  .yamllint.yaml
  tests/Makefile
  tests/README.md
  tests/framework/results.go
  tests/longevity/longevity.md
  tests/results/longevity/1.0.0/1.0.0.md
  tests/results/longevity/1.0.0/cpu.png
  tests/results/longevity/1.0.0/memory.png
  tests/results/longevity/1.0.0/reload-time.png
  tests/results/longevity/1.0.0/reloads.png
  tests/results/longevity/1.0.0/stub-status.png
  tests/results/longevity/1.1.0/1.1.0.md
  tests/results/longevity/1.1.0/cpu.png
  tests/results/longevity/1.1.0/memory.png
  tests/results/longevity/1.1.0/reload-time.png
  tests/results/longevity/1.1.0/reloads.png
  tests/results/longevity/1.1.0/stub-status.png
  tests/scripts/create-gke-cluster.sh
  tests/scripts/remote-scripts/install-deps.sh
  tests/scripts/remote-scripts/run-nfr-tests.sh
  tests/scripts/run-tests-gcp-vm.sh
  tests/scripts/sync-files-to-vm.sh
  tests/suite/dataplane_perf_test.go
  tests/suite/longevity_test.go
  tests/suite/manifests/longevity/cafe-routes.yaml
  tests/suite/manifests/longevity/cafe-secret.yaml
  tests/suite/manifests/longevity/cafe.yaml
  tests/suite/manifests/longevity/cronjob.yaml
  tests/suite/manifests/longevity/gateway.yaml
  tests/suite/manifests/longevity/prom.yaml
  tests/suite/sample_test.go
  tests/suite/scripts/longevity-wrk.sh
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: documentation, tests

#1659 Add functional test for product telemetry
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
  .goreleaser.yml
  tests/Makefile
  tests/README.md
  tests/framework/resourcemanager.go
  tests/suite/manifests/telemetry/collector-values.yaml
  tests/suite/system_suite_test.go
  tests/suite/telemetry_test.go
Labels: documentation, tests

#1651 Collect Kubernetes distribution platform and version
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/platform.go
  internal/mode/static/telemetry/platform_test.go
  internal/mode/static/usage/job_worker.go
  internal/mode/static/usage/job_worker_test.go
Labels: enhancement

#1702 Only write images to cache from the Build job
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
Labels: chore

#1689 Enable ginkgolinter and fix finding
  .golangci.yml
  internal/framework/controller/register_test.go
  internal/framework/events/events_test.go
  internal/framework/events/first_eventbatch_preparer_test.go
  internal/framework/events/loop_test.go
  internal/framework/runnables/runnables_test.go
  internal/mode/provisioner/handler_test.go
  internal/mode/static/handler_test.go
  internal/mode/static/sort/sort_test.go
  internal/mode/static/state/graph/backend_tls_policy_test.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/secret_test.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/exporter_test.go
  tests/suite/longevity_test.go
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: chore, community

#1699 Enable Production Endpoint for Product Telemetry
  .github/workflows/ci.yml
  Makefile
  site/content/installation/ngf-images/building-the-images.md
Labels: documentation, enhancement, release-notes

#1614 Product Telemetry collection document
  site/content/overview/gateway-architecture.md
  site/content/overview/product-telemetry.md
Labels: documentation

#1714 Disable sending telemetry in tests
  .github/workflows/ci.yml
  Makefile
  conformance/provisioner/static-deployment.yaml
  tests/framework/ngf.go
  tests/suite/telemetry_test.go
Labels: bug

#1717 Graceful Recovery Results 1.2
  tests/graceful-recovery/graceful-recovery.md
  tests/graceful-recovery/results/1.2.0/1.2.0.md
Labels: documentation, tests

#1716 Fix NFR upgrade test
  tests/suite/upgrade_test.go
Labels: bug

#1718 Reconfig test results for 1.2.0
  tests/reconfig/results/1.2.0/1.2.0.md
  tests/reconfig/scripts/cafe-routes.yaml
Labels: documentation, tests

#1721 Fix automated NFR issues with OSS vs Plus
  .github/workflows/nfr.yml
  tests/Makefile
  tests/framework/results.go
  tests/suite/dataplane_perf_test.go
  tests/suite/longevity_test.go
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: tests

#1719 Remove broken Conformance badge from README
  README.md
Labels: documentation, chore

#1725 Fix NFR workflow input check
  .github/workflows/nfr.yml
Labels: chore

#1728 Use nginx-bot in NFR PR
  .github/workflows/nfr.yml
Labels: chore

#1727 Added product telemetry performance test results
  tests/results/product-telemetry-performance/README.md
  tests/results/product-telemetry-performance/collector-values.yaml
  tests/results/product-telemetry-performance/img/cluster-1day-collect-not-report-cpu-usage.png
  tests/results/product-telemetry-performance/img/cluster-1day-collect-not-report-ngf-go-stats.png
  tests/results/product-telemetry-performance/img/cluster-1day-collect-not-report-ngf-mem-usage.png
  tests/results/product-telemetry-performance/img/cluster-1day-one-cpu-usage.png
  tests/results/product-telemetry-performance/img/cluster-1day-one-ngf-go-stats.png
  tests/results/product-telemetry-performance/img/cluster-1day-one-ngf-mem-usage.png
  tests/results/product-telemetry-performance/img/cluster-1day-three-cpu-usage.png
  tests/results/product-telemetry-performance/img/cluster-1day-three-mem-profile.png
  tests/results/product-telemetry-performance/img/cluster-1day-three-ngf-go-stats.png
  tests/results/product-telemetry-performance/img/cluster-1day-three-ngf-mem-usage.png
  tests/results/product-telemetry-performance/img/cluster-1day-two-cpu-usage.png
  tests/results/product-telemetry-performance/img/cluster-1day-two-ngf-go-stats.png
  tests/results/product-telemetry-performance/img/cluster-1day-two-ngf-mem-usage.png
  tests/results/product-telemetry-performance/img/cluster-1hour-cpu-usage.png
  tests/results/product-telemetry-performance/img/cluster-1hour-ngf-go-stats.png
  tests/results/product-telemetry-performance/img/cluster-1hour-ngf-mem-usage.png
  tests/results/product-telemetry-performance/img/cluster-1min-cpu-usage.png
  tests/results/product-telemetry-performance/img/cluster-1min-ngf-go-stats.png
  tests/results/product-telemetry-performance/img/cluster-1min-ngf-mem-usage.png
  tests/results/product-telemetry-performance/img/cluster-no-tel-cpu-usage.png
  tests/results/product-telemetry-performance/img/cluster-no-tel-mem-profile.png
  tests/results/product-telemetry-performance/img/cluster-no-tel-ngf-go-stats.png
  tests/results/product-telemetry-performance/img/cluster-no-tel-ngf-mem-usage.png
  tests/results/product-telemetry-performance/img/cluster-tel-disabled-cpu-usage.png
  tests/results/product-telemetry-performance/img/cluster-tel-disabled-mem-profile.png
  tests/results/product-telemetry-performance/img/cluster-tel-disabled-ngf-go-stats.png
  tests/results/product-telemetry-performance/img/cluster-tel-disabled-ngf-mem-usage.png
Labels: documentation, tests

#1730 Update the docs to point to v1.1.0
  Makefile
  deploy/helm-chart/Chart.yaml
  site/content/how-to/maintenance/upgrade-apps-without-downtime.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/installation/expose-nginx-gateway-fabric.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  site/content/installation/ngf-images/building-the-images.md
  site/content/installation/ngf-images/pulling-ngf-image.md
  site/content/installation/running-on-kind.md
  site/content/overview/gateway-architecture.md
Labels: documentation, helm-chart

#1731 Do not send telemetry data if failure in collection
  internal/framework/events/events_test.go
  internal/mode/static/telemetry/job_worker.go
  internal/mode/static/telemetry/job_worker_test.go
  internal/mode/static/usage/job_worker.go
  internal/mode/static/usage/job_worker_test.go
Labels: bug

#1734 Add scale test results for 1.2
  internal/mode/static/nginx/config/upstreams_template.go
  tests/scale/results/1.2.0/1.2.0.md
  tests/scale/results/1.2.0/TestScale_HTTPRoutes/CPU.png
  tests/scale/results/1.2.0/TestScale_HTTPRoutes/Memory.png
  tests/scale/results/1.2.0/TestScale_HTTPRoutes/TTR-without-peak.png
  tests/scale/results/1.2.0/TestScale_HTTPRoutes/TTR.png
  tests/scale/results/1.2.0/TestScale_HTTPRoutes_Plus/CPU.png
  tests/scale/results/1.2.0/TestScale_HTTPRoutes_Plus/Memory.png
  tests/scale/results/1.2.0/TestScale_HTTPRoutes_Plus/TTR.png
  tests/scale/results/1.2.0/TestScale_HTTPSListeners/CPU.png
  tests/scale/results/1.2.0/TestScale_HTTPSListeners/Memory.png
  tests/scale/results/1.2.0/TestScale_HTTPSListeners/TTR.png
  tests/scale/results/1.2.0/TestScale_HTTPSListeners_Plus/CPU.png
  tests/scale/results/1.2.0/TestScale_HTTPSListeners_Plus/Memory.png
  tests/scale/results/1.2.0/TestScale_HTTPSListeners_Plus/TTR.png
  tests/scale/results/1.2.0/TestScale_Listeners/CPU.png
  tests/scale/results/1.2.0/TestScale_Listeners/Memory.png
  tests/scale/results/1.2.0/TestScale_Listeners/TTR.png
  tests/scale/results/1.2.0/TestScale_Listeners_Plus/CPU.png
  tests/scale/results/1.2.0/TestScale_Listeners_Plus/Memory.png
  tests/scale/results/1.2.0/TestScale_Listeners_Plus/TTR.png
  tests/scale/results/1.2.0/TestScale_UpstreamServers/CPU.png
  tests/scale/results/1.2.0/TestScale_UpstreamServers/Memory.png
  tests/scale/results/1.2.0/TestScale_UpstreamServers_Plus/CPU.png
  tests/scale/results/1.2.0/TestScale_UpstreamServers_Plus/Memory.png
  tests/scale/scale.md
  tests/scale/scale_test.go
Labels: documentation, tests

#1737 Add longevity test results for 1.2.0
  tests/results/longevity/1.2.0/1.2.0.md
  tests/results/longevity/1.2.0/oss-1.1.0-memory.png
  tests/results/longevity/1.2.0/oss-cpu.png
  tests/results/longevity/1.2.0/oss-final-reloads.png
  tests/results/longevity/1.2.0/oss-memory.png
  tests/results/longevity/1.2.0/oss-ngf-memory.png
  tests/results/longevity/1.2.0/oss-reload-time.png
  tests/results/longevity/1.2.0/oss-reloads.png
  tests/results/longevity/1.2.0/oss-stub-status.png
  tests/results/longevity/1.2.0/plus-cpu.png
  tests/results/longevity/1.2.0/plus-final-reloads.png
  tests/results/longevity/1.2.0/plus-memory.png
  tests/results/longevity/1.2.0/plus-ngf-memory.png
  tests/results/longevity/1.2.0/plus-reload-time.png
  tests/results/longevity/1.2.0/plus-reloads.png
  tests/results/longevity/1.2.0/plus-status.png
Labels: documentation, tests

#1732 Create Release PR workflow
  .github/CHANGELOG_TEMPLATE.md
  .github/workflows/nfr.yml
  .github/workflows/release-pr.yml
  docs/developer/release-process.md
Labels: documentation, chore

#1733 Add test results for zero downtime scaling
  tests/zero-downtime-scaling/results/1.2.0/1.2.0.md
  tests/zero-downtime-scaling/results/1.2.0/10-node/abrupt-down-http.png
  tests/zero-downtime-scaling/results/1.2.0/10-node/abrupt-down-https.png
  tests/zero-downtime-scaling/results/1.2.0/10-node/abrupt-up-http.png
  tests/zero-downtime-scaling/results/1.2.0/10-node/abrupt-up-https.png
  tests/zero-downtime-scaling/results/1.2.0/10-node/gradual-down-http.png
  tests/zero-downtime-scaling/results/1.2.0/10-node/gradual-down-https.png
  tests/zero-downtime-scaling/results/1.2.0/10-node/gradual-up-http.png
  tests/zero-downtime-scaling/results/1.2.0/10-node/gradual-up-https.png
  tests/zero-downtime-scaling/results/1.2.0/25-node/abrupt-down-http.png
  tests/zero-downtime-scaling/results/1.2.0/25-node/abrupt-down-https.png
  tests/zero-downtime-scaling/results/1.2.0/25-node/abrupt-up-http.png
  tests/zero-downtime-scaling/results/1.2.0/25-node/abrupt-up-https.png
  tests/zero-downtime-scaling/results/1.2.0/25-node/gradual-down-http.png
  tests/zero-downtime-scaling/results/1.2.0/25-node/gradual-down-https.png
  tests/zero-downtime-scaling/results/1.2.0/25-node/gradual-up-http.png
  tests/zero-downtime-scaling/results/1.2.0/25-node/gradual-up-https.png
Labels: documentation

#1751 Add workaround for golangci-lint errors
  .github/workflows/lint.yml
Labels: chore

#1752 Fix release notes link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, chore

#1756 Mark old data plane proposal as Replaced
  docs/proposals/data-plane-config.md
  docs/proposals/nginx-extensions.md
Labels: documentation, chore

#1692 Client Settings Policy Enhancement Proposal
  docs/developer/mapping.md
  docs/images/client-settings/attach-1.png
  docs/images/client-settings/attach-2.png
  docs/images/client-settings/attach-3.png
  docs/images/client-settings/example-a1.png
  docs/images/client-settings/example-a2.png
  docs/images/client-settings/example-a3.png
  docs/images/client-settings/example-b1.png
  docs/images/client-settings/example-b2.png
  docs/images/client-settings/example-b3.png
  docs/images/client-settings/example-c1.png
  docs/images/client-settings/example-c2.png
  docs/images/client-settings/example-c3.png
  docs/images/mapping/mapping-a.png
  docs/images/mapping/mapping-b.png
  docs/images/mapping/mapping-c.png
  docs/proposals/client-settings.md
  docs/proposals/nginx-extensions.md
Labels: enhancement-proposal

#1785 Update ClientSettingsPolicy future work section
  docs/proposals/client-settings.md
Labels: documentation

#1755 Add support for s390x and ppc64le
  .github/workflows/ci.yml
  .goreleaser.yml
Labels: chore, release-notes

#1786 Force conformance tests to fail properly
  conformance/Makefile
  conformance/scripts/check-pod-exit-code.sh
Labels: tests, conformance
