Repository nginx/nginx-gateway-fabric, pull requests merged in 2025-07, with the labels that each got.

#3573 Move automountServiceAccountToken to Pod
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/serviceaccount.yaml
  deploy/azure/deploy.yaml
  deploy/default/deploy.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  deploy/nginx-plus/deploy.yaml
  deploy/nodeport/deploy.yaml
  deploy/openshift/deploy.yaml
  deploy/snippets-filters-nginx-plus/deploy.yaml
  deploy/snippets-filters/deploy.yaml
  internal/controller/provisioner/objects.go
Labels: bug, helm-chart, release-notes

#3572 Remove omitted comment
  charts/nginx-gateway-fabric/values.yaml
Labels: chore, helm-chart

#3575 Fix crash when BackendRef filter is specified (#3508)
  internal/controller/state/graph/httproute.go
  internal/controller/state/graph/httproute_test.go
Labels: bug, release-notes

#3576 Fix index out of bounds error when building status (#3513)
  internal/controller/status/prepare_requests.go
  internal/controller/status/prepare_requests_test.go
Labels: bug, release-notes

#3580 Move automountServiceAccountToken to Pod (#3573)
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/serviceaccount.yaml
  deploy/azure/deploy.yaml
  deploy/default/deploy.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  deploy/nginx-plus/deploy.yaml
  deploy/nodeport/deploy.yaml
  deploy/openshift/deploy.yaml
  deploy/snippets-filters-nginx-plus/deploy.yaml
  deploy/snippets-filters/deploy.yaml
  internal/controller/provisioner/objects.go
Labels: bug, helm-chart, release-notes

#3577 Implement basic file fetcher
  docs/proposals/nap-waf.md
  internal/framework/fetch/errors.go
  internal/framework/fetch/fetch.go
  internal/framework/fetch/fetch_test.go
  internal/framework/fetch/fetchfakes/fake_fetcher.go
Labels: documentation, enhancement

#3589 Use server side apply for NGF CRDs
  Makefile
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/README.md.gotmpl
  docs/developer/quickstart.md
Labels: documentation, chore, helm-chart, release-notes

#3590 Fix port binding with reduced privileges (#3574)
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  charts/nginx-gateway-fabric/templates/scc.yaml
  deploy/openshift/deploy.yaml
  internal/controller/provisioner/objects.go
Labels: bug, helm-chart, release-notes

#3591 Only include relevant snippets (#3586)
  internal/controller/state/dataplane/configuration.go
  internal/controller/state/dataplane/configuration_test.go
  internal/controller/state/graph/gateway.go
  internal/controller/state/graph/gateway_test.go
Labels: bug, release-notes

#3321 Support configurable hostPort in helm chart
  apis/v1alpha2/nginxproxy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/_helpers.tpl
  charts/nginx-gateway-fabric/templates/nginxproxy.yaml
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/controller/provisioner/objects.go
  internal/controller/provisioner/objects_test.go
Labels: documentation, enhancement, helm-chart, community

#3601 Update community forum link
  CONTRIBUTING.md
  README.md
Labels: documentation, chore

#3602 Enable GatewayAddressEmpty conformance test
  tests/Makefile
Labels: tests

#3607 Update NGINX and NGINX Agent versions
  README.md
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  go.mod
  go.sum
Labels: dependencies

#3611 Add worker connections field to NginxProxy
  apis/v1alpha2/nginxproxy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/controller/nginx/conf/nginx-plus.conf
  internal/controller/nginx/conf/nginx.conf
  internal/controller/nginx/config/main_config_template.go
  internal/controller/nginx/config/main_config_test.go
  internal/controller/provisioner/objects.go
  internal/controller/provisioner/objects_test.go
  internal/controller/provisioner/templates.go
  internal/controller/state/dataplane/configuration.go
  internal/controller/state/dataplane/configuration_test.go
  internal/controller/state/dataplane/types.go
Labels: enhancement

#3557 Add simplified architecture diagrams for traffic flow and config changes
  docs/architecture/README.md
  docs/architecture/configuration-flow.md
  docs/architecture/gateway-lifecycle.md
  docs/architecture/traffic-flow.md
Labels: documentation, chore, community

#3616 Add workerConnections field to helm chart
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
Labels: enhancement, helm-chart

#3629 Add readiness probe for NGINX on pod startup
  apis/v1alpha2/nginxproxy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/controller/nginx/config/base_http_config.go
  internal/controller/nginx/config/base_http_config_template.go
  internal/controller/nginx/config/base_http_config_test.go
  internal/controller/provisioner/objects.go
  internal/controller/provisioner/objects_test.go
  internal/controller/state/dataplane/configuration.go
  internal/controller/state/dataplane/configuration_test.go
  internal/controller/state/dataplane/types.go
Labels: documentation, enhancement, helm-chart, release-notes

#3630 feat: Add ability to patch dataplane Service, Deployment, and DaemonSet in NginxProxy
  apis/v1alpha2/nginxproxy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  go.mod
  internal/controller/provisioner/objects.go
  internal/controller/provisioner/objects_test.go
Labels: enhancement, dependencies, release-notes

#3667 Add logging for endpoint discovery issues
  internal/controller/handler.go
  internal/controller/nginx/agent/agent.go
  internal/controller/state/dataplane/configuration.go
  internal/controller/state/dataplane/configuration_test.go
  internal/controller/state/resolver/resolver.go
  internal/controller/state/resolver/resolver_test.go
  internal/controller/state/resolver/resolverfakes/fake_service_resolver.go
  internal/controller/state/resolver/service_resolver_test.go
Labels: chore
