Repository nginx/nginx-gateway-fabric, pull requests merged in 2025-03, with the labels that each got.

#3185 Update go oauth indirect dependency
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: dependencies

#3180 CP/DP Split: remove unneeded provisioner mode
  .github/workflows/conformance.yml
  charts/nginx-gateway-fabric/templates/deployment.yaml
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/main.go
  config/tests/static-deployment.yaml
  deploy/aws-nlb/deploy.yaml
  deploy/azure/deploy.yaml
  deploy/default/deploy.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  deploy/nginx-plus/deploy.yaml
  deploy/nodeport/deploy.yaml
  deploy/openshift/deploy.yaml
  deploy/snippets-filters-nginx-plus/deploy.yaml
  deploy/snippets-filters/deploy.yaml
  docs/developer/release-process.md
  docs/proposals/nginx-extensions.md
  embedded.go
  internal/mode/provisioner/deployment.go
  internal/mode/provisioner/doc.go
  internal/mode/provisioner/handler.go
  internal/mode/provisioner/handler_test.go
  internal/mode/provisioner/manager.go
  internal/mode/provisioner/provisioner_suite_test.go
  internal/mode/provisioner/store.go
  internal/mode/static/manager.go
  internal/mode/static/metrics/collectors/nginx_runtime.go
  scripts/generate-manifests.sh
  tests/Makefile
  tests/README.md
  tests/conformance/provisioner/README.md
  tests/conformance/provisioner/provisioner.yaml
Labels: documentation, chore, tests, helm-chart

#3159 Modify listener isolation rules for routes
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/route_common_test.go
Labels: bug

#3197 Update golang.org/x/oauth2 (#3185)
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: dependencies

#3193 CP/DP split: update/delete user secrets
  internal/framework/controller/predicate/annotation.go
  internal/framework/controller/predicate/secret.go
  internal/framework/controller/predicate/secret_test.go
  internal/framework/controller/resource.go
  internal/mode/static/provisioner/eventloop.go
  internal/mode/static/provisioner/handler.go
  internal/mode/static/provisioner/handler_test.go
  internal/mode/static/provisioner/provisioner.go
  internal/mode/static/provisioner/provisioner_test.go
  internal/mode/static/provisioner/store.go
  internal/mode/static/provisioner/store_test.go
Labels: chore

#3204 Update README with new NGINX forum
  README.md
Labels: documentation, chore

#3206 Update main branch for 1.6.2 release
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
  docs/developer/release-process.md
Labels: chore

#3194 Add support for deployment labels to helm chart
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
Labels: documentation, helm-chart, community

#3207 CP/DP Split: Update functional tests
  internal/mode/static/provisioner/handler.go
  internal/mode/static/provisioner/handler_test.go
  internal/mode/static/provisioner/objects.go
  internal/mode/static/provisioner/objects_test.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  tests/framework/collector.go
  tests/framework/crossplane.go
  tests/framework/portforward.go
  tests/framework/resourcemanager.go
  tests/suite/advanced_routing_test.go
  tests/suite/client_settings_test.go
  tests/suite/dataplane_perf_test.go
  tests/suite/graceful_recovery_test.go
  tests/suite/manifests/tracing/nginxproxy.yaml
  tests/suite/reconfig_test.go
  tests/suite/sample_test.go
  tests/suite/snippets_filter_test.go
  tests/suite/system_suite_test.go
  tests/suite/telemetry_test.go
  tests/suite/tracing_test.go
  tests/suite/upstream_settings_test.go
Labels: tests

#3244 CP/DP split: Secure connection
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/certs-job.yaml
  charts/nginx-gateway-fabric/templates/clusterrole.yaml
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/scc.yaml
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
  cmd/gateway/certs.go
  cmd/gateway/certs_test.go
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  cmd/gateway/main.go
  deploy/aws-nlb/deploy.yaml
  deploy/azure/deploy.yaml
  deploy/default/deploy.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  deploy/nginx-plus/deploy.yaml
  deploy/nodeport/deploy.yaml
  deploy/openshift/deploy.yaml
  deploy/snippets-filters-nginx-plus/deploy.yaml
  deploy/snippets-filters/deploy.yaml
  go.mod
  internal/framework/controller/index/pod.go
  internal/framework/controller/index/pod_test.go
  internal/framework/controller/register.go
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  internal/mode/static/nginx/agent/agent.go
  internal/mode/static/nginx/agent/agent_test.go
  internal/mode/static/nginx/agent/command.go
  internal/mode/static/nginx/agent/command_test.go
  internal/mode/static/nginx/agent/grpc/connections.go
  internal/mode/static/nginx/agent/grpc/context/context.go
  internal/mode/static/nginx/agent/grpc/filewatcher/doc.go
  internal/mode/static/nginx/agent/grpc/filewatcher/filewatcher.go
  internal/mode/static/nginx/agent/grpc/filewatcher/filewatcher_test.go
  internal/mode/static/nginx/agent/grpc/grpc.go
  internal/mode/static/nginx/agent/grpc/interceptor/interceptor.go
  internal/mode/static/nginx/agent/grpc/interceptor/interceptor_test.go
  internal/mode/static/provisioner/eventloop.go
  internal/mode/static/provisioner/handler.go
  internal/mode/static/provisioner/handler_test.go
  internal/mode/static/provisioner/objects.go
  internal/mode/static/provisioner/objects_test.go
  internal/mode/static/provisioner/provisioner.go
  internal/mode/static/provisioner/provisioner_test.go
  internal/mode/static/provisioner/store.go
  internal/mode/static/provisioner/store_test.go
  internal/mode/static/provisioner/templates.go
Labels: documentation, dependencies, chore, helm-chart

#3249 De-duplicate base headers if specified by user
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_test.go
Labels: bug, release-notes

#3269 Update golangci-lint to v2
  .github/workflows/lint.yml
  .golangci.yml
  .pre-commit-config.yaml
  Makefile
  internal/mode/provisioner/deployment.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/tlsroute_test.go
  internal/mode/static/telemetry/collector_test.go
Labels: chore
