Repository nginx/nginx-gateway-fabric, pull requests merged in 2025-01, with the labels that each got.

#2958 CP/DP Split: Add agent/nginx container and deployment
  .yamllint.yaml
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  build/entrypoint.sh
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/service.yaml
  charts/nginx-gateway-fabric/templates/tmp-nginx-agent-conf.yaml
  charts/nginx-gateway-fabric/templates/tmp-nginx-deployment.yaml
  charts/nginx-gateway-fabric/templates/tmp-nginx-service.yaml
  charts/nginx-gateway-fabric/tmp/tmp-nginx-deployment.yaml
  charts/nginx-gateway-fabric/tmp/tmp-nginx-service.yaml
  config/tests/static-deployment.yaml
  deploy/aws-nlb/deploy.yaml
  deploy/azure/deploy.yaml
  deploy/default/deploy.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  deploy/nginx-plus/deploy.yaml
  deploy/nodeport/deploy.yaml
  deploy/openshift/deploy.yaml
  deploy/snippets-filters-nginx-plus/deploy.yaml
  deploy/snippets-filters/deploy.yaml
  go.mod
  go.sum
  internal/mode/static/manager.go
  internal/mode/static/nginx/agent/agent.go
  internal/mode/static/nginx/agent/command.go
  internal/mode/static/nginx/agent/file.go
  internal/mode/static/nginx/agent/grpc.go
  tests/go.mod
  tests/go.sum
Labels: dependencies, chore, helm-chart

#2951 Fix rewrite path for ReplacePrefixMatch to parse request arguments correctly
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_test.go
  site/content/how-to/traffic-management/redirects-and-rewrites.md
Labels: bug, documentation

#2967 Fix NFR upgrade tests with NGINX Plus
  tests/Makefile
  tests/framework/ngf.go
  tests/scripts/remote-scripts/run-nfr-tests.sh
  tests/scripts/vars.env-example
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: tests

#2971 Improve usage reporting in automated tests
  .github/workflows/conformance.yml
  tests/framework/nginx_log_levels.go
  tests/suite/graceful_recovery_test.go
  tests/suite/reconfig_test.go
  tests/suite/scale_test.go
Labels: tests

#2974 Update shfmt
  .pre-commit-config.yaml
Labels: dependencies

#2978 Fix getting started link in README
  README.md
Labels: documentation, chore

#2981 Fix small typo in test name
  internal/mode/static/state/graph/policies_test.go
Labels: chore

#2970 CP/DP Split: track agent connections
  internal/mode/static/manager.go
  internal/mode/static/nginx/agent/agent.go
  internal/mode/static/nginx/agent/command.go
  internal/mode/static/nginx/agent/file.go
  internal/mode/static/nginx/agent/grpc.go
  internal/mode/static/nginx/agent/grpc/connections.go
  internal/mode/static/nginx/agent/grpc/context/context.go
  internal/mode/static/nginx/agent/grpc/context/doc.go
  internal/mode/static/nginx/agent/grpc/doc.go
  internal/mode/static/nginx/agent/grpc/grpc.go
  internal/mode/static/nginx/agent/grpc/interceptor/doc.go
  internal/mode/static/nginx/agent/grpc/interceptor/interceptor.go
Labels: chore

#2979 Add path field for RequestRedirect Filter
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/validation/common.go
  internal/mode/static/nginx/config/validation/common_test.go
  internal/mode/static/nginx/config/validation/http_filters.go
  internal/mode/static/nginx/config/validation/http_filters_test.go
  internal/mode/static/nginx/config/validation/http_validator.go
  internal/mode/static/state/dataplane/convert.go
  internal/mode/static/state/dataplane/convert_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/httproute.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/validation/validationfakes/fake_httpfields_validator.go
  internal/mode/static/state/validation/validator.go
  site/content/how-to/traffic-management/redirects-and-rewrites.md
  site/content/overview/gateway-api-compatibility.md
  tests/Makefile
Labels: documentation, enhancement, tests

#2985 Update references to new repo (2)
  .github/workflows/build.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/README.md.gotmpl
  docs/developer/branching-and-workflow.md
  docs/developer/quickstart.md
  docs/proposals/data-plane-config.md
  site/config/_default/config.toml
  site/content/get-started.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/how-to/traffic-management/request-response-headers.md
  site/content/how-to/traffic-management/snippets.md
  site/content/includes/installation/helm/pulling-the-chart.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  tests/results/graceful-recovery/1.0.0/1.0.0.md
  tests/results/graceful-recovery/1.1.0/1.1.0.md
  tests/results/graceful-recovery/1.2.0/1.2.0.md
  tests/results/graceful-recovery/1.3.0/1.3.0.md
  tests/results/longevity/1.0.0/1.0.0.md
  tests/results/longevity/1.1.0/1.1.0.md
  tests/results/longevity/1.2.0/1.2.0.md
  tests/results/longevity/1.3.0/oss.md
  tests/results/longevity/1.3.0/plus.md
  tests/results/ngf-upgrade/1.0.0-special/1.0.0-special.md
  tests/results/ngf-upgrade/1.0.0/1.0.0.md
  tests/results/product-telemetry-performance/README.md
  tests/results/reconfig/1.0.0/1.0.0.md
  tests/results/reconfig/1.1.0/1.1.0.md
  tests/results/reconfig/1.2.0/1.2.0.md
  tests/results/reconfig/1.3.0/1.3.0.md
  tests/results/scale/1.0.0/1.0.0.md
  tests/results/scale/1.4.0/1.4.0-plus.md
  tests/results/zero-downtime-scale/1.0.0/1.0.0.md
  tests/results/zero-downtime-scale/1.1.0/1.1.0.md
  tests/results/zero-downtime-scale/1.2.0/1.2.0.md
  tests/scripts/create-and-setup-gcp-vm.sh
  tests/suite/upgrade_test.go
Labels: documentation, chore, tests, helm-chart

#2989 Change Plus runner name
  .github/workflows/build.yml
  site/content/how-to/monitoring/tracing.md
Labels: documentation, chore

#2987 Add guide for UpstreamSettingsPolicy
  examples/upstream-settings-policy/1m-zone-size.yaml
  examples/upstream-settings-policy/README.md
  examples/upstream-settings-policy/app.yaml
  examples/upstream-settings-policy/httproutes.yaml
  examples/upstream-settings-policy/upstream-keepalives.yaml
  site/content/how-to/monitoring/tracing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/how-to/traffic-management/upstream-settings.md
  site/content/overview/custom-policies.md
  site/content/overview/nginx-plus.md
  site/content/overview/resource-validation.md
Labels: documentation, release-notes

#3000 Update from nginxinc to nginx (3)
  .github/workflows/dependency-review.yml
  .github/workflows/labeler.yml
  README.md
  apis/v1alpha2/policy_methods.go
  design/archive/gateway-evaluation.md
  examples/grpc-routing/helloworld.yaml
  go.mod
  go.sum
  internal/mode/static/manager.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/data_attributes_generated.go
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/exporter.go
  internal/mode/static/telemetry/job_worker_test.go
  internal/mode/static/telemetry/ngfresourcecounts_attributes_generated.go
  internal/mode/static/telemetry/telemetryfakes/fake_exporter.go
  renovate.json
  site/content/how-to/monitoring/prometheus.md
  site/content/overview/nginx-plus.md
  tests/conformance/conformance_test.go
  tests/go.mod
  tests/go.sum
  tests/scripts/vars.env-example
  tests/suite/manifests/clientsettings/grpc-backend.yaml
  tests/suite/manifests/snippets-filter/grpc-backend.yaml
  tests/suite/manifests/upstream-settings-policy/grpc-backend.yaml
Labels: documentation, dependencies, chore

#2991 feat: Restructure how-to section layout, update frontmatter
  site/content/how-to/control-plane-configuration.md
  site/content/how-to/data-plane-configuration.md
  site/content/how-to/monitoring/_index.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/how-to/traffic-management/https-termination.md
  site/content/how-to/traffic-management/request-response-headers.md
  site/content/how-to/traffic-management/routing-traffic-to-your-app.md
  site/content/how-to/traffic-management/upgrade-apps-without-downtime.md
  site/content/how-to/traffic-security/_index.md
  site/content/how-to/traffic-security/integrating-cert-manager.md
  site/content/how-to/traffic-security/securing-backend-traffic.md
Labels: documentation

#3012 Update from nginxinc to nginx (3) (#3000)
  .github/workflows/dependency-review.yml
  .github/workflows/labeler.yml
  README.md
  apis/v1alpha2/policy_methods.go
  design/archive/gateway-evaluation.md
  examples/grpc-routing/helloworld.yaml
  go.mod
  go.sum
  internal/mode/static/manager.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/data_attributes_generated.go
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/exporter.go
  internal/mode/static/telemetry/job_worker_test.go
  internal/mode/static/telemetry/ngfresourcecounts_attributes_generated.go
  internal/mode/static/telemetry/telemetryfakes/fake_exporter.go
  renovate.json
  site/content/how-to/monitoring/prometheus.md
  site/content/overview/nginx-plus.md
  tests/conformance/conformance_test.go
  tests/go.mod
  tests/go.sum
  tests/scripts/vars.env-example
  tests/suite/manifests/clientsettings/grpc-backend.yaml
  tests/suite/manifests/snippets-filter/grpc-backend.yaml
  tests/suite/manifests/upstream-settings-policy/grpc-backend.yaml
Labels: documentation, dependencies, chore

#3020 (cherry-pick) Restructure how-to section layout, update frontmatter (#2991)
  site/content/how-to/control-plane-configuration.md
  site/content/how-to/data-plane-configuration.md
  site/content/how-to/monitoring/_index.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/how-to/traffic-management/https-termination.md
  site/content/how-to/traffic-management/request-response-headers.md
  site/content/how-to/traffic-management/routing-traffic-to-your-app.md
  site/content/how-to/traffic-management/upgrade-apps-without-downtime.md
  site/content/how-to/traffic-security/_index.md
  site/content/how-to/traffic-security/integrating-cert-manager.md
  site/content/how-to/traffic-security/securing-backend-traffic.md
Labels: documentation

#3021 Update main with 1.6.0
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
  site/content/get-started.md
  site/content/how-to/monitoring/prometheus.md
  site/content/how-to/traffic-management/advanced-routing.md
  site/content/how-to/traffic-management/client-settings.md
  site/content/how-to/traffic-management/request-response-headers.md
  site/content/how-to/traffic-management/snippets.md
  site/content/how-to/traffic-management/upgrade-apps-without-downtime.md
  site/content/includes/installation/install-gateway-api-experimental-features.md
  site/content/includes/installation/install-gateway-api-resources.md
  site/content/includes/installation/uninstall-gateway-api-resources.md
  site/content/installation/building-the-images.md
  site/content/installation/installing-ngf/helm.md
  site/content/installation/installing-ngf/manifests.md
  site/content/installation/nginx-plus-jwt.md
  site/content/overview/gateway-architecture.md
  tests/Makefile
Labels: documentation, chore, tests, helm-chart

#3018 move ks client reader to separated directory
  internal/framework/events/first_eventbatch_preparer.go
  internal/framework/events/first_eventbatch_preparer_test.go
  internal/framework/kubernetes/client.go
  internal/framework/kubernetes/kubernetesfakes/fake_reader.go
  internal/mode/static/telemetry/collector_test.go
Labels: tests

#3022 Deploy docs for release 1.6.0
  .github/workflows/docs-build-push.yml
Labels: documentation

#3031 Add more details to release process
  docs/developer/release-process.md
  tests/README.md
Labels: documentation, chore, tests

#3067 Listener Isolation for hostnames occupied by other listeners
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/route_common_test.go
  tests/Makefile
Labels: enhancement, tests

#3066 Allow configuration of NGINX Plus API access
  apis/v1alpha1/nginxproxy_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/nginx/conf/nginx-plus.conf
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/plus_api.go
  internal/mode/static/nginx/config/plus_api_template.go
  internal/mode/static/nginx/config/plus_api_test.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/nginxproxy.go
  internal/mode/static/state/graph/nginxproxy_test.go
  site/content/reference/api.md
Labels: documentation, enhancement, helm-chart

#3078 CP/DP Split: Fix empty plus file, blocking calls
  internal/mode/static/nginx/agent/agent.go
  internal/mode/static/nginx/agent/command.go
  internal/mode/static/nginx/agent/file.go
  internal/mode/static/nginx/config/plus_api.go
  internal/mode/static/nginx/config/plus_api_test.go
Labels: chore
