Repository nginx/nginx-gateway-fabric, pull requests merged in 2025-04, with the labels that each got.

#3278 CP/DP Split: Openshift support
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/README.md.gotmpl
  charts/nginx-gateway-fabric/templates/certs-job.yaml
  charts/nginx-gateway-fabric/templates/clusterrole.yaml
  charts/nginx-gateway-fabric/templates/deployment.yaml
  charts/nginx-gateway-fabric/templates/scc.yaml
  cmd/gateway/commands.go
  cmd/gateway/commands_test.go
  deploy/openshift/deploy.yaml
  internal/mode/static/config/config.go
  internal/mode/static/manager.go
  internal/mode/static/provisioner/eventloop.go
  internal/mode/static/provisioner/handler.go
  internal/mode/static/provisioner/objects.go
  internal/mode/static/provisioner/objects_test.go
  internal/mode/static/provisioner/openshift/openshift.go
  internal/mode/static/provisioner/openshift/openshiftfakes/fake_apichecker.go
  internal/mode/static/provisioner/provisioner.go
  internal/mode/static/provisioner/provisioner_test.go
  internal/mode/static/provisioner/setter.go
  internal/mode/static/provisioner/store.go
  internal/mode/static/provisioner/store_test.go
Labels: documentation, chore, helm-chart

#3297 Update README badge from slack to forum
  README.md
Labels: documentation, chore

#3306 Add support for RequestMirror filter
  internal/mode/static/nginx/config/http/config.go
  internal/mode/static/nginx/config/servers.go
  internal/mode/static/nginx/config/servers_template.go
  internal/mode/static/nginx/config/servers_test.go
  internal/mode/static/nginx/config/validation/http_validator.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/convert.go
  internal/mode/static/state/dataplane/convert_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/graph/backend_refs.go
  internal/mode/static/state/graph/backend_refs_test.go
  internal/mode/static/state/graph/common_filter.go
  internal/mode/static/state/graph/common_filter_test.go
  internal/mode/static/state/graph/extension_ref_filter.go
  internal/mode/static/state/graph/extension_ref_filter_test.go
  internal/mode/static/state/graph/grpcroute.go
  internal/mode/static/state/graph/grpcroute_test.go
  internal/mode/static/state/graph/httproute.go
  internal/mode/static/state/graph/httproute_test.go
  internal/mode/static/state/graph/route_common.go
  internal/mode/static/state/graph/tlsroute.go
  internal/mode/static/state/graph/tlsroute_test.go
  internal/mode/static/state/mirror/mirror.go
  internal/mode/static/state/mirror/mirror_test.go
  internal/mode/static/state/validation/validationfakes/fake_httpfields_validator.go
  internal/mode/static/state/validation/validator.go
Labels: enhancement, release-notes

#3337 Update README for nginx version
  README.md
Labels: documentation, chore

#3320 CP/DP Split: optimize configuration events
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/nginx/agent/action.go
  internal/mode/static/nginx/agent/action_test.go
  internal/mode/static/nginx/agent/agent.go
  internal/mode/static/nginx/agent/agent_test.go
  internal/mode/static/nginx/agent/agentfakes/fake_nginx_updater.go
  internal/mode/static/nginx/agent/deployment.go
  internal/mode/static/nginx/agent/deployment_test.go
  internal/mode/static/provisioner/templates.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/state/dataplane/configuration.go
  internal/mode/static/state/dataplane/configuration_test.go
  internal/mode/static/state/dataplane/types.go
  internal/mode/static/state/statefakes/fake_change_processor.go
  internal/mode/static/state/store.go
  internal/mode/static/state/store_test.go
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/telemetryfakes/fake_configuration_getter.go
  tests/suite/client_settings_test.go
Labels: chore, tests

#3342 Update Go to 1.24.2
  go.mod
  tests/framework/crossplane/go.mod
  tests/go.mod
Labels: dependencies, chore

#3349 CP/DP Split: Remove prometheus logger
  go.mod
  go.sum
  internal/mode/static/log_level_setters.go
  internal/mode/static/log_level_setters_test.go
  internal/mode/static/manager.go
  tests/go.mod
  tests/go.sum
  tests/suite/nginxgateway_test.go
Labels: dependencies, chore

#3348 Update Gateway API to v1.3.0
  README.md
  cmd/gateway/validation.go
  config/crd/gateway-api/experimental/kustomization.yaml
  config/crd/gateway-api/standard/kustomization.yaml
  go.mod
  go.sum
  internal/framework/gatewayclass/validate.go
  internal/mode/static/state/graph/gateway_test.go
  tests/go.mod
  tests/go.sum
Labels: documentation, enhancement, dependencies

#3343 CP/DP Split: Support configuring NodePorts
  apis/v1alpha2/nginxproxy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/templates/_helpers.tpl
  charts/nginx-gateway-fabric/templates/nginxproxy.yaml
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/mode/static/handler.go
  internal/mode/static/handler_test.go
  internal/mode/static/provisioner/handler.go
  internal/mode/static/provisioner/handler_test.go
  internal/mode/static/provisioner/objects.go
  internal/mode/static/provisioner/objects_test.go
  internal/mode/static/provisioner/provisioner.go
  internal/mode/static/provisioner/store.go
  internal/mode/static/provisioner/store_test.go
Labels: documentation, chore, helm-chart

#3338 CP/DP Split: Update documentation on accessing nginx container
  docs/developer/testing.md
  examples/cafe-example/README.md
  examples/cross-namespace-routing/README.md
  examples/grpc-routing/README.md
  examples/https-termination/README.md
  examples/traffic-splitting/README.md
Labels: documentation
