Repository nginx/nginx-gateway-fabric, pull requests merged in 2025-10, with the labels that each got.

#3983 Update Dockerfile alpine packages for cve fixes (#3973)
  build/Dockerfile.nginx
Labels: chore

#3990 Update main docs for release 2.1.3
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
Labels: documentation, helm-chart

#3993 Fix cves for libcrpyto3 and libssl3
  build/Dockerfile.nginx
Labels: chore

#3995 Fix cves for libcrpyto3 and libssl3 (#3993)
  build/Dockerfile.nginx
Labels: chore

#3996 Release 2.1.4 docs
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
  deploy/azure/deploy.yaml
  deploy/default/deploy.yaml
  deploy/experimental-nginx-plus/deploy.yaml
  deploy/experimental/deploy.yaml
  deploy/nginx-plus/deploy.yaml
  deploy/nodeport/deploy.yaml
  deploy/openshift/deploy.yaml
  deploy/snippets-filters-nginx-plus/deploy.yaml
  deploy/snippets-filters/deploy.yaml
Labels: documentation, helm-chart

#3997 Update main docs for release 2.1.4
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
Labels: documentation, helm-chart

#3989 Update readmes and makefiles
  operators/Makefile
  operators/README.md
  tests/Makefile
  tests/OPENSHIFT_CONFORMANCE.md
  tests/README.md
Labels: documentation, tests

#4004 Use relative module path for both UBI and Alpine builds
  build/ubi/Dockerfile.nginx
  build/ubi/Dockerfile.nginxplus
  examples/http-request-header-filter/headers.yaml
  internal/controller/nginx/conf/nginx-plus.conf
  internal/controller/nginx/conf/nginx.conf
Labels: chore

#4020 Add plus secrets for image building in tests
  .github/workflows/conformance.yml
  .github/workflows/functional.yml
Labels: bug
