Repository nginx/nginx-gateway-fabric, pull requests merged in 2025-02, with the labels that each got.

#3083 updated unit test files with logr.Discard
  cmd/gateway/initialize_test.go
  internal/framework/controller/register_test.go
  internal/framework/events/events_test.go
  internal/framework/events/loop_test.go
  internal/framework/runnables/cronjob_test.go
  internal/framework/status/leader_aware_group_updater_test.go
  internal/framework/status/updater_retry_test.go
  internal/framework/status/updater_test.go
  internal/mode/provisioner/handler_test.go
  internal/mode/static/config_updater_test.go
  internal/mode/static/handler_test.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/file/manager_test.go
  internal/mode/static/nginx/runtime/manager_test.go
  internal/mode/static/state/change_processor_test.go
  internal/mode/static/status/prepare_requests_test.go
  internal/mode/static/telemetry/job_worker_test.go
Labels: tests, tech-debt

#3104 Remove announce for slack
  .goreleaser.yml
Labels: chore

#3105 Remove announce for slack (#3104)
  .goreleaser.yml
Labels: chore

#3129 Update main for 1.6.1 release
  CHANGELOG.md
  README.md
  charts/nginx-gateway-fabric/Chart.yaml
  charts/nginx-gateway-fabric/README.md
Labels: documentation, chore, helm-chart

#3136 Fix revert commit for leader election
  internal/framework/runnables/runnables.go
  internal/framework/runnables/runnables_test.go
  internal/mode/static/manager.go
Labels: bug

#3147 CP/DP split: Support nginx debug mode when provisioning Data Plane
  apis/v1alpha2/nginxproxy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  build/entrypoint.sh
  charts/nginx-gateway-fabric/templates/nginxproxy.yaml
  config/crd/bases/gateway.nginx.org_nginxproxies.yaml
  deploy/crds.yaml
  internal/mode/static/provisioner/objects.go
  internal/mode/static/state/graph/nginxproxy_test.go
Labels: enhancement, helm-chart

#3158 Update documentation step for the release process
  .github/workflows/release-pr.yml
  docs/developer/release-process.md
Labels: documentation

#3181 Remove tools.go and require Go 1.24
  .golangci.yml
  go.mod
  internal/framework/controller/fakes.go
  internal/framework/events/handler.go
  internal/framework/kubernetes/client.go
  internal/framework/status/k8s_updater.go
  internal/mode/static/licensing/collector.go
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/policies/policy.go
  internal/mode/static/nginx/config/policies/validator.go
  internal/mode/static/nginx/file/manager.go
  internal/mode/static/nginx/runtime/manager.go
  internal/mode/static/nginx/runtime/verify.go
  internal/mode/static/state/change_processor.go
  internal/mode/static/state/resolver/resolver.go
  internal/mode/static/state/validation/validator.go
  internal/mode/static/telemetry/exporter.go
  tests/framework/crossplane/go.mod
  tests/go.mod
  tools.go
Labels: dependencies, chore
