Repository nginx/nginx-gateway-fabric, pull requests merged in 2025-05, with the labels that each got.

#3352 CP/DP Split: Collect telemetry for cp dp split
  internal/mode/static/telemetry/collector.go
  internal/mode/static/telemetry/collector_test.go
  internal/mode/static/telemetry/data.avdl
  internal/mode/static/telemetry/data_attributes_generated.go
  internal/mode/static/telemetry/data_test.go
  internal/mode/static/telemetry/ngfresourcecounts_attributes_generated.go
  tests/suite/telemetry_test.go
Labels: enhancement, tests

#3361 Remove unnecessary step in build file
  .github/workflows/build.yml
Labels: chore

#3370 CP/DP Split: fix label updates
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  go.mod
  go.sum
  internal/mode/static/provisioner/provisioner.go
  internal/mode/static/provisioner/setter.go
  internal/mode/static/provisioner/templates.go
  internal/mode/static/state/conditions/conditions.go
Labels: dependencies, chore

#3373 Update security workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/mend.yml
Labels: chore

#3386 Update service labels in NFR tests
  tests/Makefile
  tests/framework/ngf.go
  tests/scripts/remote-scripts/run-nfr-tests.sh
  tests/suite/manifests/dp-perf/gateway.yaml
  tests/suite/manifests/longevity/gateway.yaml
  tests/suite/manifests/ngf-upgrade/gateway-updated.yaml
  tests/suite/manifests/ngf-upgrade/gateway.yaml
  tests/suite/manifests/reconfig/gateway.yaml
  tests/suite/manifests/scale/matches.yaml
  tests/suite/manifests/scale/upstreams.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-1.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-10.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-11.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-12.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-13.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-14.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-15.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-16.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-17.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-18.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-19.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-2.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-20.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-21.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-22.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-23.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-24.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-25.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-3.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-4.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-5.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-6.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-7.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-8.yaml
  tests/suite/manifests/scale/zero-downtime/gateway-9.yaml
  tests/suite/system_suite_test.go
  tests/suite/upgrade_test.go
Labels: tests

#3392 Add GKE router to nfr workflow
  .github/workflows/nfr.yml
Labels: chore

#3390 Support sending chunked files to agent
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  go.mod
  go.sum
  internal/mode/static/nginx/agent/command.go
  internal/mode/static/nginx/agent/file.go
  internal/mode/static/nginx/agent/file_test.go
  internal/mode/static/nginx/config/generator.go
  internal/mode/static/nginx/config/generator_test.go
  internal/mode/static/nginx/config/main_config.go
Labels: enhancement, dependencies

#3396 Update agent collector config
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  go.mod
  go.sum
  internal/mode/static/provisioner/templates.go
Labels: dependencies, chore

#3402 Bulk delete namespaces in reconfiguration nfr test
  tests/framework/resourcemanager.go
  tests/suite/reconfig_test.go
Labels: tests

#3399 Support provisioning of Gateway(s) in helm chart
  charts/nginx-gateway-fabric/README.md
  charts/nginx-gateway-fabric/README.md.gotmpl
  charts/nginx-gateway-fabric/templates/gateway.yaml
  charts/nginx-gateway-fabric/values.schema.json
  charts/nginx-gateway-fabric/values.yaml
Labels: documentation, helm-chart

#3415 Don't run Mend on fork
  .github/workflows/mend.yml
Labels: chore

#3417 Add actions to CodeQL to satisfy scanning
  .github/workflows/codeql-analysis.yml
Labels: chore

#3416 Update libxml for CVEs
  build/Dockerfile.nginx
Labels: dependencies

#3423 Update agent v3 to latest version
  build/Dockerfile.nginx
  build/Dockerfile.nginxplus
  go.mod
  go.sum
Labels: dependencies
